V3.fcrNative = (() => {
  const C=V3.core;
  const exactBin=(payload,aliases)=>{
    const wanted=V3.fcrAudit.preferredAliases(aliases),matches=(payload?.items||[]).filter(item=>{const fnsku=C.upper(item.skuDetail?.fnSku);if(aliases.some(alias=>/^(?:X0|ZZ)[A-Z0-9]{8}$/.test(C.upper(alias)))&&fnsku&&!wanted.has(fnsku))return false;return [item.scannableId,item.value,item.scannedBarcode,fnsku,item.skuDetail?.asin,item.skuDetail?.fcSku].map(C.upper).some(code=>wanted.has(code));});
    const sizes=[...new Set(matches.map(item=>C.clean(item.binDescription)).filter(Boolean))];if(sizes.length!==1)throw new Error(sizes.length?'Conflicting exact-item bin descriptions':'No exact-item bin description');return sizes[0];
  };
  function mount({life,telemetry,fcr,print,move,unbind}={}) {
    const measurement=V3.measurement.create({life}),mounted=new WeakSet();let hoverGeneration=0;
    const message=document.createElement('div');message.dataset.bwu2Ui='1';message.className='v3-note';
    const readBin=async(product,inventory)=>{const aliases=[product.asin,product.isbn,product.fnsku,product.fcsku],wanted=V3.fcrAudit.preferredAliases(aliases);
      const row=V3.fcr.inventoryRows({querySelector:()=>inventory}).find(row=>[row.asin,row.fnsku,row.fcsku].map(C.upper).some(code=>wanted.has(code))&&C.container(row.container));
      if(!row)throw new Error('No exact-item native inventory container');
      const response=await C.request('https://aft-poirot-website-nrt.nrt.proxy.amazon.com/api/scanitem',{method:'POST',body:JSON.stringify({containerScannableId:row.container,itemBarcode:product.fnsku||product.asin,isMasterpack:null,itemAndonContext:null,requestId:'amzn1.fc.v1.common.request-id.v1.AFTPoirotWebsite.'+crypto.randomUUID(),tool:'V3'}),headers:{'Content-Type':'application/json'},signal:life.signal});return exactBin(response.data,aliases);
    };
    const decorateProduct=async table=>{if(mounted.has(table))return;mounted.add(table);const product=V3.fcr.product(table.outerHTML);if(!product)return;
      const strip=document.createElement('div');strip.dataset.bwu2Ui='1';strip.className='v3-row';strip.innerHTML='<b>V3 '+C.esc(V3.build.version)+'</b><span>Sortable: '+C.esc(product.sortableText||'UNKNOWN')+'</span><span>'+C.esc(product.dimensions)+(product.suspicious?' · CHECK DIMENSIONS':'')+'</span><button class="v3-btn" data-size>Size: CHECK…</button><button class="v3-btn" data-madcat>Madcat: CHECK…</button><span data-msg></span>';table.after(strip);
      const size=strip.querySelector('[data-size]'),madcat=strip.querySelector('[data-madcat]'),msg=strip.querySelector('[data-msg]'),code=product.fnsku||product.asin;let sizeBusy=false,madcatBusy=false;
      const bin=async()=>{if(sizeBusy)return;sizeBusy=true;size.textContent='Size: CHECK…';try{const inventory=await V3.native.waitFor(()=>document.querySelector('#table-inventory'),{life,timeout:12000});const value=await readBin(product,inventory);if(strip.isConnected)size.textContent='Size: '+value;}catch(error){size.textContent='Size: ERROR ↻';size.title=error.message;}finally{sizeBusy=false;}};
      const check=async(force=false)=>{if(madcatBusy)return;madcatBusy=true;madcat.textContent='Madcat: CHECK…';try{const value=await measurement.lookup(code,force);if(strip.isConnected){madcat.textContent='Madcat: '+(value.madcat?'YES':'NO');madcat.title='Raw native measurement events · rolling 30 days';}}catch(error){madcat.textContent='Madcat: AUTH / RETRY';madcat.title=error.message+' · click to open native Measurement, then retry';}finally{madcatBusy=false;}};
      size.onclick=()=>void bin();madcat.onclick=()=>{if(madcat.textContent.includes('AUTH'))measurement.open(code);void check(true);};
      void bin();void check();
      for(const row of table.querySelectorAll('tr'))if(/^(ASIN|ISBN|FNSKU|FCSKU)$/i.test(C.clean(row.querySelector('th')?.textContent)))row.querySelector('td')?.setAttribute('data-v3-exact-code',C.clean(row.querySelector('td')?.textContent));
      msg.textContent='';
    };
    const decorateInventory=table=>{if(mounted.has(table))return;mounted.add(table);const current=C.clean(new URL(location.href).searchParams.get('s'));
      const indexes=V3.fcr.inventoryIndexes(table),groups=new Map();for(const row of table.tBodies?.[0]?.rows||[]){const code=index=>C.upper(row.cells[index]?.textContent),container=code(indexes.container)||C.upper(current),fnsku=code(indexes.fnsku),fcsku=code(indexes.fcsku);if(!container||!fnsku||!fcsku)continue;const key=container+'|'+fnsku;if(!groups.has(key))groups.set(key,{rows:[],fcskus:new Set()});groups.get(key).rows.push(row);groups.get(key).fcskus.add(fcsku);}
      const conflicts=[...groups.values()].filter(group=>group.fcskus.size>1);for(const group of conflicts)for(const row of group.rows){row.style.outline='3px solid #8b1d1d';row.style.outlineOffset='-3px';row.title='FCSKU CONFLICT · '+[...group.fcskus].join(' + ');}if(conflicts.length){const badge=document.createElement('b');badge.dataset.bwu2Ui='1';badge.className='v3-bad';badge.textContent='FCSKU CONFLICT: '+conflicts.length;table.before(badge);}
      if(C.container(current)){const strip=document.createElement('div');strip.dataset.bwu2Ui='1';strip.className='v3-row';let floor=localStorage.getItem('bwu2.v3.fcr.floor')||'P2';
        const paint=()=>{strip.innerHTML='<b>MOVE '+C.esc(current)+'</b>'+V3.actions.FLOORS.map(value=>'<button class="v3-btn'+(value===floor?' primary':'')+'" data-floor="'+value+'">'+value+'</button>').join('')+'<span>|</span>'+[{key:'PRIME',label:'PRIME'},...V3.actions.dropChoices(floor)].map(row=>'<button class="v3-btn" data-drop="'+row.key+'">'+C.esc(row.label)+'</button>').join('')+'<button class="v3-btn danger" data-unbind>UNBIND</button>';
          for(const btn of strip.querySelectorAll('[data-floor]'))btn.onclick=()=>{floor=btn.dataset.floor;localStorage.setItem('bwu2.v3.fcr.floor',floor);paint();};
          for(const btn of strip.querySelectorAll('[data-drop]'))btn.onclick=()=>void move.runContext({container:current,destination:V3.actions.destination(floor,btn.dataset.drop)});strip.querySelector('[data-unbind]').onclick=()=>void unbind.runContext({container:current});};paint();table.before(strip,message);
      }
      const hover=document.createElement('div');hover.dataset.bwu2Ui='1';hover.hidden=true;hover.className='v3-section';hover.style.cssText='position:fixed;left:12px;bottom:60px;z-index:2147482998;max-width:460px;pointer-events:none';document.body.appendChild(hover);life.own(()=>hover.remove());
      life.on(table,'mouseover',event=>{const link=event.target.closest('a');if(!link||link.contains(event.relatedTarget))return;const code=C.clean(link.textContent);if(!/^[A-Z0-9]{10}$/i.test(code))return;const generation=++hoverGeneration;
        void fcr.product(code).then(product=>{if(generation!==hoverGeneration||!product)return;hover.innerHTML=(product.img?'<img width="100" src="'+C.esc(product.img)+'" alt="">':'')+'<b>'+C.esc(product.title)+'</b><div>'+C.esc(product.dimensions)+' · '+C.esc(product.weight)+' · Sortable '+C.esc(product.sortableText)+'</div>';hover.hidden=false;}).catch(error=>{if(generation===hoverGeneration)message.textContent=error.message;});});
      life.on(table,'mouseout',event=>{if(event.target.closest('a')&&!event.target.closest('a').contains(event.relatedTarget)){hoverGeneration++;hover.hidden=true;}});
    };
    life.on(document,'click',event=>{if(!event.altKey)return;const cell=event.target.closest('td[data-v3-exact-code],#table-inventory td,#table-product td,.a-keyvalue td');if(!cell||cell.closest('[data-bwu2-ui]'))return;
      const code=C.clean(cell.dataset.v3ExactCode||event.target.closest('a')?.textContent||cell.textContent);if(!/^(?:[A-Z0-9]{10}|(?:ts|cs)x[0-9a-z_-]+|dz-[0-9a-z_-]+)$/i.test(code))return;event.preventDefault();event.stopPropagation();void(async()=>{let title='';if(/^[A-Z0-9]{10}$/i.test(code)){const product=await fcr.product(code);if(product&&[product.asin,product.isbn,product.fnsku,product.fcsku].map(C.upper).includes(C.upper(code)))title=product.title;}await print(code,title);})().then(()=>{message.textContent='Printed '+code;}).catch(error=>{message.textContent='Print failed · '+error.message;});},true);
    life.on(document,'copy',event=>{const selection=window.getSelection();if(!selection||selection.isCollapsed)return;const node=selection.anchorNode?.parentElement,cell=node?.closest('td[data-v3-exact-code]');if(!cell||cell!==selection.focusNode?.parentElement?.closest('td[data-v3-exact-code]'))return;event.clipboardData?.setData('text/plain',cell.dataset.v3ExactCode);event.preventDefault();});
    const sections=[...document.querySelectorAll('[data-section-type]')];for(const section of sections){const endpoint=section.dataset.sectionType;if(!endpoint||endpoint==='product'||endpoint==='inventory')continue;const heading=section.querySelector('h2,h3,.a-box-inner .a-row')||section.firstElementChild;if(!heading)continue;const toggle=document.createElement('button');toggle.className='v3-btn';toggle.dataset.bwu2Ui='1';toggle.textContent='HIDE';heading.appendChild(toggle);toggle.onclick=event=>{event.stopPropagation();const content=section.querySelector('table');if(!content)return;content.hidden=!content.hidden;toggle.textContent=content.hidden?'SHOW':'HIDE';};}
    for(const [selector,decorate] of [['[data-section-type="product"] .a-keyvalue,#table-product,.a-box-group .a-keyvalue',decorateProduct],['#table-inventory',decorateInventory]]){
      const existing=document.querySelector(selector);if(existing)void decorate(existing);else void V3.native.waitFor(()=>document.querySelector(selector),{life,timeout:15000}).then(decorate).catch(error=>{if(error.name!=='AbortError')telemetry.emit('native.section.unavailable',{selector});});
    }
  }
  return Object.freeze({mount,exactBin});
})();
