V3.sidelineUi=(()=>{
  function mount(root,{engine,title='Sideline'}={}){
    const state={source:'',destination:'',items:'',lookups:new Map(),queue:[],active:0,generation:0,running:false,paused:false,stop:false,clearSource:true,delay:true,expiry:null,dates:new Map(),aside:new Map(),attention:'',done:false};
    root.innerHTML='<section class="section"><b>'+V3.base.esc(title)+'</b><div class="grid" style="margin-top:9px"><label class="field">Source<input data-source></label><label class="field">Destination<input data-dest></label></div><label class="field">Item barcodes<textarea data-items></textarea></label><div class="row"><span class="ok" data-good>0 GOOD</span><span class="warn" data-date>0 DATE</span><span class="bad" data-aside>0 ASIDE</span><span class="note" data-check>0 CHECKING</span></div><div class="row" style="margin-top:9px"><button class="btn" data-clear>CLEAR SOURCE: ON</button><button class="btn" data-delay>DELAY: ON</button><button class="btn" data-pause hidden>PAUSE</button></div><div class="row" style="margin-top:9px"><button class="btn primary" data-run>RUN</button><button class="btn danger" data-stop>STOP AFTER CURRENT</button></div><div class="note" data-msg style="margin-top:8px"></div><div class="bad" data-attention style="margin-top:8px"></div></section><section class="section"><b>Preflight</b><div data-list style="margin-top:8px"></div></section>';
    const q=s=>root.querySelector(s),source=q('[data-source]'),dest=q('[data-dest]'),items=q('[data-items]'),list=q('[data-list]'),msg=q('[data-msg]'),attention=q('[data-attention]');
    const parsed=()=>{const map=new Map();for(const line of String(state.items||'').split(/\r?\n/)){const code=V3.base.clean(line.split(/\s+/)[0]);if(!code)continue;const key=V3.base.upper(code),entry=map.get(key)||{code,qty:0};entry.qty++;map.set(key,entry);}return[...map.values()];};
    const key=code=>V3.base.upper(state.source)+'|'+V3.base.upper(code);
    const reset=()=>{state.generation++;state.lookups.clear();state.queue=[];state.active=0;state.expiry=null;state.dates.clear();state.aside.clear();state.done=false;};
    const status=(text,tone='')=>{msg.className='note '+tone;msg.textContent=text;};
    const schedule=()=>{if(state.running||!V3.base.container(state.source))return;for(const item of parsed()){const k=key(item.code);if(state.lookups.has(k))continue;const e={key:k,code:item.code,generation:state.generation,state:'queued',result:null,error:''};state.lookups.set(k,e);state.queue.push(e);}pump();paint();};
    const pump=()=>{while(!state.running&&state.active<5&&state.queue.length){const e=state.queue.shift();if(!e||e.generation!==state.generation)continue;state.active++;e.state='checking';paint();engine.preflight(state.source,e.code).then(result=>{if(e.generation!==state.generation)return;e.result=result;e.state=result.kind;if(result.kind==='red')state.aside.set(V3.base.upper(e.code),result.reason);if(result.kind==='retry')e.error=result.reason;}).catch(error=>{if(e.generation===state.generation){e.state='retry';e.error=String(error.message||error);}}).finally(()=>{state.active--;pump();paint();});}};
    const settle=async()=>{schedule();const start=Date.now();while(state.active||state.queue.length){if(Date.now()-start>30000)throw new Error('Preflight did not settle');await new Promise(r=>setTimeout(r,60));}for(const item of parsed()){const e=state.lookups.get(key(item.code));if(!e||['queued','checking','retry'].includes(e.state))throw new Error(e?.error||'Preflight incomplete: '+item.code);if(e.state==='yellow'&&!state.dates.has(V3.base.upper(item.code)))throw new Error('Date required: '+item.code);}return parsed();};
    const paint=()=>{
      let good=0,date=0,aside=0,checking=0;const rows=[];
      for(const item of parsed()){const e=state.lookups.get(key(item.code)),st=e?.state||'checking';if(st==='green')good+=item.qty;else if(st==='yellow')date+=item.qty;else if(st==='red')aside+=item.qty;else checking+=item.qty;
        let extra='';
        if(st==='yellow'&&!state.dates.has(V3.base.upper(item.code)))extra='<div class="row" style="margin-top:5px"><input class="input" type="date" data-exp="'+V3.base.esc(item.code)+'"><button class="btn" data-apply="'+V3.base.esc(item.code)+'">APPLY</button></div>';
        rows.push('<div style="padding:7px;border-bottom:1px solid #39475b"><div class="row"><b>'+V3.base.esc(item.code)+' ×'+item.qty+'</b><span class="'+(st==='green'?'ok':st==='yellow'?'warn':st==='red'?'bad':'note')+'">'+st.toUpperCase()+'</span></div><div class="note">'+V3.base.esc(e?.result?.reason||e?.error||'CHECKING')+'</div>'+extra+'</div>');
      }
      q('[data-good]').textContent=good+' GOOD';q('[data-date]').textContent=date+' DATE';q('[data-aside]').textContent=aside+' ASIDE';q('[data-check]').textContent=checking+' CHECKING';list.innerHTML=rows.join('')||'<div class="note">Enter source + items to preflight.</div>';
      for(const button of list.querySelectorAll('[data-apply]'))button.onclick=()=>{const code=button.dataset.apply,e=state.lookups.get(key(code)),input=list.querySelector('[data-exp="'+CSS.escape(code)+'"]');try{const chosen=engine.expiration(e.result.ctx,input.value);if(state.expiry!=null&&state.expiry!==chosen.finalExpirationMs){state.aside.set(V3.base.upper(code),'MIXED EXPIRY — NEXT WORKFLOW');e.state='red';e.result={...e.result,kind:'red',reason:'MIXED EXPIRY — NEXT WORKFLOW'};}else{if(state.expiry==null)state.expiry=chosen.finalExpirationMs;state.dates.set(V3.base.upper(code),chosen);}paint();}catch(error){status(String(error.message||error),'bad');}};
      attention.innerHTML=state.attention?'<b>'+V3.base.esc(state.attention)+'</b><br><button class="btn danger" data-ack style="margin-top:6px">I VERIFIED IT · CLEAR ATTENTION</button>':'';attention.querySelector('[data-ack]')?.addEventListener('click',()=>{state.attention='';reset();paint();status('Attention cleared after verification');});
      q('[data-run]').disabled=Boolean(state.attention);
    };
    source.oninput=()=>{const next=V3.base.clean(source.value);if(V3.base.upper(next)!==V3.base.upper(state.source)){state.source=next;reset();}else state.source=next;schedule();};
    dest.oninput=()=>{const next=V3.base.clean(dest.value);if(V3.base.upper(next)!==V3.base.upper(state.destination)){state.destination=next;reset();}else state.destination=next;};
    items.oninput=()=>{state.items=items.value;schedule();};
    q('[data-clear]').onclick=()=>{state.clearSource=!state.clearSource;q('[data-clear]').textContent='CLEAR SOURCE: '+(state.clearSource?'ON':'OFF');};
    q('[data-delay]').onclick=()=>{state.delay=!state.delay;q('[data-delay]').textContent='DELAY: '+(state.delay?'ON':'OFF');};
    q('[data-pause]').onclick=()=>{state.paused=!state.paused;q('[data-pause]').textContent=state.paused?'RESUME':'PAUSE';};
    q('[data-stop]').onclick=()=>{state.stop=true;state.paused=false;status('STOP REQUESTED','warn');};
    q('[data-run]').onclick=async()=>{
      if(state.running)return;if(state.done)reset();state.stop=false;
      try{if(!V3.base.container(state.source)||!V3.base.container(state.destination))throw new Error('Source and destination must be tsX/csX');if(V3.base.upper(state.source)===V3.base.upper(state.destination))throw new Error('Source and destination cannot match');const all=await settle(),movable=all.filter(x=>!state.aside.has(V3.base.upper(x.code)));if(!movable.length)throw new Error('Nothing moveable');state.running=true;q('[data-pause]').hidden=false;status('Validating source','warn');const meta=await engine.validateSource(state.source);let moved=0,failed=0;
        for(let i=0;i<movable.length;i++){if(state.stop)throw new Error('Stopped before next item');while(state.paused&&!state.stop)await new Promise(r=>setTimeout(r,80));if(i>0&&state.delay)await new Promise(r=>setTimeout(r,2000+Math.floor(Math.random()*6001)));const item=movable[i],e=state.lookups.get(key(item.code)),chosen=state.dates.get(V3.base.upper(item.code));status((i+1)+'/'+movable.length+' '+item.code+' ×'+item.qty,'warn');try{await engine.move({source:state.source,destination:state.destination,sourceMeta:meta,preflightResult:e.result,qty:item.qty,expirationMs:chosen?.finalExpirationMs??null});moved+=item.qty;}catch(error){if(error?.outcome==='unknown'){state.attention='OUTCOME UNKNOWN — VERIFY '+item.code+' BEFORE RETRY';throw error;}failed+=item.qty;state.aside.set(V3.base.upper(item.code),String(error.message||error));}}
        if(state.clearSource&&failed===0&&state.aside.size===0)await engine.close(state.source,true);state.done=true;status('COMPLETE · moved '+moved+(failed?' · failed '+failed:''),failed?'warn':'ok');
      }catch(error){status((error?.outcome==='unknown'?'OUTCOME UNKNOWN — VERIFY · ':'')+String(error.message||error),error?.outcome==='unknown'?'bad':'warn');}
      finally{state.running=false;state.paused=false;q('[data-pause]').hidden=true;paint();}
    };
    paint();return Object.freeze({dispose:()=>{state.stop=true;state.paused=false;}});
  }
  return Object.freeze({mount});
})();