V3.sideline=(()=>{
  const ORIGIN='https://aft-poirot-website-nrt.nrt.proxy.amazon.com',TOOL='V3';
  const API={bootstrap:'/api/get-bootstrap-data',source:'/api/scan-source-container',item:'/api/scanitem',move:'/api/move-items',close:'/api/close-container'};
  const requestId=()=> 'amzn1.fc.v1.common.request-id.v1.AFTPoirotWebsite.'+(crypto?.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2));
  const sourcePayload=container=>({containerScannableId:container,requestId:requestId(),tool:TOOL});
  const itemPayload=(source,barcode)=>({containerScannableId:source,itemBarcode:barcode,isMasterpack:null,itemAndonContext:null,requestId:requestId(),tool:TOOL});
  const closePayload=(container,empty)=>({containerScannableId:container,containerEmpty:empty===true,directedLabel:false,processPath:'UNDETERMINED',requestId:requestId(),tool:TOOL});
  const problems=r=>(Array.isArray(r?.problems)?r.problems:[]).map(p=>V3.base.clean(p?.description||p?.message||p?.reason||p?.code||p?.['@type']||'')).filter(Boolean);
  const hazmatRejected=r=>{if(!r||typeof r!=='object')return false;const f=r.filterResult||{},reason=f.reason||{},rr=r.reason||{},ps=problems(r),labels=[r.message,r.description,r.errorMessage,r.errorCode,typeof r.reason==='string'?r.reason:'',rr.type,rr.description,rr.message,rr['@type'],reason.type,reason.description,reason.message,reason['@type'],f.filterType,...ps].map(V3.base.clean).filter(Boolean);return labels.some(x=>/hazmat|dangerous.?goods/i.test(x))&&(r.success===false||f.compatible===false||ps.length>0||r.errorMessage||r.errorCode||/error|reject|incompat|filter/i.test(V3.base.clean(r['@type'])));};
  const predicant=v=>{if(v==null)return false;if(typeof v==='string')return/predicant/i.test(v);if(Array.isArray(v))return v.some(predicant);if(typeof v!=='object')return false;return Object.entries(v).some(([k,x])=>(/predicant/i.test(k)&&(x===true||(typeof x==='string'&&x&&!/^false$/i.test(x))))||predicant(x));};
  const damaged=r=>r?.filterResult?.compatible===false&&(r.filterResult?.reason?.containerDamaged===true||V3.base.lower(r.filterResult?.reason?.['@type'])==='damageditemsfilterresultreason'||/damageditemsfilter/i.test(V3.base.clean(r.filterResult?.filterType)));
  const overageLabel=v=>/\boverage(?:s)?\b|\bitem\s+not\s+in\s+(?:source\s+)?container\b|\bnot\s+in\s+source\s+container\b/i.test(V3.base.clean(v));
  const allowedOverage=r=>{if(!r||typeof r!=='object')return false;const type=V3.base.clean(r['@type']);if(type==='InvalidBarcodeResponse'||type==='RequestMultipleBarcodesResponse'||hazmatRejected(r)||predicant(r)||damaged(r))return false;const f=r.filterResult,fr=V3.base.clean(f?.reason?.type||f?.reason?.description||f?.reason?.message||f?.reason?.['@type']||f?.filterType||''),ps=problems(r);if(f?.compatible===false&&!overageLabel(fr))return false;if(ps.some(x=>!overageLabel(x)))return false;const diag=[r.message,r.description,r.errorMessage,r.errorCode,fr,...ps].map(V3.base.clean).filter(Boolean);return(overageLabel(type)||diag.some(overageLabel))&&!/hazmat|dangerous.?goods|invalid\s+barcode|incompatib|damaged|predicant|customer\s*bound/i.test([type,...diag].join(' '));};
  const resolve=(r,barcode)=>{const type=V3.base.clean(r?.['@type']),overage=allowedOverage(r);if(!r||type==='InvalidBarcodeResponse'||(r.success===false&&!overage))return{ok:false,invalid:type==='InvalidBarcodeResponse',type:type||'Unknown'};const records=(Array.isArray(r.items)?r.items:[]).filter(x=>x?.skuDetail),item=records[0],sku=item?.skuDetail;if(!item||!sku)return{ok:false,invalid:false,type:type||'Unknown'};return{ok:true,type,barcode,item,records,sku,asin:V3.base.clean(sku.asin),fnsku:V3.base.clean(sku.fnSku),fcsku:V3.base.clean(sku.fcSku),dateType:V3.base.clean(sku.datelotDetail?.expirationPromptType),dateDetail:sku.datelotDetail||{},hazmat:sku.hazmat===true,permissionLevel:V3.base.upper(sku.itemDropzoneRecommendation?.permissionLevel),overage,notInSource:type==='ItemNotInContainerResponse'||records.every(x=>Number(x.quantity)===0)};};
  const classify=(r,code)=>{const ctx=resolve(r,code),text=[r?.['@type'],r?.message,r?.description,r?.errorMessage,r?.errorCode,r?.filterResult?.filterType,r?.filterResult?.reason?.type,...problems(r)].map(V3.base.clean).join(' ');if(/damaged/i.test(text))return{kind:'red',reason:'DAMAGED / INCOMPATIBLE',ctx};if(hazmatRejected(r))return{kind:'red',reason:'HAZMAT / DANGEROUS GOODS',ctx};if(!ctx.ok)return{kind:'red',reason:ctx.invalid?'INVALID BARCODE':ctx.type==='RequestMultipleBarcodesResponse'?'MULTIPLE BARCODE MATCHES':ctx.type,ctx};if(ctx.permissionLevel==='UNDER_REVIEW')return{kind:'red',reason:'ASIN UNDER REVIEW — RIVER REQUIRED',ctx};if(ctx.dateType==='EXPIRATION_DATE'||ctx.dateType==='PRODUCTION_DATE')return{kind:'yellow',reason:ctx.dateType==='PRODUCTION_DATE'?'PRODUCTION DATE':'EXPIRY DATE',ctx};return{kind:'green',reason:'GOOD TO GO',ctx};};
  const movePayload=(source,dest,meta,ctx,qty,expirationMs)=>({itemExternalId:null,sourceContainerScannableId:source,destinationContainerScannableId:dest,scannableId:V3.base.clean(ctx.item.scannableId||ctx.barcode),quantity:String(Math.max(1,Number(qty)||1)),itemDetails:(ctx.records?.length?ctx.records:[ctx.item]).map(record=>({fcsku:V3.base.clean((record.skuDetail||ctx.sku).fcSku),quantity:Number(record.quantity)||0,consumerType:record.consumer??null,disposition:record.disposition??null,referenceId:record.referenceId??null,fnsku:V3.base.clean((record.skuDetail||ctx.sku).fnSku)})),foundProblems:[null,null,null],scannedSourceContainerAsDestination:false,datelotDetail:ctx.sku.datelotDetail||null,userEnteredExpirationDate:expirationMs,mlcCaptureDetail:{mlcClass:ctx.sku.mlcDetail?.mlcClass??'UNKNOWN',userEnteredLotCode:null,mlcMissing:ctx.sku.mlcDetail?.mlcMissing??false,mlcNotEnteredReason:null,mlcCaptureMethod:null},itemMovedToISS:false,candidatePurchaseOrders:[],packHierarchyDetail:null,itemAndonContext:null,processPath:meta?.processPath??'UNDETERMINED',requestId:requestId(),tool:TOOL});
  const reason=r=>hazmatRejected(r)?'HAZMAT':allowedOverage(r)?'OVERAGE':damaged(r)?'DESTINATION DAMAGED':predicant(r)?'PREDICANT':r?.filterResult?.compatible===false?V3.base.upper(r.filterResult?.reason?.type)||'DESTINATION INCOMPATIBLE':problems(r).join(', ')||V3.base.clean(r?.['@type']||'MOVE REJECTED').replace(/Response$/,'');
  function create({telemetry,pandash}={}){
    let warehousePromise=null;
    const request=(path,body,options={})=>V3.transport.gm(ORIGIN+path,{method:'POST',body:JSON.stringify(body),headers:{'content-type':'application/json'},timeout:options.timeout||15000,allowHttpError:options.allowHttpError===true});
    const warehouse=async()=>{if(warehousePromise)return warehousePromise;warehousePromise=(async()=>{try{const r=await V3.transport.gm(ORIGIN+API.bootstrap+'?tool='+encodeURIComponent(TOOL),{timeout:8000});const info=r.data?.warehouseInfo,c=V3.base.upper((typeof info==='string'?info:'')||info?.warehouseId||info?.id||info?.warehouse||info?.fc||r.data?.warehouseId);if(c)return c;}catch{}return V3.base.upper(V3.fcr?.warehouse?.()||'BWU2');})();return warehousePromise;};
    const haz= pandash||V3.pandash.create({telemetry,warehouse:()=> 'BWU2'});
    const validateSource=async source=>{source=V3.base.clean(source);if(!V3.base.container(source))throw new Error('Source must be tsX/csX');const r=await request(API.source,sourcePayload(source));if(/customer\s*bound\s*shipment/i.test(JSON.stringify(r.data||{})))throw new Error('CUSTOMER-BOUND SHIPMENT');if(V3.base.clean(r.data?.['@type'])!=='ScanSourceContainerResponse'||r.data?.success!==true)throw new Error(V3.base.clean(r.data?.message||r.data?.description||r.data?.errorMessage||r.data?.['@type'])||'SOURCE VALIDATION FAILED');return r.data;};
    const preflight=async(source,barcode)=>{barcode=V3.base.clean(barcode);const r=await request(API.item,itemPayload(source,barcode),{allowHttpError:true}),base=classify(r.data,barcode);if(base.ctx?.ok&&base.ctx.hazmat&&base.kind!=='red'){try{const h=await haz.check(base.ctx.asin);if(!h.allowed)return{kind:'red',reason:'HAZMAT L'+h.level+' — NOT PROCESSABLE',ctx:base.ctx,hazmat:h};return{...base,reason:base.kind==='yellow'?base.reason:'HAZMAT L'+h.level+' — OK TO PROCESS',hazmat:h};}catch(error){return{kind:'retry',reason:'HAZMAT CHECK FAILED — '+String(error.message||error),ctx:base.ctx};}}return base;};
    const move=async({source,destination,sourceMeta,preflightResult,qty=1,expirationMs=null})=>{const ctx=preflightResult?.ctx;if(!ctx?.ok)throw new Error('Item context not moveable');const op=V3.operation.create({kind:'sideline-move',ref:ctx.barcode,telemetry});op.submitted({qty});let r;try{r=await request(API.move,movePayload(source,destination,sourceMeta,ctx,qty,expirationMs),{allowHttpError:true});}catch(error){op.unknown({reason:'transport'});throw new V3.operation.UnknownError('Move submitted; confirmation lost',{cause:error});}if(r.status>=500){op.unknown({status:r.status});throw new V3.operation.UnknownError('Move HTTP '+r.status+'; verify before retry');}const payload=r.data;if(!payload||typeof payload!=='object'){op.unknown({reason:'unexpected-response'});throw new V3.operation.UnknownError('Unexpected move confirmation');}if(allowedOverage(payload)||(r.status>=200&&r.status<300&&payload.success===true&&payload.filterResult?.compatible!==false&&!hazmatRejected(payload)&&!predicant(payload))){op.confirmed({status:r.status});return payload;}const why=reason(payload);op.rejected({reason:why,status:r.status});throw new V3.operation.RejectedError(why,{data:payload,recoverable:predicant(payload)||damaged(payload)});};
    const close=async(container,empty=true)=>{container=V3.base.clean(container);if(!V3.base.container(container))throw new Error('Container must be tsX/csX');const op=V3.operation.create({kind:'sideline-close',ref:container,telemetry});op.submitted();let r;try{r=await request(API.close,closePayload(container,empty),{allowHttpError:true});}catch(error){op.unknown({reason:'transport'});throw new V3.operation.UnknownError('Close submitted; confirmation lost',{cause:error});}if(r.status>=200&&r.status<300&&V3.base.clean(r.data?.['@type'])==='CloseContainerResponse'&&r.data?.success===true){op.confirmed();return r.data;}if(r.status>=500||!r.data){op.unknown({status:r.status});throw new V3.operation.UnknownError('Close not confirmed — verify before retry');}op.rejected({status:r.status});throw new V3.operation.RejectedError(V3.base.clean(r.data?.message||r.data?.['@type'])||'Close rejected');};
    const expiration=(ctx,date)=>{const entered=new Date(String(date)+'T00:00:00').getTime();if(!Number.isFinite(entered))throw new Error('Invalid date');return{enteredMs:entered,finalExpirationMs:ctx.dateType==='PRODUCTION_DATE'?entered+Number(ctx.dateDetail?.shelfLife||0):entered};};
    return Object.freeze({warehouse,validateSource,preflight,move,close,expiration});
  }
  return Object.freeze({create,classify,resolve,allowedOverage,hazmatRejected});
})();