V3.boot=()=>{
  const life=V3.lifecycle.create('river'),telemetry=V3.telemetry.create('river',V3.build.version),store=V3.storage.create('river',1);
  const WORKFLOW_Q0='3654ec14-7232-4f65-84c3-87927cdb4d0c',WORKFLOW_ID='0dbb253e-c43a-4a8b-a316-e32b8ab9be21';
  const norm=v=>V3.base.lower(v).replace(/[^a-z0-9]+/g,' ').trim(),code=v=>V3.base.upper(v).replace(/[^A-Z0-9]/g,'');
  const visible=el=>{if(!el?.isConnected)return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden';};
  const headers=table=>{const wrap=table?.closest('.dataTables_wrapper,.dataTables_scroll')||table?.parentElement,head=wrap?.querySelector('.dataTables_scrollHead table')||table;return[...head?.querySelectorAll('thead th,thead td')||[]].map(x=>norm(x.textContent));};
  const col=(hs,...names)=>hs.findIndex(h=>names.some(n=>h===norm(n)||h.startsWith(norm(n)+' ')));
  const num=v=>{const t=V3.base.clean(v).replace(/,/g,'');if(!/^-?\d+(?:\.\d+)?$/.test(t))return null;const n=Number(t);return Number.isFinite(n)&&n>=0?n:null;};
  const date=v=>{const t=V3.base.clean(v),n=Date.parse(t);return Number.isFinite(n)?n:Number.NEGATIVE_INFINITY;};
  const vendor=v=>{const xs=(V3.base.clean(v).match(/[A-Z0-9]+/gi)||[]).map(x=>x.toUpperCase());return xs.find(x=>x.length>=2&&x.length<=6&&x!=='FBA')||'';};
  const poDetails=doc=>{const table=doc.querySelector('#table-purchase-order'),map=new Map();if(!table)return map;const hs=headers(table),pi=col(hs,'purchase order','po'),di=col(hs,'placed','confirmed','order date','date');if(pi<0)return map;[...table.querySelectorAll('tbody tr')].forEach((row,i)=>{const cs=[...row.children].filter(x=>x.matches?.('td,th')),po=V3.base.clean(cs[pi]?.textContent);if(!po)return;const ts=di>=0?date(cs[di]?.textContent):Number.NEGATIVE_INFINITY,old=map.get(code(po));if(!old||ts>old.ts)map.set(code(po),{po,ts,i});});return map;};
  const poRows=doc=>{const table=doc.querySelector('#table-purchase-order-item');if(!table)return[];const hs=headers(table),idx={po:col(hs,'purchase order','po'),sku:col(hs,'sku','fnsku','asin'),vendor:col(hs,'vendor code','seller id'),unfilled:col(hs,'unfilled'),cancelled:col(hs,'canceled','cancelled'),received:col(hs,'received'),title:col(hs,'title'),date:col(hs,'order date','placed','date')};if(idx.po<0||idx.sku<0)return[];return[...table.querySelectorAll('tbody tr')].map((row,i)=>{const cs=[...row.children].filter(x=>x.matches?.('td,th')),po=V3.base.clean(cs[idx.po]?.textContent);if(!po)return null;return{po,sku:V3.base.clean(cs[idx.sku]?.textContent),vendor:idx.vendor>=0?V3.base.clean(cs[idx.vendor]?.textContent):'',unfilled:idx.unfilled>=0?num(cs[idx.unfilled]?.textContent):null,cancelled:idx.cancelled>=0?num(cs[idx.cancelled]?.textContent):null,received:idx.received>=0?num(cs[idx.received]?.textContent):null,title:idx.title>=0?V3.base.clean(cs[idx.title]?.textContent):'',ts:idx.date>=0?date(cs[idx.date]?.textContent):Number.NEGATIVE_INFINITY,i,text:V3.base.clean(row.textContent)};}).filter(Boolean);};
  const selectPo=(itemDoc,detailDoc,identity)=>{const rows=poRows(itemDoc),details=poDetails(detailDoc),wanted=[identity.search,identity.asin,identity.fnsku].map(code).filter(Boolean),c=[];for(const row of rows){const sku=code(row.sku),text=code(row.text);let strength=0;if(sku&&wanted.includes(sku))strength=3;else if(wanted.some(x=>x.length>=8&&text.includes(x)))strength=2;else if(identity.title&&row.title&&norm(identity.title)===norm(row.title))strength=1;if(!strength)continue;const ts=Math.max(row.ts,details.get(code(row.po))?.ts??Number.NEGATIVE_INFINITY);c.push({...row,strength,ts});}if(!c.length)return null;c.sort((a,b)=>b.ts-a.ts||b.strength-a.strength||a.i-b.i);const x=c[0],parts=[x.unfilled,x.cancelled,x.received],known=parts.every(Number.isFinite),qty=known?parts.reduce((a,b)=>a+b,0):null;return{purchaseOrder:x.po,vendorCode:vendor(x.vendor)||'N/A',quantity:Number.isFinite(qty)&&qty>0?qty:null};};
  const riverUrl=warehouse=>{const u=new URL('https://river.amazon.com/'+encodeURIComponent(warehouse)+'/workflows');u.searchParams.set('buildingType','fc');u.searchParams.set('q0',WORKFLOW_Q0);u.searchParams.set('q1',WORKFLOW_ID);u.searchParams.set('id',WORKFLOW_ID);return u.href;};

  if(location.hostname!=='river.amazon.com'){
    const fcr=V3.fcr.create({telemetry,life}),panel=V3.ui.panel({id:'bwu2-v3-river-capture',title:'V3 · RIVER Capture',width:520,life});let mounted=false,payload=null;
    const mount=()=>{if(mounted)return;mounted=true;const root=document.createElement('div');root.innerHTML='<section class="section"><label class="field">Current item<input data-code></label><div class="row"><button class="btn primary" data-cap>CAPTURE</button><button class="btn" data-open>OPEN RIVER</button></div><div class="note" data-msg style="margin-top:8px"></div><div data-data style="margin-top:8px"></div></section>';panel.set(root);const input=root.querySelector('[data-code]'),msg=root.querySelector('[data-msg]'),dataBox=root.querySelector('[data-data]');input.value=V3.base.clean(new URLSearchParams(location.search).get('s'));const paint=()=>{dataBox.innerHTML=payload?'<div class="grid"><div class="note"><b>FNSKU</b><br>'+V3.base.esc(payload.fnsku)+'</div><div class="note"><b>PO</b><br>'+V3.base.esc(payload.purchaseOrder)+'</div><div class="note"><b>PO qty</b><br>'+(payload.poLineQuantity??'N/A')+'</div><div class="note"><b>Live qty</b><br>'+(payload.liveInventoryQuantity??'N/A')+'</div></div>':'';};root.querySelector('[data-cap]').onclick=async()=>{try{msg.className='note warn';msg.textContent='CAPTURING…';const search=V3.base.clean(input.value);if(!search)throw new Error('Search item required');const [product,inventory,itemHtml,poHtml]=await Promise.all([fcr.product(search),fcr.inventory(search,{allowPartial:false}),fcr.post('purchase-order-item',{s:search}),fcr.post('purchase-order',{s:search})]);if(!product)throw new Error('Product unavailable');const po=selectPo(V3.base.html(itemHtml),V3.base.html(poHtml),{search,asin:product.asin,fnsku:product.fnsku,title:product.title}),warehouse=V3.fcr.warehouse()||'BWU2';payload={asin:product.asin||'N/A',fnsku:product.fnsku||'N/A',title:product.title||'N/A',purchaseOrder:po?.purchaseOrder||'N/A',vendorCode:po?.vendorCode||'N/A',poLineQuantity:po?.quantity??null,liveInventoryQuantity:inventory.totalQuantity,inventoryCost:product.inventoryCost||'N/A',physicalLocation:'TBD',warehouseId:warehouse,riverUrl:riverUrl(warehouse),capturedAt:Date.now()};payload.quantityDisagreement=Number.isFinite(payload.poLineQuantity)&&Number.isFinite(payload.liveInventoryQuantity)&&payload.poLineQuantity!==payload.liveInventoryQuantity;await store.set('payload',payload);telemetry.emit('capture',{po:payload.poLineQuantity,live:payload.liveInventoryQuantity,disagreement:payload.quantityDisagreement});msg.className='note '+(payload.quantityDisagreement?'warn':'ok');msg.textContent=payload.quantityDisagreement?'QTY DISAGREES':'READY';paint();}catch(e){msg.className='note bad';msg.textContent=e.message;}};root.querySelector('[data-open]').onclick=async()=>{payload=payload||await store.get('payload',null);if(!payload?.riverUrl)return;if(typeof GM_openInTab==='function')GM_openInTab(payload.riverUrl,{active:true,insert:true});else window.open(payload.riverUrl,'_blank','noopener');};};
    V3.ui.dockButton({id:'river',label:'RIVER',title:'RIVER capture',onClick:()=>{mount();panel.open();}});return;
  }

  const panel=V3.ui.panel({id:'bwu2-v3-river-assistant',title:'V3 · RIVER Assistant',width:600,life});let watcher=null,severity=null;
  const field=aliases=>{const wanted=aliases.map(norm);for(const el of document.querySelectorAll('input,textarea,select')){if(!visible(el))continue;const label=V3.base.clean(el.getAttribute('aria-label')||el.placeholder||el.name||el.id||el.closest('label')?.textContent||'');if(wanted.some(x=>norm(label).includes(x)))return el;}return null;};
  const setValue=async(el,value)=>{if(!el||!visible(el)||el.disabled||el.readOnly)return false;const next=String(value??'');let p=el,setter=null;while((p=Object.getPrototypeOf(p))&&!setter)setter=Object.getOwnPropertyDescriptor(p,'value')?.set||null;if(setter)setter.call(el,next);else el.value=next;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>requestAnimationFrame(r));return V3.base.clean(el.value)===V3.base.clean(next);};
  const nextButton=()=>[...document.querySelectorAll('button,a,[role="button"],input[type="submit"],input[type="button"]')].filter(visible).find(x=>norm(x.innerText||x.textContent||x.value||'')==='next');
  const label=()=>V3.base.clean(document.querySelector('page-info[label]')?.getAttribute('label')||[...document.querySelectorAll('h1,h2,h3,h4,[role="heading"],legend')].find(visible)?.textContent||'');
  const page=()=>{const t=norm(label()),route=(location.pathname+' '+location.search+' '+location.hash).toLowerCase();if(t.includes('information')||field(['physical location of the units','inventory cost per unit']))return'information';if(t.includes('severity')||field(['units impacted']))return'severity';if(t==='asin'||t.includes('enter asin')||field(['type asin here']))return'asin';if(t.includes('pandash')||/pandash|dangerous/.test(route))return'pandash';if(t.includes('sortab')||/sortab/.test(route))return'sortability';if(t.includes('related')||/related.?tt/.test(route))return'related';if(t.includes('image'))return'images';if(t.includes('create issue'))return'create';if(t.includes('issue')&&t.includes('fc'))return'issue';return'unknown';};
  const choose=p=>{const po=Number(p?.poLineQuantity),live=Number(p?.liveInventoryQuantity),a=Number.isFinite(po)&&po>0,b=Number.isFinite(live)&&live>0;if(a&&b&&po!==live)return{value:null,reason:'PO qty '+po+' ≠ live inventory '+live,po,live};if(a&&b)return{value:po,reason:'PO/live agree'};if(b)return{value:live,reason:'live inventory only'};if(a)return{value:po,reason:'PO only'};return{value:null,reason:'No positive quantity',po:a?po:null,live:b?live:null};};
  const arm=previous=>{watcher?.disconnect();let timer=0;watcher=life.observe(document.body,()=>{clearTimeout(timer);timer=setTimeout(()=>{const now=page();if(now&&now!=='unknown'&&now!==previous){watcher?.disconnect();watcher=null;void run();}},150);},{childList:true,subtree:true,attributes:true,attributeFilter:['label','disabled','aria-label','data-step']});};
  const render=async(message='')=>{const p=await store.get('payload',null),choice=choose(p),root=document.createElement('div');let chooseHtml='';if(severity)chooseHtml='<section class="section"><b>Units impacted</b><div class="note warn" style="margin-top:5px">'+V3.base.esc(severity.reason)+'</div><div class="grid" style="margin-top:8px">'+(severity.po!=null?'<button class="btn" data-po><b style="font-size:20px">'+severity.po+'</b><br>PO LINE</button>':'')+(severity.live!=null?'<button class="btn" data-live><b style="font-size:20px">'+severity.live+'</b><br>LIVE INVENTORY</button>':'')+'</div><div class="row" style="margin-top:8px"><input class="input" type="number" min="0" data-manual placeholder="Manual qty"><button class="btn" data-apply>APPLY MANUAL</button></div></section>';root.innerHTML='<section class="section"><b>RIVER Assistant</b><div class="note" style="margin-top:5px">Item: '+V3.base.esc(p?.fnsku||p?.asin||'NO CAPTURE')+'</div><div class="note" style="margin-top:5px">'+V3.base.esc(message||('Current: '+(label()||page())))+'</div><div class="row" style="margin-top:8px"><button class="btn primary" data-run>RUN</button><button class="btn danger" data-clear>CLEAR</button></div></section>'+chooseHtml;panel.set(root);root.querySelector('[data-run]').onclick=run;root.querySelector('[data-clear]').onclick=async()=>{severity=null;watcher?.disconnect();watcher=null;await store.set('payload',null);render('CLEARED');};const apply=async(value,source)=>{const n=Number(value),units=field(['units impacted','number of units impacted']),ship=field(['shipments impacted','number of shipments impacted']);if(!Number.isInteger(n)||n<0)return render('Enter whole quantity 0+');if(!await setValue(units,n)||!await setValue(ship,0))return render('RIVER did not retain quantity');severity={...severity,selected:n,source};telemetry.emit('severity.choice',{value:n,source});render('Units impacted = '+n+' ('+source+'). Review RIVER, then click Next.');arm('severity');};root.querySelector('[data-po]')?.addEventListener('click',()=>apply(severity.po,'PO'));root.querySelector('[data-live]')?.addEventListener('click',()=>apply(severity.live,'LIVE'));root.querySelector('[data-apply]')?.addEventListener('click',()=>apply(root.querySelector('[data-manual]').value,'MANUAL'));};
  const run=async()=>{const p=await store.get('payload',null);if(!p)return render('No FCR capture');const pg=page();telemetry.emit('step',{page:pg,label:label()});if(['pandash','sortability','related','images','issue','create','unknown'].includes(pg))return render(pg.toUpperCase()+' stays manual — complete it then RUN/Next');if(pg==='asin'){const el=field(['type asin here','asin']);if(!await setValue(el,p.asin))return render('ASIN field not ready');nextButton()?.click();arm('asin');return;}if(pg==='information'){const pairs=[[['x0 asin','fnsku','asin/fnsku'],p.fnsku],[['purchase order','po'],p.purchaseOrder],[['vendor code / seller id','vendor code','seller id'],p.vendorCode],[['inventory cost per unit','inventory cost'],p.inventoryCost],[['physical location of the units','physical location'],p.physicalLocation],[['asin title','product title','title'],p.title]];for(const [aliases,value] of pairs){const el=field(aliases);if(!el||!await setValue(el,value||'N/A'))return render('Information field not ready: '+aliases[0]);}const next=nextButton();if(!next)return render('Information filled — review and click Next');next.click();arm('information');return;}if(pg==='severity'){const c=choose(p),ship=field(['shipments impacted','number of shipments impacted']);if(!c.value){if(ship)await setValue(ship,0);severity={...c,selected:null};return render('Choose Units impacted');}severity=null;const units=field(['units impacted','number of units impacted']);if(!await setValue(units,c.value)||!await setValue(ship,0))return render('Severity fields not ready');const next=nextButton();if(next){next.click();arm('severity');}else render('Severity filled — review and click Next');}};
  V3.ui.dockButton({id:'river',label:'RIVER',title:'V3 RIVER Assistant',onClick:()=>{render();panel.open();}});
};