import {clean} from './ui-tools.mjs';
export const AFT_MODES=Object.freeze({each:{title:'Edit • Each',instructionId:'EditItems',tool:'edititems',path:'/app/edititems',input:'EACH'},sku:{title:'Edit • SKU',instructionId:'EditItems',tool:'edititems',path:'/app/edititems',input:'SKU'},date:{title:'Edit • Date',instructionId:'EditItems',tool:'edititems',path:'/app/edititems',input:'DATELOT'},flip:{title:'Edit • FCSKU',instructionId:'FcSkuFlip',tool:'fcskuflip',path:'/app/fcskuflip',input:'SKU'},moveEach:{title:'Move • Each',instructionId:'MoveItems',tool:'moveitems',path:'/app/moveitems',input:'EACH'},moveAll:{title:'Move • Multi',instructionId:'MoveItems',tool:'moveitems',path:'/app/moveitems',input:'MULTI'},moveContainer:{title:'Move • Container',instructionId:'MoveItems',tool:'moveitems',path:'/app/moveitems',input:'CONTAINER'}});
const editSteps=[['location',/scan location|scan container|input location|enter location|enter container/i],['item',/input fnsku or fcsku|input item|scan item|enter the sku|enter item/i],['sourceState',/select source inventory state/i],['sourceDisp',/select source disposition/i],['newState',/select new inventory state/i],['newDisp',/select new disposition/i],['dateRemove',/confirm expiry date removal|remove expiry date/i],['dateEntry',/enter expiry date|enter expiration date/i],['dateConfirm',/confirm new expiry date|save expiry date/i],['confirm',/confirm change|confirm to continue/i],['success',/success items changed|items changed from|current expiry date:/i],['error',/work is errored|service failed|failed to change consumer type/i]];
export function classifyAft(text,tool){
 if(tool==='fcskuflip'){if(/success/i.test(text))return 'success';if(/confirm flip/i.test(text))return 'confirm';if(/enter new (?:fnsku|fcsku)/i.test(text))return 'new';if(/input item/i.test(text)&&/fnskus/i.test(text))return 'old';if(/scan container/i.test(text))return 'location';return 'unknown';}
 if(tool==='moveitems'){if(/verify item/i.test(text))return 'verify';if(/success|items moved|moved items/i.test(text))return 'success';if(/scan destination|destination container/i.test(text))return 'destination';if(/quantity/i.test(text))return 'quantity';if(/scan item|input item/i.test(text))return 'item';if(/scan (?:source )?container/i.test(text))return 'location';return 'unknown';}
 let found=['unknown',Infinity];for(const [state,rx]of editSteps){const m=rx.exec(text);if(m&&m.index<found[1])found=[state,m.index];}return found[0];
}
export function parseAftPage(window,html,definition){
 const doc=new window.DOMParser().parseFromString(html,'text/html');let objectId='',instructionId='';
 for(const node of doc.querySelectorAll('script[type="a-state"]')){let data;try{data=JSON.parse(node.textContent);}catch{continue;}const walk=value=>{if(!value||typeof value!=='object')return;if(value.objectId){if(objectId&&objectId!==value.objectId)throw new Error('Conflicting native workflow IDs');objectId=String(value.objectId);instructionId=value.instructionId||instructionId;}for(const v of Object.values(value))if(v&&typeof v==='object')walk(v);};walk(data);}
 if(!objectId){const source=html.replace(/&quot;|&#34;|&#x22;/gi,'"');const match=source.match(/"objectId"\s*:\s*"([^"<]+)"/);objectId=match?.[1]||'';instructionId=source.match(/"instructionId"\s*:\s*"([^"]+)"/)?.[1]||'';}
 if(!objectId||instructionId&&instructionId!==definition.instructionId)throw new Error('Exact native workflow identity unavailable');
 for(const node of doc.querySelectorAll('script,style,noscript,template,[hidden],[aria-hidden=true],.aok-hidden,.a-hidden,[style*="display:none"],[style*="display: none"],[data-tm-v4-script]'))node.remove();
 const text=clean(doc.body.textContent);return{objectId,doc,text,raw:html,state:classifyAft(text,definition.tool),selector:!!doc.querySelector('input[name=options]')};
}
export function aftSourceChoices(snapshot){
 const rows=[];for(const radio of snapshot.doc.querySelectorAll('input[type=radio]')){const label=clean([...(radio.labels||[])].map(node=>node.textContent).join(' ')||radio.closest('label')?.textContent);if(!/Owner\s*:/i.test(label)||!/Quantity\s*:/i.test(label))continue;const state=/pending research|PENDING_RESEARCH/i.test(label)?'PENDING_RESEARCH':/unsellable/i.test(label)?'UNSELLABLE':/inventory|sellable/i.test(label)?'SELLABLE':'';const qty=Number(label.match(/Quantity\s*:\s*(\d{1,7})/i)?.[1]);if(state&&Number.isInteger(qty))rows.push({state,qty,value:clean(radio.value),disabled:radio.disabled});}return rows;
}
export function aftQuantity(snapshot){if(snapshot.state==='verify')throw new Error('Native Verify Item requires manual review');const rawValues=[...(snapshot.raw||'').matchAll(/(?:"|&quot;)quantity(?:"|&quot;)\s*:\s*(?:"|&quot;)?(\d{1,7})\b/gi)].map(m=>Number(m[1]));if(rawValues.length&&new Set(rawValues).size===1&&rawValues[0]>0)return rawValues[0];const values=[...snapshot.text.matchAll(/\bQuantity\s*[:=-]?\s*(\d{1,7})\b/gi)].map(m=>Number(m[1]));const unique=[...new Set(values)];if(unique.length!==1||unique[0]<1)throw new Error('Exact native quantity unavailable/ambiguous');return unique[0];}
export function createAftClient({window,fetch=window.fetch.bind(window),onStage=()=>{}}){
 async function request(path,payload,{signal,timeout=25000}={}){const controller=new window.AbortController(),cancel=()=>controller.abort();if(signal?.aborted)cancel();signal?.addEventListener('abort',cancel,{once:true});const timer=window.setTimeout(cancel,timeout);try{const response=await fetch(path,{method:payload?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:payload?{'Content-Type':'application/json; charset=utf-8','Accept':'application/json, text/javascript, */*; q=0.01','X-Requested-With':'XMLHttpRequest'}:undefined,body:payload?JSON.stringify(payload):undefined,signal:controller.signal});const target=new window.URL(response.url||path,window.location.origin);if(response.redirected||target.origin!==window.location.origin||target.pathname!==new window.URL(path,window.location.origin).pathname)throw new Error('Native AFT redirected/auth response');const raw=await response.text();if(!response.ok)throw Object.assign(new Error('Native AFT HTTP '+response.status),{outcome:'UNKNOWN'});return raw;}finally{window.clearTimeout(timer);signal?.removeEventListener('abort',cancel);}}
 const id=(definition,objectId)=>({id:{instructionId:definition.instructionId,objectId}});
 async function page(definition,expected='',signal){const html=await request(definition.path+'?experience=Desktop',null,{signal});if(!/<html|<body|a-state/i.test(html))throw new Error('Native AFT page is not HTML');const snap=parseAftPage(window,html,definition);if(expected&&snap.objectId!==expected)throw new Error('Native AFT workflow changed');return snap;}
 async function wait(definition,objectId,{signal,complete=false,timeout=120000}={}){const deadline=Date.now()+timeout;let polls=0;while(Date.now()<deadline){const raw=await request('/status',id(definition,objectId),{signal});let data;try{data=JSON.parse(raw);}catch{throw new Error('Invalid native status JSON');}const state=String(data?.status||'').toUpperCase();onStage('status '+state);if(state==='ERRORED')throw Object.assign(new Error('Native backend ERRORED'),{outcome:'REJECTED'});if(state===(complete?'COMPLETE':'READY'))return state;if(state!=='PROCESSING')throw new Error('Unexpected native status '+state);await delay(Math.min(300,60+(++polls)*35),signal);}throw new Error('Native AFT status timeout');}
 function delay(ms,signal){return new Promise((resolve,reject)=>{if(signal?.aborted)return reject(new Error('Cancelled'));const cancel=()=>{window.clearTimeout(timer);reject(new Error('Cancelled'));};const timer=window.setTimeout(()=>{signal?.removeEventListener('abort',cancel);resolve();},ms);signal?.addEventListener('abort',cancel,{once:true});});}
 async function action(definition,objectId,action,input,options={}){onStage(action);await request('/action',{...id(definition,objectId),action,input},options);return wait(definition,objectId,options);}
 async function end(definition,objectId,signal){await request('/end',{...id(definition,objectId),tool:definition.tool},{signal});}
 async function fresh(definition,previous='',signal){const deadline=Date.now()+8000;while(Date.now()<deadline){const snap=await page(definition,'',signal);if(snap.objectId!==previous){await wait(definition,snap.objectId,{signal,timeout:8000});return snap;}await delay(100,signal);}throw new Error('Fresh native workflow unavailable');}
 return{page,wait,action,end,fresh,delay,id};
}
// Native MoveItems may hydrate Quantity only after the full page has loaded.
// The fallback is a same-origin, read-only native page with one load/DOM observer.
export function renderedAftQuantity(window,definition,expected,{signal,timeout=3500}={}){return new Promise((resolve,reject)=>{const d=window.document,frame=d.createElement('iframe');frame.dataset.tmV4Script='AFT';frame.setAttribute('aria-hidden','true');frame.tabIndex=-1;frame.style.cssText='position:fixed;left:-12000px;top:0;width:1280px;height:900px;opacity:0;pointer-events:none;border:0';let done=false,observer=null;const finish=(value,error)=>{if(done)return;done=true;observer?.disconnect();window.clearTimeout(timer);signal?.removeEventListener('abort',cancel);frame.remove();if(error)reject(error);else resolve(value);},cancel=()=>finish(null,new Error('Quantity read cancelled'));function assess(){if(done)return;try{const doc=frame.contentDocument;if(!doc?.body)return;const snap=parseAftPage(window,doc.documentElement.outerHTML,definition);if(snap.objectId!==expected)return finish(null,new Error('Rendered native workflow changed'));if(snap.state==='verify')return finish(null,new Error('Native Verify Item requires manual review'));try{finish(aftQuantity(snap));}catch{}}catch{}}const timer=window.setTimeout(()=>finish(null,new Error('Rendered native quantity unavailable')),timeout);signal?.addEventListener('abort',cancel,{once:true});frame.addEventListener('load',()=>{if(done)return;try{const doc=frame.contentDocument;if(doc?.body){observer?.disconnect();observer=new window.MutationObserver(assess);observer.observe(doc.body,{subtree:true,childList:true,characterData:true});}}catch{}assess();});const url=new window.URL(definition.path+'?experience=Desktop',window.location.origin);url.hash='tm-v4-aft-quantity';frame.src=url.href;d.documentElement.append(frame);if(signal?.aborted)cancel();});}
