import{AFT_MODES}from'./aft-client.mjs';import{parseAftRows}from'./aft-workflow.mjs';import{escapeHtml as esc,clean,upper}from'./ui-tools.mjs';
export function detectAftMode(window){const text=clean(window.document.querySelector('main,#aft-tool,#aft-tool-sub-main')?.textContent||[...window.document.body.children].filter(node=>!node.dataset.tmV4Script).map(node=>node.textContent).join(' '));if(/\/fcskuflip/.test(window.location.pathname))return 'flip';if(/\/moveitems/.test(window.location.pathname))return /Mode\s*:\s*Each/i.test(text)?'moveEach':/Mode\s*:\s*Multi/i.test(text)?'moveAll':/Mode\s*:\s*Container/i.test(text)?'moveContainer':'';return /Mode\s*:\s*Sku/i.test(text)?'sku':/Mode\s*:\s*Datelot/i.test(text)?'date':/Mode\s*:\s*Each/i.test(text)?'each':'';}
export function createAftUi({window,runner,version,onError=()=>{}}){
 const d=window.document,mode=detectAftMode(window),events=new window.AbortController();let minimized=false;
 const root=d.createElement('section');root.id='tm-v4-aft';root.dataset.tmV4Script='AFT';const control=d.createElement('aside');control.id='tm-v4-aft-control';control.dataset.tmV4Script='AFT';
 const style=d.createElement('style');style.dataset.tmV4Style='AFT';style.textContent=`#tm-v4-aft{position:fixed;top:125px;left:15px;width:368px;max-height:calc(100vh - 145px);overflow:auto;z-index:999990;background:#eff7fb;border:2px solid #52758e;border-radius:6px;box-shadow:0 2px 6px #0003;color:#152a3c;font:12px Arial}#tm-v4-aft[data-mode^=move]{width:318px}#tm-v4-aft[data-mode=flip]{top:86px;left:10px;width:320px}#tm-v4-aft[data-mode=date]{top:auto;left:auto;right:14px;bottom:14px;width:420px}#tm-v4-aft header{display:flex;align-items:center;justify-content:space-between;background:#294f6b;color:white;padding:7px;font-weight:bold}#tm-v4-aft[data-mode^=move] header{background:#256845}#tm-v4-aft .body{padding:9px}#tm-v4-aft input,#tm-v4-aft textarea,#tm-v4-aft select{box-sizing:border-box;max-width:100%;border:1px solid #9caec0;border-radius:4px;padding:5px;background:white;color:#152a3c}#tm-v4-aft input:not([type=checkbox]),#tm-v4-aft textarea{width:100%}#tm-v4-aft textarea{height:120px;resize:vertical;font:12px monospace}#tm-v4-aft button,#tm-v4-aft-control button{padding:6px;border:1px solid #8ba0af;border-radius:4px;cursor:pointer;font-weight:700;background:#ddeaf2;color:#173b56}#tm-v4-aft button:disabled,#tm-v4-aft-control button:disabled{opacity:.45;cursor:default}#tm-v4-aft .grid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:7px 0}#tm-v4-aft [data-run]{background:#247045;color:white}#tm-v4-aft [data-stop]{background:#a33d2c;color:white}#tm-v4-aft .rows{max-height:170px;overflow:auto;margin-top:7px;font:11px monospace;white-space:pre-wrap;overflow-wrap:anywhere}#tm-v4-aft [data-state=UNKNOWN],#tm-v4-aft [data-state=SUBMITTED]{background:#fff2be}#tm-v4-aft [data-state=REJECTED]{background:#ffe2de}#tm-v4-aft [data-state=CONFIRMED]{background:#d9f5df}#tm-v4-aft-control{position:fixed;top:76px;right:10px;width:278px;padding:8px;z-index:999991;border:1px solid #7593a9;border-radius:7px;background:#f5fafc;color:#234154;font:12px Arial}#tm-v4-aft-control .modes{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin:7px 0}#tm-v4-aft-control [data-current=true]{outline:2px solid #1d6fa8}#tm-v4-aft .choices{display:flex;gap:4px;flex-wrap:wrap}#tm-v4-aft .choices button{flex:1;font-size:11px}#tm-v4-aft .choices [data-selected=true]{background:#176c96;color:white}#tm-v4-aft .date-row{display:grid;grid-template-columns:1.25fr 1fr;gap:6px;margin:6px 0}#tm-v4-aft .date-head{font-weight:bold;padding:7px 0}#tm-v4-aft label{display:block;margin:6px 0}#tm-v4-aft .qty{display:flex;gap:8px;font-weight:bold}`;
 root.dataset.mode=mode;root.innerHTML=`<header><span>AFT V4 ${esc(version)} • ${esc(AFT_MODES[mode]?.title||'Select native mode')}</span><button data-min>−</button></header><div class="body"><div role="status">Ready • native mode required</div><div class="entry"></div><div class="grid"><button data-run>RUN</button><button data-stop>STOP AFTER CURRENT ITEM</button></div><button data-clear>CLEAR</button><div class="rows"></div></div>`;
 control.innerHTML=`<b>AFT CONTROL</b><div class="modes">${Object.entries(AFT_MODES).map(([key,def])=>`<button data-mode="${key}" data-current="${mode===key}">${esc(def.title)}</button>`).join('')}</div><label><input type="checkbox" data-enable checked> ${mode.startsWith('move')?'MoveItems':'EditItems'} helper</label>${mode==='sku'?'<label><input type="checkbox" data-batch> SKU batch queue</label>':''}<div data-mode-status>Native workflow modes</div>`;
 const stateOptions=['INVENTORY','PENDING_RESEARCH','UNSELLABLE'],damageOptions=['AMAZON_DAMAGE','DEFECTIVE','DISTRIBUTOR_DAMAGE','EXPIRED'],select=(name,options)=>`<select data-field="${name}">${options.map(value=>`<option>${value}</option>`).join('')}</select>`;
 const stateFields=source=>`${source?'<label>Current state '+select('currentState',stateOptions)+'</label><label>Current disposition '+select('currentDamage',damageOptions)+'</label>':''}<label>New state ${select('desiredState',stateOptions)}</label><label>New disposition ${select('desiredDamage',damageOptions)}</label>`;
 let content='';if(mode==='each')content=`<label>TOTE ASIN [FNSKU]<textarea data-field="text" placeholder="tsX… B0… X0…"></textarea></label>${stateFields(false)}`;
 if(mode==='sku')content=`<div class="qty"><span data-qty="SELLABLE">S: —</span><span data-qty="PENDING_RESEARCH">P: —</span><span data-qty="UNSELLABLE">U: —</span></div><label data-single>SKU / ASIN / FNSKU / FCSKU<input data-field="code"></label><label data-batch-wrap hidden>One SKU per line<textarea data-field="text"></textarea></label>${stateFields(true)}`;
 if(mode==='date')content='<label>Tote<input data-field="location"></label><div class="date-head">ASIN / FNSKU / UPC / EAN • Desired date</div><div data-date-rows></div><button data-add-row>+ ADD ROW</button>';
 if(mode==='flip')content='<label>OLD FCSKU<input data-field="old"></label><label>NEW FCSKU<input data-field="newCode"></label><label>LOCATIONS / CONTAINERS<textarea data-field="text"></textarea></label>';
 if(mode.startsWith('move'))content=`<label>SOURCE<input data-field="source"></label><label>DESTINATION<input data-field="destination"></label>${mode==='moveAll'?'<div class="grid"><label>Quantity<select data-field="quantityMode"><option value="all">ALL</option><option value="user">USER QTY</option></select></label><label>QTY<input type="number" min="1" step="1" data-field="quantity" value="1"></label></div>':''}<label>ITEM BARCODES<textarea data-field="text"></textarea></label>${mode==='moveContainer'?'<p>Container mode uses the native form. V4 observes no container transfer proof here; helper Run is disabled.</p>':''}`;
 root.querySelector('.entry').innerHTML=content;function addDateRow(code='',date=''){const row=d.createElement('div');row.className='date-row';row.innerHTML='<input data-date-code autocomplete="off" placeholder="ASIN / FNSKU / UPC / EAN"><input data-date-value type="date">';row.querySelector('[data-date-code]').value=code;row.querySelector('[data-date-value]').value=date;root.querySelector('[data-date-rows]').append(row);return row;}if(mode==='date')for(let i=0;i<4;i++)addDateRow();const draftKey='tm-v4.aft.draft.'+mode;try{const saved=JSON.parse(window.localStorage.getItem(draftKey)||'{}');for(const node of root.querySelectorAll('[data-field]'))if(saved[node.dataset.field]!=null)node.value=saved[node.dataset.field];minimized=saved.minimized===true;if(mode==='date'&&Array.isArray(saved.dateRows)){root.querySelector('[data-date-rows]').replaceChildren();for(const row of saved.dateRows)addDateRow(row.code,row.date);if(!saved.dateRows.length)for(let i=0;i<4;i++)addDateRow();}}catch{}
 const message=text=>root.querySelector('[role=status]').textContent=text;
 function save(){const data={minimized};if(mode==='date')data.dateRows=[...root.querySelectorAll('.date-row')].map(row=>({code:row.querySelector('[data-date-code]').value,date:row.querySelector('[data-date-value]').value}));for(const node of root.querySelectorAll('[data-field]'))data[node.dataset.field]=node.value;window.localStorage.setItem(draftKey,JSON.stringify(data));}
 function drawChoices(){if(!['each','sku'].includes(mode))return;const current=root.querySelector('[data-field=currentState]'),desired=root.querySelector('[data-field=desiredState]'),sourceDamage=root.querySelector('[data-field=currentDamage]'),targetDamage=root.querySelector('[data-field=desiredDamage]');if(current){for(const option of desired.options)option.disabled=current.value!=='UNSELLABLE'&&option.value===current.value;if(desired.selectedOptions[0]?.disabled)desired.value=[...desired.options].find(option=>!option.disabled).value;}for(const option of targetDamage.options)option.disabled=current?.value==='UNSELLABLE'&&desired.value==='UNSELLABLE'&&option.value===sourceDamage.value;if(targetDamage.selectedOptions[0]?.disabled)targetDamage.value=[...targetDamage.options].find(option=>!option.disabled).value;for(const name of['currentDamage','desiredDamage']){const field=root.querySelector('[data-field='+name+']');if(field)field.closest('label').hidden=(name==='currentDamage'?current?.value:desired.value)!=='UNSELLABLE';}for(const button of root.querySelectorAll('[data-choice]')){const field=root.querySelector('[data-field='+button.dataset.choice+']'),option=[...field.options].find(option=>option.value===button.dataset.value);button.disabled=runner.busy||option?.disabled;button.dataset.selected=String(field.value===button.dataset.value);button.setAttribute('aria-pressed',String(field.value===button.dataset.value));}}
 function paint(text,rows=runner.rows){if(text)message(text);root.querySelector('.body').hidden=minimized;drawChoices();root.querySelector('[data-min]').textContent=minimized?'+':'−';root.querySelector('[data-run]').disabled=runner.busy||!mode||mode==='moveContainer';root.querySelectorAll('[data-field]').forEach(node=>node.disabled=runner.busy);control.querySelectorAll('[data-mode]').forEach(node=>node.disabled=runner.busy);root.querySelector('.rows').innerHTML=rows.map(row=>`<div data-state="${esc(row.state)}">${esc(row.code||row.container)} • ${esc(row.state)}<br>${esc(row.message)}</div>`).join('');}
 async function run(){try{const meta={};for(const node of root.querySelectorAll('[data-field]'))meta[node.dataset.field]=clean(node.value);const batch=control.querySelector('[data-batch]')?.checked;const text=mode==='date'?[...root.querySelectorAll('.date-row')].map(row=>({code:clean(row.querySelector('[data-date-code]').value),date:row.querySelector('[data-date-value]').value})).filter(row=>row.code||row.date).map(row=>row.code+' '+row.date).join('\n'):mode==='sku'&&!batch?meta.code:root.querySelector('[data-field=text]')?.value||'';save();const task=runner.run(parseAftRows(mode,text,meta));paint();await task;paint();if(runner.rows.length&&runner.rows.every(row=>['CONFIRMED','REJECTED'].includes(row.state))&&mode.startsWith('move')){for(const node of root.querySelectorAll('[data-field=source],[data-field=destination],[data-field=text]'))node.value='';save();root.querySelector('[data-field=source]').focus();}}catch(error){message(error.message);onError(error);}}
 root.addEventListener('input',event=>{if(mode==='date'&&event.target.matches('[data-date-code]')&&event.target.value&&event.target.closest('.date-row')===root.querySelector('[data-date-rows]').lastElementChild)addDateRow();save();},{signal:events.signal});root.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;if(target.hasAttribute('data-add-row'))addDateRow().querySelector('input').focus();if(target.hasAttribute('data-choice')){const field=root.querySelector('[data-field="'+target.dataset.choice+'"]');field.value=target.dataset.value;field.dispatchEvent(new window.Event('change',{bubbles:true}));save();drawChoices();}if(target.hasAttribute('data-run'))void run();if(target.hasAttribute('data-stop')){runner.stop();}if(target.hasAttribute('data-clear')){void runner.clear().then(()=>{for(const node of root.querySelectorAll('input:not([type=number]),textarea'))node.value='';save();paint();}).catch(error=>message(error.message));}if(target.hasAttribute('data-min')){minimized=!minimized;save();paint();}},{signal:events.signal});
 control.addEventListener('click',event=>{const key=event.target.closest('[data-mode]')?.dataset.mode;if(key)void runner.switchMode(key).catch(error=>{control.querySelector('[data-mode-status]').textContent=error.message;});},{signal:events.signal});control.addEventListener('change',event=>{if(event.target.matches('[data-enable]'))root.hidden=!event.target.checked;if(event.target.matches('[data-batch]')){root.querySelector('[data-single]').hidden=event.target.checked;root.querySelector('[data-batch-wrap]').hidden=!event.target.checked;}},{signal:events.signal});
 d.addEventListener('keydown',event=>{
  if(!root.contains(event.target)||event.key!=='Enter'||event.shiftKey)return;const field=event.target;
  if(field.matches('[data-field=source],[data-field=old]')){event.preventDefault();root.querySelector(mode==='flip'?'[data-field=newCode]':'[data-field=destination]')?.focus();}
  else if(field.matches('[data-field=destination],[data-field=newCode],[data-field=location]')){event.preventDefault();root.querySelector('[data-field=text]')?.focus();}
  else if(field.tagName==='TEXTAREA'){
   const pos=field.selectionStart??field.value.length,start=field.value.lastIndexOf('\n',Math.max(0,pos-1))+1,next=field.value.indexOf('\n',pos),end=next<0?field.value.length:next,code=clean(field.value.slice(start,end)),destination=root.querySelector('[data-field=destination]')?.value,source=root.querySelector('[data-field=source]')?.value,isStart=upper(code)==='123START',container=mode.startsWith('move')&&/^(?:ts|cs)x[A-Za-z0-9_-]+$/i.test(code);
   event.preventDefault();
   if(isStart||container){field.value=field.value.slice(0,start)+field.value.slice(end).replace(/^\r?\n/,'');field.setSelectionRange(field.value.length,field.value.length);save();if(runner.busy&&upper(code)===upper(source))runner.stop();else if(isStart||upper(code)===upper(destination))void run();else message('Container scan is a control — not an item');}
   else{const before=field.value.slice(0,pos).replace(/[\t ]+$/,''),after=field.value.slice(field.selectionEnd??pos).replace(/^\r?\n+/,'');field.value=before+'\n'+after;field.setSelectionRange(before.length+1,before.length+1);save();}
  }else if(mode==='sku'&&field.matches('[data-field=code]')){event.preventDefault();void run();}
  event.stopImmediatePropagation();
 },{capture:true,signal:events.signal});
 if(['each','sku'].includes(mode)){const labels={INVENTORY:'Sellable',PENDING_RESEARCH:'Pending',UNSELLABLE:'Unsellable',AMAZON_DAMAGE:'Amazon Damage',DEFECTIVE:'Defective',DISTRIBUTOR_DAMAGE:'Distributor Damage',EXPIRED:'Expired'};for(const select of root.querySelectorAll('.entry select[data-field]')){select.hidden=true;const group=d.createElement('span');group.className='choices';for(const option of select.options){const button=d.createElement('button');button.type='button';button.dataset.choice=select.dataset.field;button.dataset.value=option.value;button.textContent=labels[option.value]||option.value;group.append(button);}select.after(group);}const saved=window.localStorage.getItem(draftKey);if(!saved){root.querySelector('[data-field=desiredState]').value='UNSELLABLE';root.querySelector('[data-field=desiredDamage]').value=mode==='sku'?'DEFECTIVE':'AMAZON_DAMAGE';if(mode==='sku')root.querySelector('[data-field=currentDamage]').value='DEFECTIVE';}root.addEventListener('change',()=>{drawChoices();save();},{signal:events.signal});}d.body.append(style,root,control);paint();return{root,control,paint,inventory:choices=>{for(const state of stateOptions){const node=root.querySelector(`[data-qty="${state==='INVENTORY'?'SELLABLE':state}"]`);if(node){const matches=choices.filter(row=>row.state===(state==='INVENTORY'?'SELLABLE':state));node.textContent=(state==='INVENTORY'?'S':state==='PENDING_RESEARCH'?'P':'U')+': '+(matches.length===1?matches[0].qty:'—');}}},dispose(){events.abort();root.remove();control.remove();style.remove();}};
}
