import {clean,upper,escapeHtml as esc,printBarcode}from'./ui-tools.mjs';
export function snapshotInventory(window,page=window){
 const table=window.document.getElementById('table-inventory');if(!table)throw new Error('Inventory table not ready');
 const names=[...table.querySelectorAll('thead th')].map(node=>clean(node.id||node.textContent).toLowerCase().replace(/^inventory-/,'').replace(/\([\d,]+\)/g,'').replaceAll('-',' ').trim());
 const index=field=>names.indexOf(field);if(index('container')<0||index('quantity')<0)throw new Error('Native Container/Quantity columns missing');
 let nodes,source='visible DOM only';const jq=page.jQuery||page.$;
 // Native FCR 1.9.x also names its legacy wrapper DataTable; inspect the returned API.
 try{const plugin=jq?.fn?.dataTable,isDataTable=plugin?.isDataTable||plugin?.fnIsDataTable;if(typeof isDataTable==='function'&&isDataTable.call(plugin,table)){const native=jq(table),modern=typeof native.DataTable==='function'?native.DataTable():null;if(typeof modern?.rows==='function'){nodes=modern.rows({search:'applied'}).nodes().toArray();}else if(typeof native.dataTable==='function'){const settings=native.dataTable().fnSettings();nodes=settings.aiDisplay.map(i=>settings.aoData[i]?.nTr);}if(nodes){if(nodes.some(node=>!node))throw new Error('Native filtered rows not rendered');source='DataTables applied filter';}}}catch{nodes=null;}
 if(!nodes)nodes=[...(table.tBodies[0]?.rows||[])].filter(row=>!row.hidden&&row.getAttribute('aria-hidden')!=='true'&&row.style.display!=='none'&&!row.classList.contains('filtered-out')&&window.getComputedStyle(row).display!=='none');
 const rows=[];for(const node of nodes){if(!node||node.querySelector('.dataTables_empty'))continue;const field=name=>clean(node.cells[index(name)]?.textContent);const container=field('container'),pod=container.match(/\bP-\d-(?:[A-Z]\d{3}){2}\b/i)?.[0];if(!pod)continue;const raw=field('quantity').replaceAll(',','');if(!/^\d+$/.test(raw)||!Number.isSafeInteger(Number(raw)))throw new Error('Snapshot quantity is invalid');rows.push({container,pod:upper(pod),qty:Number(raw),fnsku:field('fnsku'),fcsku:field('fcsku'),title:field('title'),floor:null,error:''});}
 return{rows,source};
}
export function parseFloor(window,html){
 const d=new window.DOMParser().parseFromString(html,'text/html');if(d.querySelector('input[type=password],form[action*=login],form[action*=signin]'))throw new Error('Hierarchy authentication required');
 const values=[];for(const row of d.querySelectorAll('table tr')){const label=clean(row.querySelector('th')?.textContent||row.cells[0]?.textContent).toLowerCase();if(/^(?:floor|floor number|level|location level)$/.test(label))values.push(clean(row.cells[1]?.textContent));}
 if(!values.length){const cell=d.querySelector('div.a-span6:nth-child(1) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2)');if(cell)values.push(clean(cell.textContent).split(',')[0]);}
 const floors=values.map(value=>value.match(/^(?:P\s*)?([1-4])(?:\b|$)/i)?.[1]).filter(Boolean);if(new Set(floors).size>1)throw new Error('Hierarchy contains conflicting floors');if(!floors.length)throw new Error('Native floor field not returned');return Number(floors[0]);
}
export function createBinOverlay({window,page=window,reader,version,onEvidence=()=>{},fetch=window.fetch?.bind(window)}){
 const d=window.document,controller=new window.AbortController(),cache=new Map();let run=null,observer=null,disposed=false,button=null;
 const style=d.createElement('style');style.dataset.tmV4Style='BINC';style.textContent=`#tm-v4-bin{position:fixed;right:14px;bottom:14px;width:660px;max-width:calc(100vw - 28px);max-height:78vh;z-index:999999;background:#fff;border:2px solid #111827;border-radius:10px;box-shadow:0 10px 30px #0005;font:12px Arial,sans-serif;color:#111827;overflow:hidden}#tm-v4-bin[hidden]{display:none}#tm-v4-bin header{display:flex;align-items:center;gap:8px;background:#111827;color:#fff;padding:8px 10px;font-weight:800}#tm-v4-bin header span{flex:1}#tm-v4-bin .body{padding:9px;overflow:auto;max-height:calc(78vh - 46px)}#tm-v4-bin .controls{display:flex;flex-wrap:wrap;gap:4px;margin-bottom:8px}#tm-v4-bin button{cursor:pointer;border:1px solid #374151;border-radius:6px;padding:5px 8px;font-size:12px;font-weight:800;background:#f3f4f6;color:#111827}#tm-v4-bin button[data-active=true]{outline:2px solid #111827}#tm-v4-bin table{width:100%;border-collapse:collapse}#tm-v4-bin th,#tm-v4-bin td{border-bottom:1px solid #e5e7eb;padding:6px 5px;text-align:left;white-space:nowrap}#tm-v4-bin [data-floor]{border-radius:7px;padding:3px 7px;font-weight:900}#tm-v4-bin [data-floor="1"]{background:#f0e442}#tm-v4-bin [data-floor="2"]{background:#009e73;color:white}#tm-v4-bin [data-floor="3"]{background:#e69f00}#tm-v4-bin [data-floor="4"]{background:#0072b2;color:white}#tm-v4-bin [data-floor="?"]{background:#cbd5e1}#tm-v4-bin a{color:#005eb8;font-weight:800}`;
 const root=d.createElement('section');root.id='tm-v4-bin';root.dataset.tmV4Script='BINC';root.hidden=true;
 root.innerHTML=`<header><b>Overlay v${esc(version)}</b><span role="status"></span><button data-action="pause">Pause</button><button data-action="hide">Hide</button></header><div class="body"><div class="controls">${['ALL','P2','P3','P4','P1'].map(floor=>`<button data-filter="${floor}">${floor==='ALL'?'All':floor}</button>`).join('')}<button data-sort="FLOOR">Floor</button><button data-sort="DESC">Qty ↓</button><button data-sort="ASC">Qty ↑</button><button data-action="lazy">Lazy bin check</button><button data-action="copy">Copy visible TSV</button></div><p data-source></p><table><thead><tr><th>Floor</th><th>Container</th><th>Qty</th><th>FNSKU</th><th>FcSku</th></tr></thead><tbody></tbody></table></div>`;
 const status=text=>{root.querySelector('[role=status]').textContent=text;};
 function visible(){if(!run)return[];return run.rows.filter(row=>run.filter==='ALL'||'P'+row.floor===run.filter).sort((a,b)=>(run.sort==='ASC'?a.qty-b.qty:run.sort==='DESC'?b.qty-a.qty:0)||(a.floor??99)-(b.floor??99)||a.container.localeCompare(b.container));}
 function render(){if(!run||disposed)return;root.querySelectorAll('[data-filter]').forEach(node=>node.dataset.active=String(node.dataset.filter===run.filter));root.querySelectorAll('[data-sort]').forEach(node=>node.dataset.active=String(node.dataset.sort===run.sort));root.querySelector('[data-action=pause]').textContent=run.paused?'Resume':'Pause';root.querySelector('[data-source]').textContent=`${run.source} • ${run.rows.length} P-level rows • snapshot at click`;root.querySelector('tbody').innerHTML=visible().map((row,i)=>{const url=new window.URL(window.location.href);url.search='';url.hash='';url.searchParams.set('s',row.container);return`<tr><td><span data-floor="${row.floor??'?'}" title="${esc(row.error)}">P${row.floor??'-'}</span></td><td><a href="${esc(url.href)}" target="_blank" rel="noopener" data-print="${esc(row.container)}" data-title="">${esc(row.container)}</a></td><td>${row.qty}</td><td><span data-print="${esc(row.fnsku)}" data-title="${esc(row.title)}" tabindex="0">${esc(row.fnsku)}</span></td><td>${esc(row.fcsku)}</td></tr>`;}).join('');status(`${run.finished}/${run.pods.length} floors • ${run.paused?'PAUSED':run.finished===run.pods.length?'ready':'loading'}${run.errors?' • '+run.errors+' unknown':''}`);}
 function pump(s){if(disposed||s!==run||s.paused||s.controller.signal.aborted)return;while(s.active<4&&s.pending.length){const pod=s.pending.shift();s.active++;let cached=cache.get(pod);if(cached&&Date.now()-cached.at>1800000)cached=null;Promise.resolve().then(()=>cached?{html:null,floor:cached.floor}:reader.section('container-hierarchy',pod,{signal:s.controller.signal})).then(result=>{if(s!==run)return;const floor=result.floor??parseFloor(window,result.html);cache.set(pod,{floor,at:Date.now()});s.rows.filter(row=>row.pod===pod).forEach(row=>row.floor=floor);},error=>{if(s!==run||s.controller.signal.aborted)return;s.errors++;s.rows.filter(row=>row.pod===pod).forEach(row=>row.error=error.message);}).catch(error=>{if(s!==run)return;s.errors++;s.rows.filter(row=>row.pod===pod).forEach(row=>row.error=error.message);}).finally(()=>{if(s!==run)return;s.active--;s.finished++;render();pump(s);});}}
 function open(){if(disposed)return;run?.controller.abort();root.hidden=false;try{const snap=snapshotInventory(window,page);const pods=[...new Set(snap.rows.map(row=>row.pod))];run={...snap,pods,pending:pods.slice(),active:0,finished:0,errors:0,filter:'ALL',sort:'FLOOR',paused:false,controller:new window.AbortController()};render();pump(run);onEvidence({type:'bin.snapshot',intent:'read',data:{rows:snap.rows.length,pods:pods.length,source:snap.source}});}catch(error){run=null;root.querySelector('tbody').replaceChildren();status(error.message);}}
 async function copy(lazy){if(!run)return;if(lazy&&run.finished<run.pods.length){status('Wait for floor scan');return;}let text;if(lazy){const groups=new Map();for(const row of run.rows){const code=row.fnsku||row.fcsku;if(!code)continue;if(!groups.has(code))groups.set(code,[]);groups.get(code).push(row);}text=[...groups].map(([code,rows])=>[code,...[2,3,4].map(floor=>rows.filter(row=>row.floor===floor).sort((a,b)=>b.qty-a.qty||a.container.localeCompare(b.container))[0]?.container||'')].join('\t')).join('\n');}else text=['Floor\tContainer\tQty\tFNSKU\tFcSku',...visible().map(row=>['P'+(row.floor??'-'),row.container,row.qty,row.fnsku,row.fcsku].map(value=>clean(value).replaceAll('\t',' ')).join('\t'))].join('\n');try{await window.navigator.clipboard.writeText(text);status('COPIED ✓');}catch{status('COPY FAILED');}}
 root.addEventListener('click',event=>{const target=event.target.closest('button,[data-print]');if(!target)return;if(event.altKey&&target.dataset.print){event.preventDefault();event.stopPropagation();if(!/^(?:P-\d-(?:[A-Z]\d{3}){2}|[A-Z0-9]{10})$/i.test(target.dataset.print))return;void printBarcode(window,fetch,target.dataset.print,target.dataset.title,'BINC',version).then(status,error=>status(error.message));return;}if(!run)return;if(target.dataset.filter)run.filter=target.dataset.filter;if(target.dataset.sort)run.sort=target.dataset.sort;if(target.dataset.action==='pause'){run.paused=!run.paused;if(!run.paused)pump(run);}if(target.dataset.action==='hide')root.hidden=true;if(target.dataset.action==='copy')void copy(false);if(target.dataset.action==='lazy')void copy(true);render();},{signal:controller.signal});
 function mount(){if(disposed)return;const nav=d.getElementById('inventory-nav')||d.getElementById('inventory-status');if(!nav)return;if(!button){button=d.createElement('button');button.type='button';button.dataset.tmV4Script='BINC';button.textContent='P-level overlay sorter';button.style.cssText='background:orange;color:#111;font-weight:bold;border-radius:6px;margin-left:8px;padding:4px 10px;cursor:pointer';button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();open();},{signal:controller.signal});}if(!button.isConnected)(nav.tagName==='A'?nav.parentElement:nav).append(button);}
 function ready(){if(!d.head||!d.body)return;d.head.append(style);d.body.append(root);mount();const nav=d.getElementById('inventory-status')||d.querySelector('[data-section-type="inventory"]');if(nav){observer=new window.MutationObserver(mount);observer.observe(nav,{childList:true,subtree:true});}}
 if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',ready,{once:true,signal:controller.signal});else ready();
 return{open,root,visible,getState:()=>run,dispose(){disposed=true;run?.controller.abort();controller.abort();observer?.disconnect();button?.remove();root.remove();style.remove();}};
}
