import{escapeHtml as esc,clean}from'./ui-tools.mjs';
export function localDate(month,day,year){const date=new Date(year,month-1,day);return date.getFullYear()===year&&date.getMonth()===month-1&&date.getDate()===day?date.getTime():null;}
export function chosenExpiration(ctx,entered,{native=false,now=Date.now()}={}){const today=new Date(now);today.setHours(0,0,0,0);if(!Number.isFinite(entered))throw new Error('Invalid date');if(ctx.dateType==='PRODUCTION_DATE'){if(entered>today.getTime())throw new Error('Production date must be today or earlier');if(native)return entered;const shelf=Number(ctx.dateDetail?.shelfLife);if(!Number.isFinite(shelf)||shelf<0||ctx.dateDetail?.shelfLife===null||ctx.dateDetail?.shelfLife===undefined)throw new Error('Native shelf life missing — no guessed expiration');const expires=entered+shelf;return expires;}if(entered<today.getTime())throw new Error('Expiration must be today or later');return entered;}
export function paoExpiration(now=new Date()){const date=new Date(now);date.setHours(0,0,0,0);date.setDate(date.getDate()+900);return date.getTime();}
export function createDatePicker(window,{owner='SIDE'}={}){
 let cancelCurrent=()=>{};
 const pick=({code,ctx,signal,native=false})=>new Promise(resolve=>{
  const existing=window.document.getElementById('tm-v4-date-picker');existing?.dispatchEvent(new window.Event('tm-v4-date:replace'));cancelCurrent();const d=window.document,root=d.createElement('div'),style=d.createElement('style');root.id='tm-v4-date-picker';root.dataset.tmV4Script=owner;style.dataset.tmV4Script=owner;
  style.textContent=`#tm-v4-date-picker{position:fixed;inset:0;z-index:2147483647;display:flex;align-items:center;justify-content:center;background:#0008;font:14px Arial;color:#172033}#tm-v4-date-picker .wrap{max-width:1100px;width:96vw;padding:12px;background:#f8fafc;border:2px solid #334155;border-radius:8px}#tm-v4-date-picker .preview{display:flex;gap:12px;align-items:center;padding:8px;background:white;margin-bottom:10px}#tm-v4-date-picker img{width:90px;max-height:105px;object-fit:contain}#tm-v4-date-picker .panels{display:grid;grid-template-columns:1fr 2fr 1.5fr;gap:10px}#tm-v4-date-picker section{border:1px solid #94a3b8;border-radius:5px;overflow:hidden}#tm-v4-date-picker h3{margin:0;background:#e2e8f0;padding:8px;display:flex;justify-content:space-between}#tm-v4-date-picker .grid{display:grid;gap:5px;padding:7px;grid-template-columns:repeat(4,1fr)}#tm-v4-date-picker .days{grid-template-columns:repeat(7,1fr)}#tm-v4-date-picker button{padding:9px;border:1px solid #94a3b8;border-radius:4px;background:white;font-weight:800;cursor:pointer}#tm-v4-date-picker button.selected{background:#146eb4;color:white}#tm-v4-date-picker button:disabled{opacity:.35;cursor:default}#tm-v4-date-picker footer{display:flex;gap:10px;margin-top:10px}#tm-v4-date-picker [data-error]{color:#b91c1c;font-weight:bold}`;
  d.head.append(style);d.body.append(root);let month=null,day=1,year=null,done=false;
  const production=ctx.dateType==='PRODUCTION_DATE',today=new Date();today.setHours(0,0,0,0);
  function finish(value){if(done)return;done=true;signal?.removeEventListener('abort',abort);root.remove();style.remove();cancelCurrent=()=>{};resolve(value);}
  const abort=()=>finish(null);cancelCurrent=abort;root.addEventListener('tm-v4-date:replace',abort,{once:true});signal?.addEventListener('abort',abort,{once:true});
  const months=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];
  function permitted(m,d,y){const entered=localDate(m,d,y);if(entered===null)return false;try{chosenExpiration(ctx,entered,{native});return true;}catch{return false;}}
  function render(error=''){const image=clean(ctx.sku?.imageUrl||ctx.sku?.img||ctx.sku?.image);const safeImage=/^https?:\/\//i.test(image)?image:'';root.innerHTML=`<div class="wrap"><b>${esc(ctx.asin||'')} / ${esc(ctx.fnsku||code)} • REQUIRES ${production?'PRODUCTION':'EXPIRATION'} DATE</b><div class="preview">${safeImage?`<img src="${esc(safeImage)}" alt="">`:''}<section><strong>${esc(ctx.sku?.title||ctx.sku?.normalizedTitle||'Item title unavailable')}</strong><div>SCAN: ${esc(code)}</div></section></div><div class="panels"><section><h3>MONTH <b>${month?months[month-1]:'—'}</b></h3><div class="grid">${months.map((m,i)=>`<button data-month="${i+1}" class="${month===i+1?'selected':''}">${m}</button>`).join('')}</div></section><section><h3>DAY <b>${day}</b></h3><div class="grid days">${Array.from({length:31},(_,i)=>i+1).map(v=>`<button data-day="${v}" class="${day===v?'selected':''}" ${!month||v>new Date(2000,month,0).getDate()?'disabled':''}>${v}</button>`).join('')}</div></section><section><h3>YEAR <b>${year||'—'}</b></h3><div class="grid">${Array.from({length:16},(_,i)=>today.getFullYear()+(production?-i:i)).map(v=>`<button data-year="${v}" class="${year===v?'selected':''}" ${!month||!permitted(month,day,v)?'disabled':''}>${v}</button>`).join('')}</div></section></div><footer>${production?`<button data-apply ${year?'':'disabled'}>USE PRODUCTION DATE</button>`:'<button data-pao>PAO +900 DAYS</button>'}<button data-cancel>↩ RETURN TO SOURCE / CANCEL</button><span data-error>${esc(error)}</span></footer></div>`;}
  root.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.month){month=Number(b.dataset.month);day=1;year=null;render();return;}if(b.dataset.day){day=Number(b.dataset.day);year=null;render();return;}if(b.dataset.year){year=Number(b.dataset.year);if(production){render();return;}}else if(b.hasAttribute('data-pao')){finish(paoExpiration(today));return;}else if(b.hasAttribute('data-cancel')){finish(null);return;}else if(!b.hasAttribute('data-apply'))return;
   try{finish(chosenExpiration(ctx,localDate(month,day,year),{native}));}catch(error){render(error.message);}
  });render();if(signal?.aborted)abort();
 });return{pick,dispose:()=>cancelCurrent()};
}
