import{clean,upper,escapeHtml as esc}from'./ui-tools.mjs';import{DROPZONES,dropzone}from'./move-container.mjs';import{createOperationJournal,withOperationLock}from'./operation-journal.mjs';import{normalizeHierarchyContainer}from'./hierarchy-runtime.mjs';
export function createDropzoneQueue({window,move,identity,version,onEvidence=()=>{},onPause=()=>{},storage=window.localStorage}){
 const d=window.document,key='tm-v4.drop.rows',prefKey='tm-v4.drop.preferences',listeners=new window.AbortController();let journal,owner=false,running=false,processing=false,nativeBusy=false,disposed=false,currentRow=null,controller=null,runPromise=null,observer=null,lastStep=false;
 let prefs={floor:'',type:'PRIME',enabled:true,inputEnabled:true};try{Object.assign(prefs,JSON.parse(storage.getItem(prefKey)||'{}'));}catch{}
 const uuid=()=>window.crypto.randomUUID?.()||[...window.crypto.getRandomValues(new Uint32Array(4))].join('-');
 const load=()=>journal=createOperationJournal({storage,key,normalize:normalizeHierarchyContainer,uuid});
 const root=d.createElement('aside');root.id='tm-v4-drop';root.dataset.tmV4Script='DROP';
 const style=d.createElement('style');style.dataset.tmV4Style='DROP';style.textContent=`#tm-v4-drop{position:fixed;right:10px;bottom:10px;z-index:999999;width:360px;max-width:calc(100vw - 20px);background:rgba(28,28,28,.94);color:white;border:1px solid #ffffff38;border-radius:10px;box-shadow:0 3px 14px #0005;padding:9px;font:12px Arial,sans-serif;box-sizing:border-box}#tm-v4-drop[hidden]{display:none}#tm-v4-drop header{display:flex;justify-content:space-between;align-items:center;margin-bottom:7px}#tm-v4-drop button{cursor:pointer;border:1px solid #64748b;border-radius:5px;padding:5px;color:white;background:#435a77;font-weight:bold}#tm-v4-drop button:disabled{opacity:.5;cursor:default}#tm-v4-drop [data-selected=true]{outline:2px solid #fff}#tm-v4-drop .grid{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin:7px 0}#tm-v4-drop .drops{grid-template-columns:repeat(3,1fr)}#tm-v4-drop textarea{width:100%;box-sizing:border-box;height:65px;background:#101010;color:white;border:1px solid #666;border-radius:6px;padding:6px;font:13px monospace}#tm-v4-drop .rows{max-height:155px;overflow:auto;background:#111;border-radius:6px;padding:4px}#tm-v4-drop [data-state=CONFIRMED]{color:#bfffcf}#tm-v4-drop [data-state=UNKNOWN],#tm-v4-drop [data-state=SUBMITTED]{color:#ffe08c}#tm-v4-drop [data-state=REJECTED]{color:#ffb3b3}#tm-v4-drop [data-action=run]{background:#176a3a}#tm-v4-drop [data-action=pause]{background:#a05b20}#tm-v4-drop [data-action=clear]{background:#6b3030}#tm-v4-drop .unable{background:#421b1b;color:#ffdada;padding:6px;border-radius:5px}#tm-v4-drop details{margin:7px 0}#tm-v4-drop select{max-width:100%}`;
 root.innerHTML=`<header><b>DZ Auto V4 ${esc(version)}</b><button data-action="enable"></button><b data-destination></b></header><button data-type="PRIME" style="width:100%;background:#6b55c9">PRIME • dz-P-PRIME</button><b>Floor</b><div class="grid">${['P1','P2','P3','P4'].map(floor=>`<button data-floor="${floor}">${floor}</button>`).join('')}</div><b>Dropzone</b><div class="grid drops"></div><hr><b>Container Queue • API</b> <button data-action="input"></button><textarea autocomplete="off" spellcheck="false" placeholder="Scan/paste tsX / csX containers"></textarea><div class="unable" hidden></div><div class="grid" style="grid-template-columns:1fr 1fr"><button data-action="run">RUN</button><button data-action="pause">PAUSE</button></div><div data-counts></div><div role="status">Ready</div><div class="rows"></div><div class="grid" style="grid-template-columns:1fr 1fr"><button data-action="done">CLEAR DONE</button><button data-action="clear">CLEAR ALL</button></div><details><summary>Location verification</summary><label>Authenticated FCR host <select data-origin>${['https://fcresearch-fe.aka.amazon.com','https://qi-fcresearch-fe.corp.amazon.com','https://qi-fcresearch-jp.corp.amazon.com','https://qifcr.fe.aftx.amazonoperations.app'].map(origin=>`<option value="${origin}">${origin}</option>`).join('')}</select></label></details>`;
 const input=root.querySelector('textarea'),status=text=>root.querySelector('[role=status]').textContent=text;
 const origins=root.querySelector('[data-origin]');origins.value=storage.getItem('tm-v4.drop.fcr-origin')||'https://fcresearch-fe.aka.amazon.com';
 function render(){if(disposed||!journal)return;root.querySelector('[data-destination]').textContent=dropzone(prefs.floor,prefs.type)||'SELECT DZ';root.querySelector('[data-action=enable]').textContent=prefs.enabled?'ON':'OFF';root.querySelector('[data-action=input]').textContent=prefs.inputEnabled?'INPUT ON':'INPUT OFF';input.readOnly=!prefs.inputEnabled;root.querySelectorAll('[data-floor]').forEach(button=>{button.dataset.selected=String(button.dataset.floor===prefs.floor);button.disabled=processing||nativeBusy;});root.querySelector('[data-type=PRIME]').disabled=processing||nativeBusy;root.querySelector('[data-type=PRIME]').dataset.selected=String(prefs.type==='PRIME');root.querySelector('.drops').innerHTML=prefs.type==='PRIME'?'PRIME selected (no DZ needed)':(prefs.floor==='P1'?DROPZONES.p1:DROPZONES.upper).map(([type])=>`<button data-type="${esc(type)}" data-selected="${type===prefs.type}" ${processing||nativeBusy?'disabled':''}>${esc(type)}</button>`).join('');root.querySelector('[data-counts]').textContent=`${journal.rows.filter(row=>row.state==='QUEUED').length} queued • ${journal.rows.filter(row=>row.state==='CONFIRMED').length} done • ${journal.rows.filter(row=>['SUBMITTED','UNKNOWN'].includes(row.state)).length} unresolved`;root.querySelector('.rows').innerHTML=journal.rows.map(row=>`<div data-state="${row.state}"><b>${esc(row.container)}</b> → ${esc(row.destination)}<br>${row.state} ${esc(row.message)}</div>`).join('');root.querySelector('[data-action=run]').disabled=processing||nativeBusy;origins.disabled=processing||nativeBusy;}
 function persistPrefs(){storage.setItem(prefKey,JSON.stringify(prefs));render();}
 function transition(row,state,message){journal.transition(row,state,message);render();if(['SUBMITTED','CONFIRMED','REJECTED','UNKNOWN'].includes(state))onEvidence({type:'drop.operation',intent:'mutation',phase:state,operationId:row.operationId,data:{outcome:state,stage:row.phase||'move'}});}
 async function edit(work){if(owner)return work();return withOperationLock(window,'tm-v4.move-container.owner',async()=>{load();return work();});}
 async function add(){const destination=dropzone(prefs.floor,prefs.type);if(!destination)throw new Error('Select exact floor/dropzone');const values=input.value.split(/[\s,;]+/).filter(Boolean),invalid=values.filter(value=>!normalizeHierarchyContainer(value)&&upper(value)!=='123START');const valid=values.filter(normalizeHierarchyContainer);root.querySelector('.unable').hidden=!invalid.length;root.querySelector('.unable').textContent='Unable: '+invalid.join(' • ');if(valid.length)await edit(()=>journal.add(valid,{destination}));input.value='';window.sessionStorage.setItem('tm-v4.drop.draft','');render();}
 function pause(){const nativeSettled=onPause();running=false;if(currentRow?.state==='READING')controller?.abort();status(currentRow?.state==='SUBMITTED'?'PAUSED — submitted outcome still pending':'Paused');render();return nativeSettled;}
 async function run(){if(processing||nativeBusy||disposed)return;try{await add();}catch(error){status(error.message);return;}processing=running=true;render();
  runPromise=withOperationLock(window,'tm-v4.move-container.owner',async()=>{owner=true;load();journal.save();identity();while(running&&!disposed){const row=journal.next();if(!row)break;currentRow=row;controller=new window.AbortController();let submitted=false;transition(row,'READING','Checking native location');try{await move(row,{signal:controller.signal,fcrOrigin:origins.value,checkRunning:()=>{if(!running||disposed)throw new Error('Paused before movement');},onPhase:phase=>{row.phase=phase;journal.save();render();},beforeMutation:()=>{if(!running||disposed)throw new Error('Paused before movement');identity();row.operationId=uuid();transition(row,'SUBMITTED','Submitted — verifying location');submitted=true;}});if(disposed)break;transition(row,'CONFIRMED','Exact native destination verified');status('Moved ✓ '+row.container);}catch(error){if(disposed)break;transition(row,submitted?(error.outcome==='REJECTED'?'REJECTED':'UNKNOWN'):!running||controller.signal.aborted?'QUEUED':'REJECTED',error.message);status(error.message);running=false;}finally{currentRow=null;controller=null;}}}).catch(error=>status(error.message)).finally(()=>{owner=running=processing=false;runPromise=null;render();});await runPromise;
 }
 async function clear(doneOnly=false){await pause();if(runPromise)await runPromise;try{await edit(()=>{if(doneOnly)journal.clearConfirmed();else journal.clear();});if(!doneOnly)input.value='';render();status('Cleared safe rows; unresolved outcomes retained');}catch(error){status(error.message);}}
 function autoDestination(){if(disposed||processing||nativeBusy||!prefs.enabled)return;const host=d.querySelector('#root,#app,main')||d.body;if(!host)return;const text=[...host.childNodes].filter(node=>node!==root&&!(node.nodeType===1&&node.hasAttribute('data-tm-v4-script'))).map(node=>node.textContent).join(' ');const step=/scan destination container/i.test(text);if(!step){lastStep=false;return;}if(lastStep)return;const destination=dropzone(prefs.floor,prefs.type);if(!destination){status('Select floor/dropzone');return;}const fields=[...host.querySelectorAll('input,textarea')].filter(node=>!node.closest('[data-tm-v4-script]')&&!node.disabled&&!node.readOnly&&!node.hidden&&window.getComputedStyle(node).display!=='none');if(fields.length!==1){status('Native scan field missing/ambiguous');return;}lastStep=true;const target=fields[0],prototype=target.tagName==='TEXTAREA'?window.HTMLTextAreaElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(prototype,'value').set.call(target,destination);target.dispatchEvent(new window.Event('input',{bubbles:true}));target.dispatchEvent(new window.Event('change',{bubbles:true}));target.focus();for(const type of ['keydown','keypress','keyup']){const event=new window.KeyboardEvent(type,{key:'Enter',code:'Enter',bubbles:true,cancelable:true});for(const property of ['keyCode','which'])Object.defineProperty(event,property,{get:()=>13});target.dispatchEvent(event);}}
 root.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const action=button.dataset.action;if(button.dataset.floor&&!processing&&!nativeBusy){prefs.floor=button.dataset.floor;prefs.type='';lastStep=false;persistPrefs();}if(button.dataset.type&&!processing&&!nativeBusy){prefs.type=button.dataset.type;lastStep=false;persistPrefs();}if(action==='enable'){prefs.enabled=!prefs.enabled;lastStep=false;persistPrefs();}if(action==='input'){prefs.inputEnabled=!prefs.inputEnabled;persistPrefs();}if(action==='run')void run();if(action==='pause')pause();if(action==='done')void clear(true);if(action==='clear')void clear(false);autoDestination();},{signal:listeners.signal});
 input.addEventListener('input',()=>window.sessionStorage.setItem('tm-v4.drop.draft',input.value),{signal:listeners.signal});
 d.addEventListener('keydown',event=>{if(event.altKey&&['=','+'].includes(event.key)){event.preventDefault();root.hidden=!root.hidden;return;}if(event.target!==input||!prefs.inputEnabled)return;event.stopPropagation();event.stopImmediatePropagation();if(event.key==='Enter'){if(upper(input.value.split(/\r?\n/).at(-1))==='123START'){event.preventDefault();input.value=input.value.replace(/123START\s*$/i,'');void run();}else if(running){event.preventDefault();void add().catch(error=>status(error.message));}}},{capture:true,signal:listeners.signal});
 for(const type of ['keypress','keyup'])d.addEventListener(type,event=>{if(event.target===input&&prefs.inputEnabled){event.stopPropagation();event.stopImmediatePropagation();}},{capture:true,signal:listeners.signal});
 origins.addEventListener('change',()=>storage.setItem('tm-v4.drop.fcr-origin',origins.value),{signal:listeners.signal});
 function ready(){const host=d.querySelector('#root,#app,main')||d.body;if(host){observer=new window.MutationObserver(records=>{if(records.every(record=>root.contains(record.target)))return;autoDestination();});observer.observe(host,{childList:true,subtree:true,characterData:true});autoDestination();}}
 try{load();input.value=window.sessionStorage.getItem('tm-v4.drop.draft')||'';render();}catch(error){status(error.message);root.querySelector('[data-action=run]').disabled=true;}
 d.documentElement.append(style,root);if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',ready,{once:true,signal:listeners.signal});else ready();
 return{root,run,pause,clear,setNativeBusy:value=>{nativeBusy=value;render();},refreshNative:message=>{if(!processing){try{load();render();}catch(error){status(error.message);}}if(message)status(message);},getState:()=>journal?.rows,dispose(){if(disposed)return;running=false;if(currentRow){try{transition(currentRow,currentRow.state==='SUBMITTED'?'UNKNOWN':'QUEUED','Page disposed — verify submitted outcome');}catch{}}disposed=true;controller?.abort();listeners.abort();observer?.disconnect();root.remove();style.remove();}};
}
