import{createOperationJournal,withOperationLock}from'./operation-journal.mjs';import{validateLocation,validateMoveEnvelope}from'./move-container.mjs';import{clean,upper}from'./ui-tools.mjs';
export function createDropNative({window,page=window,reader,identity,onChange=()=>{},onBusy=()=>{},onEvidence=()=>{}}){
 let disposed=false;const tasks=new Set(),details=new WeakMap(),key='tm-v4.drop.rows';
 function selected(url,method){try{const target=new window.URL(url,window.location.href);return String(method).toUpperCase()==='POST'&&target.origin===window.location.origin&&target.pathname==='/api/move-container';}catch{return false;}}
 async function guard(body,sendNative,responseInfo,signal){
  const controller=new window.AbortController(),task={controller,row:null,journal:null};task.settled=new Promise(resolve=>task.finish=resolve);tasks.add(task);onBusy(true);const cancel=()=>controller.abort();signal?.addEventListener('abort',cancel,{once:true});
  try{return await withOperationLock(window,'tm-v4.move-container.owner',async()=>{
   if(disposed||signal?.aborted)throw new Error('Native move cancelled before submission');let payload;try{payload=JSON.parse(body);}catch{throw new Error('Native move payload is not exact JSON');}
   const container=clean(payload?.containerScannableId),destination=clean(payload?.destinationScannableId);
   if(!/^(?:tsX|csX)[A-Za-z0-9_-]+$/i.test(container)||!/^dz-[A-Za-z0-9_-]+$/.test(destination)||payload.confirmed!==true&&payload.confirmed!=='true'||payload.sourceScannableId!==null)throw new Error('Native move payload/context is unsupported — no request sent');
   identity();const capability=typeof reader==='function'?reader():reader;const journal=createOperationJournal({storage:window.localStorage,key,uuid:()=>window.crypto.randomUUID()});task.journal=journal;
   if(journal.rows.some(row=>upper(row.container)===upper(container)&&['QUEUED','READING','SUBMITTED','UNKNOWN'].includes(row.state)))throw new Error('Native move has unresolved or queued ownership for this container');
   const row=journal.add([container],{mode:'drop',kind:'native-move',destination})[0];task.row=row;journal.transition(row,'READING','Native move location preflight');onChange('Native preflight • '+container);
   validateLocation(await capability.inventory(container,{signal:controller.signal}),container);
   if(disposed||controller.signal.aborted)throw new Error('Native move cancelled before submission');identity();journal.transition(row,'SUBMITTED','Native move submitted — result pending',{operationId:row.id});onChange('SUBMITTED • native '+container);onEvidence({type:'operation',intent:'mutation',operationId:row.id,phase:'SUBMITTED',data:{kind:'native-move'}});
   let native;const expired=()=>controller.abort();const timer=window.setTimeout(expired,25000);let cancelAwait;const interrupted=new Promise((_,reject)=>{cancelAwait=()=>reject(new Error('Native move request cancelled/timed out'));controller.signal.addEventListener('abort',cancelAwait,{once:true});});try{native=await Promise.race([sendNative(controller.signal),interrupted]);const info=await responseInfo(native);validateMoveEnvelope(info,await info.text());}finally{window.clearTimeout(timer);controller.signal.removeEventListener('abort',cancelAwait);}
   try{validateLocation(await capability.inventory(container,{signal:controller.signal}),container,destination);}catch(error){throw Object.assign(error,{outcome:'UNKNOWN'});}
   journal.transition(row,'CONFIRMED','Exact native destination location verified');onChange('CONFIRMED • native '+container);onEvidence({type:'operation',intent:'mutation',operationId:row.id,phase:'CONFIRMED',data:{kind:'native-move'}});return native;
  });}catch(error){const row=task.row;let outcome=row?.state==='SUBMITTED'||row?.state==='UNKNOWN'?'UNKNOWN':'REJECTED';if(row?.state==='SUBMITTED'&&error.outcome==='REJECTED')outcome='REJECTED';try{if(row&&row.state!=='UNKNOWN')task.journal.transition(row,outcome,error.message);}catch{outcome='UNKNOWN';}onChange(outcome+' • native move • '+error.message);if(row?.operationId)onEvidence({type:'operation',intent:'mutation',operationId:row.operationId,phase:outcome,data:{kind:'native-move'}});throw error;}
  finally{signal?.removeEventListener('abort',cancel);tasks.delete(task);task.finish();onBusy(tasks.size>0);}
 }
 const originalFetch=page.fetch;const wrapper=function(input,init={}){const url=typeof input==='string'||input instanceof window.URL?String(input):input?.url;if(!selected(url,init.method||input?.method||'GET')||disposed)return originalFetch.apply(this,arguments);const receiver=this;return guard(init.body,nativeSignal=>originalFetch.call(receiver,input,{...init,signal:nativeSignal}),async response=>({ok:response.ok,status:response.status,redirected:response.redirected||(response.url&&new window.URL(response.url,window.location.href).pathname!=='/api/move-container'),headers:response.headers,text:()=>response.clone().text()}),init.signal||input?.signal);};page.fetch=wrapper;
 const proto=page.XMLHttpRequest?.prototype,open=proto?.open,send=proto?.send,abort=proto?.abort;
 function wrappedOpen(method,url,async=true){details.set(this,{method,url,async,controller:null});return open.apply(this,arguments);}
 function wrappedSend(body){const metadata=details.get(this);if(!metadata||!selected(metadata.url,metadata.method)||disposed)return send.apply(this,arguments);if(metadata.async===false)throw new Error('Synchronous native move cannot acquire ownership — request blocked');metadata.controller=new window.AbortController();const xhr=this;void guard(body,nativeSignal=>new Promise((resolve,reject)=>{nativeSignal.addEventListener('abort',()=>abort.call(xhr),{once:true});xhr.addEventListener('loadend',()=>resolve(xhr),{once:true});try{send.call(xhr,body);}catch(error){reject(error);}}),async response=>({ok:response.status>=200&&response.status<300,status:response.status,redirected:!!response.responseURL&&new window.URL(response.responseURL,window.location.href).pathname!=='/api/move-container',headers:{get:key=>response.getResponseHeader?.(key)||''},text:async()=>{if(response.responseType==='json')return JSON.stringify(response.response);return response.responseText||'';}}),metadata.controller.signal).catch(()=>{if(xhr.readyState<2){xhr.dispatchEvent(new window.ProgressEvent('error'));xhr.dispatchEvent(new window.ProgressEvent('loadend'));}});return undefined;}
 function wrappedAbort(){details.get(this)?.controller?.abort();return abort.apply(this,arguments);}
 if(proto){proto.open=wrappedOpen;proto.send=wrappedSend;proto.abort=wrappedAbort;}
 return{pause(){for(const task of tasks)if(task.row?.state!=='SUBMITTED'&&task.row?.state!=='UNKNOWN')task.controller.abort();return Promise.allSettled([...tasks].map(task=>task.settled));},dispose(){if(disposed)return;disposed=true;for(const task of tasks){try{if(task.row?.state==='SUBMITTED'){task.journal.transition(task.row,'UNKNOWN','Native move disposed after submission');onEvidence({type:'operation',intent:'mutation',phase:'UNKNOWN',operationId:task.row.operationId,data:{kind:'native-move'}});}else if(task.row?.state==='READING')task.journal.transition(task.row,'REJECTED','Native preflight disposed');}catch{}task.controller.abort();}if(page.fetch===wrapper)page.fetch=originalFetch;if(proto?.open===wrappedOpen)proto.open=open;if(proto?.send===wrappedSend)proto.send=send;if(proto?.abort===wrappedAbort)proto.abort=abort;}};
}
