const PROTOCOL='tm-v4.iss',FCR=/^(?:fcresearch-fe\.aka\.amazon\.com|qi-fcresearch-(?:fe|jp)\.corp\.amazon\.com|qifcr\.fe\.aftx\.amazonoperations\.app)$/;
export const ISS_TARGETS=Object.freeze({aft:'https://aft-qt-jp.aka.nrt.corp.amazon.com/app/edititems?experience=Desktop',sideline:'https://aft-poirot-website-nrt.nrt.proxy.amazon.com/'});
export function issWorkerContext(window){const nonce=/^#tm-v4-iss-worker=([a-f0-9-]{20,80})$/.exec(window.location.hash)?.[1];if(!nonce||window.parent===window)return null;try{const origin=new window.URL(window.location.href).searchParams.get('tmV4ParentOrigin'),url=new window.URL(origin);if(url.origin!==origin||!FCR.test(url.hostname)||!/^https?:$/.test(url.protocol))return null;return{nonce,parentOrigin:origin};}catch{return null;}}
export function createIssBridge({window,onProgress=()=>{},onEvidence=()=>{},onDate=async()=>null,healthTimeout=15000,runTimeout=12*60*1000}){const d=window.document,events=new window.AbortController(),peers=new Map();let disposed=false;
 function peer(kind){if(!ISS_TARGETS[kind])throw new Error('Unknown ISS worker');let item=peers.get(kind);if(item)return item;const nonce=window.crypto.randomUUID(),frame=d.createElement('iframe'),url=new window.URL(ISS_TARGETS[kind]);url.searchParams.set('tmV4ParentOrigin',window.location.origin);url.hash='tm-v4-iss-worker='+nonce;frame.dataset.tmV4Script='ISSC';frame.title='ISS native '+kind+' worker';frame.tabIndex=-1;frame.setAttribute('aria-hidden','true');frame.style.cssText='position:fixed;left:-12000px;top:0;width:1280px;height:900px;opacity:0;pointer-events:none;border:0';let readyResolve,readyReject;const ready=new Promise((resolve,reject)=>{readyResolve=resolve;readyReject=reject;});item={kind,nonce,origin:url.origin,frame,ready,readyResolve,readyReject,pending:new Map(),readyState:false};item.timer=window.setTimeout(()=>{item.readyReject(Object.assign(new Error(kind.toUpperCase()+' native worker unavailable — authenticate/open native application, then reconnect'),{outcome:'REJECTED'}));item.unavailable=true;},healthTimeout);peers.set(kind,item);frame.addEventListener('load',()=>{try{send(item,'hello');}catch(error){onProgress({kind,stage:'error',message:error.message});}});frame.src=url.href;d.documentElement.append(frame);return item;}
 function send(item,type,data={}){if(disposed)throw new Error('ISS bridge disposed');item.frame.contentWindow.postMessage({protocol:PROTOCOL,nonce:item.nonce,type,...data},item.origin);}
 async function run(kind,payload,{requestId=window.crypto.randomUUID()}={}){const item=peer(kind);await item.ready;if(disposed)throw new Error('ISS disposed');return new Promise((resolve,reject)=>{const timer=window.setTimeout(()=>{item.pending.delete(requestId);try{send(item,'control',{action:'stop',area:payload.area});}catch{}reject(Object.assign(new Error('Native workflow timed out after handoff — UNKNOWN; verify before retry'),{outcome:'UNKNOWN'}));},runTimeout);item.pending.set(requestId,{resolve,reject,timer});try{send(item,'run',{requestId,payload});}catch(error){window.clearTimeout(timer);item.pending.delete(requestId);reject(Object.assign(error,{outcome:'UNKNOWN'}));}});}
 function control(kind,action,data={}){const item=peers.get(kind);if(item?.readyState)send(item,'control',{action,...data});}
 async function message(event){const data=event.data;if(data?.protocol!==PROTOCOL)return;const item=[...peers.values()].find(peer=>event.source===peer.frame.contentWindow&&event.origin===peer.origin&&data.nonce===peer.nonce);if(!item||disposed)return;if(data.type==='ready'){if(item.unavailable)return;window.clearTimeout(item.timer);item.readyState=true;item.readyResolve();onProgress({kind:item.kind,stage:'connected'});return;}const pending=item.pending.get(data.requestId);if(!pending)return;if(data.type==='progress'){onProgress({kind:item.kind,...data.data});return;}if(data.type==='evidence'){onEvidence(data.record);return;}if(data.type==='date'){const value=await onDate({kind:item.kind,requestId:data.requestId,dateId:data.dateId,code:data.code,ctx:data.ctx});if(!disposed&&item.pending.has(data.requestId))send(item,'date-result',{requestId:data.requestId,dateId:data.dateId,value});return;}if(data.type==='date-cancel'){onProgress({kind:item.kind,stage:'date-cancel'});return;}if(data.type==='result'){window.clearTimeout(pending.timer);item.pending.delete(data.requestId);if(data.error)pending.reject(Object.assign(new Error(data.error.message),{outcome:data.error.outcome||'UNKNOWN',rows:data.rows||[]}));else pending.resolve(data.result);}}
 window.addEventListener('message',event=>void message(event).catch(error=>onProgress({stage:'error',message:error.message})),{signal:events.signal});
 function reconnect(kind){const item=peers.get(kind);if(item?.pending.size)throw new Error('Native workflow pending — reconnect would erase uncertainty');if(item){window.clearTimeout(item.timer);item.frame.remove();peers.delete(kind);}return peer(kind).ready;}
 return{run,control,reconnect,ready:kind=>peer(kind).ready,getPeer:kind=>peers.get(kind),dispose(){if(disposed)return;for(const item of peers.values()){if(item.readyState){try{send(item,'control',{action:'stop'});}catch{}}window.clearTimeout(item.timer);item.readyReject(new Error('ISS disposed before worker ready'));for(const pending of item.pending.values()){window.clearTimeout(pending.timer);pending.reject(Object.assign(new Error('ISS disposed after native handoff — verify outcome'),{outcome:'UNKNOWN'}));}item.frame.remove();}disposed=true;events.abort();peers.clear();}};
}
export function serveIssWorker({window,kind,engine,onDispose=()=>{}}){const context=issWorkerContext(window);if(!context)return null;const events=new window.AbortController(),seen=new Set(),dates=new Map();let busy=false,disposed=false,requestId='',area='';
 const send=(type,data={})=>{if(!disposed)window.parent.postMessage({protocol:PROTOCOL,nonce:context.nonce,type,requestId,...data},context.parentOrigin);};
 function progress(data){send('progress',{data:{kind,area,...data}});}function evidence(record){send('evidence',{record});}
 function pickDate({code,ctx,signal}){const dateId=window.crypto.randomUUID();return new Promise(resolve=>{const finish=value=>{dates.delete(dateId);signal?.removeEventListener('abort',cancel);resolve(value);},cancel=()=>{send('date-cancel',{dateId});finish(null);};dates.set(dateId,finish);signal?.addEventListener('abort',cancel,{once:true});if(signal?.aborted)return cancel();send('date',{dateId,code,ctx:{asin:ctx.asin,fnsku:ctx.fnsku,dateType:ctx.dateType,dateDetail:ctx.dateDetail,sku:{title:ctx.sku?.title||ctx.sku?.normalizedTitle,imageUrl:ctx.sku?.imageUrl}}});});}
 const api=engine({progress,evidence,pickDate});
 async function message(event){const data=event.data;if(event.source!==window.parent||event.origin!==context.parentOrigin||data?.protocol!==PROTOCOL||data.nonce!==context.nonce||disposed)return;if(data.type==='hello'){send('ready',{kind});return;}if(data.type==='date-result'){if(data.requestId===requestId&&(data.value===null||Number.isFinite(data.value)))dates.get(data.dateId)?.(data.value);return;}if(data.type==='control'){if(['stop','clear','pause','scan'].includes(data.action))api[data.action]?.(data);return;}if(data.type!=='run')return;if(busy||seen.has(data.requestId)||typeof data.requestId!=='string'||!data.payload){send('result',{requestId:data.requestId,error:{message:'Native owner busy or command already handled',outcome:'REJECTED'}});return;}seen.add(data.requestId);requestId=data.requestId;area=data.payload.area;busy=true;try{const result=await api.run(data.payload);send('result',{result});}catch(error){send('result',{error:{message:error.message,outcome:error.outcome||'UNKNOWN'},rows:api.rows?.()||[]});}finally{busy=false;requestId='';area='';}}
 window.addEventListener('message',event=>void message(event).catch(error=>progress({stage:'error',message:error.message})),{signal:events.signal});send('ready',{kind});return{dispose(){if(disposed)return;api.stop?.({});api.dispose?.();for(const resolve of dates.values())resolve(null);dates.clear();disposed=true;events.abort();onDispose();}};
}
