import{clean}from'./ui-tools.mjs';
const norm=value=>clean(value).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
export function riverStep(window){const d=window.document,label=d.querySelector('page-info[label]')?.getAttribute('label')||[...d.querySelectorAll('h1,h2,h3,h4,[role=heading],legend')].find(node=>!node.closest('[data-tm-v4-script]')&&!node.hidden)?.textContent||'',text=norm(label);for(const[key,rx]of[['pandash',/pandash/],['related',/related.*(?:tt|ticket)/],['information',/information/],['sortability',/sortab|sort.*non sort/],['severity',/severity/],['images',/image/],['create',/create (?:issue|ticket)/],['asin',/^(?:asin)$|asin check|enter asin/],['issue',/issue.*fc/]])if(rx.test(text))return key;return'unknown';}
export function createRiverAssistant({window,getPayload,clearPayload,onEvidence=()=>{}}){const d=window.document,events=new window.AbortController();let active=false,disposed=false,busy=false,controller=null,lastSubmitted='',manual=false,watcher=null,deadline=0;
 const root=d.createElement('aside');root.id='tm-v4-river';root.dataset.tmV4Script='RIVR';root.innerHTML='<b>RIVER V4</b><span data-id></span><div role="status">READY</div><button data-run>RUN</button><button data-clear>STOP / CLEAR</button>';const style=d.createElement('style');style.dataset.tmV4Style='RIVR';style.textContent='#tm-v4-river{position:fixed;left:14px;bottom:14px;z-index:2147483647;width:300px;padding:10px;border:2px solid #475569;border-radius:8px;background:white;color:#111;font:12px Arial;box-shadow:0 4px 16px #0004}#tm-v4-river span{float:right;max-width:145px;overflow:hidden;text-overflow:ellipsis}#tm-v4-river [role=status]{clear:both;padding:8px 0;font-weight:700}#tm-v4-river button{width:49%;min-height:30px;font-weight:800;cursor:pointer}';d.body.append(root);d.head.append(style);const status=text=>root.querySelector('[role=status]').textContent=text;
 const visible=node=>node&&!node.hidden&&!node.closest('[data-tm-v4-script],[hidden]')&&window.getComputedStyle(node).display!=='none'&&window.getComputedStyle(node).visibility!=='hidden',enabled=node=>visible(node)&&!node.disabled&&!node.readOnly&&node.getAttribute('aria-disabled')!=='true';
 function check(step,signal){if(disposed||!active||signal?.aborted||step!==riverStep(window))throw new Error('Stopped or native step changed');}
 function field(aliases){const wanted=aliases.map(norm),matches=[...d.querySelectorAll('input,textarea,select')].filter(visible).filter(node=>{const label=norm([node.name,node.id,node.placeholder,node.getAttribute('aria-label'),...(node.labels||[])].map(value=>value?.textContent||value||'').join(' '));return wanted.some(value=>value.length<=3?label.split(' ').includes(value):label.includes(value));});if(matches.length!==1)throw new Error('Native field missing/ambiguous: '+aliases[0]);return matches[0];}
 function nextButton(){const matches=[...d.querySelectorAll('button,a,[role=button],input[type=button],input[type=submit]')].filter(node=>visible(node)&&norm(node.textContent||node.value||node.getAttribute('aria-label'))==='next');return matches.length===1?matches[0]:null;}
 function wait(checkReady,signal,timeout=8000){return new Promise((resolve,reject)=>{let done=false;const finish=(value,error)=>{if(done)return;done=true;observer.disconnect();window.clearTimeout(timer);signal?.removeEventListener('abort',cancel);if(error)reject(error);else resolve(value);},cancel=()=>finish(null,new Error('Stopped')),assess=()=>{if(done)return;try{const value=checkReady();if(value)finish(value);}catch{}};const observer=new window.MutationObserver(assess);observer.observe(d.body,{subtree:true,childList:true,attributes:true,attributeFilter:['disabled','readonly','aria-disabled','label']});const timer=window.setTimeout(()=>finish(null,new Error('Native form readiness timeout')),timeout);signal?.addEventListener('abort',cancel,{once:true});if(signal?.aborted)cancel();else assess();});}
 async function frame(signal){await new Promise(resolve=>window.requestAnimationFrame?window.requestAnimationFrame(resolve):window.queueMicrotask(resolve));if(signal.aborted)throw new Error('Stopped');}
 async function set(node,value,step,signal){check(step,signal);if(!enabled(node))throw new Error('Native field is disabled');node.focus({preventScroll:true});await frame(signal);check(step,signal);if(!node.isConnected||!enabled(node))throw new Error('Native field replaced/disabled');const proto=node.tagName==='TEXTAREA'?window.HTMLTextAreaElement.prototype:node.tagName==='SELECT'?window.HTMLSelectElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(node,String(value));node.dispatchEvent(new window.Event('input',{bubbles:true,composed:true}));node.dispatchEvent(new window.Event('change',{bubbles:true,composed:true}));await frame(signal);check(step,signal);node.blur();await frame(signal);check(step,signal);if(clean(node.value)!==clean(value))throw new Error('Native field did not retain value');}
 function choice(index,step,signal){check(step,signal);const radios=[...d.querySelectorAll('input[type=radio],[role=radio]')].filter(enabled).filter(node=>!node.querySelector('input[type=radio]'));if(!radios[index-1])throw new Error('Expected native choice '+index+' unavailable');radios[index-1].click();}
 async function advance(step,signal){check(step,signal);const button=await wait(()=>{const node=nextButton();return enabled(node)?node:null;},signal,4000);check(step,signal);if(lastSubmitted===step)throw new Error('Next already submitted for this step — wait for native transition');lastSubmitted=step;onEvidence({type:'river.step',intent:'workflow',data:{step,stage:'next-submitted'}});button.click();status('Next submitted • waiting for native step');deadline=window.setTimeout(()=>{if(active&&lastSubmitted===step&&riverStep(window)===step){status('UNKNOWN • native step did not advance; no automatic repeat');stopWatch();}},12000);}
 function stopWatch(){watcher?.disconnect();watcher=null;window.clearTimeout(deadline);deadline=0;}
 function watch(){if(watcher||!active)return;watcher=new window.MutationObserver(records=>{if(records.every(record=>root.contains(record.target)))return;if(!busy&&active){const step=riverStep(window);if(step!=='unknown'&&step!==lastSubmitted){window.clearTimeout(deadline);deadline=0;void drive();}}});watcher.observe(d.body,{subtree:true,childList:true,attributes:true,attributeFilter:['label','disabled','readonly','aria-disabled']});}
 async function drive(){if(busy||!active||disposed)return;const payload=getPayload();if(!payload||payload.schema!==1){status('No V4 FCResearch payload');return;}busy=true;controller=new window.AbortController();const signal=controller.signal,step=riverStep(window);try{root.querySelector('[data-id]').textContent=payload.fnsku!=='N/A'?payload.fnsku:payload.asin;status('RUN • '+step);if(step==='unknown'){status('WAITING • native workflow state unavailable');watch();return;}if(step==='related'||step==='create'){manual=true;stopWatch();status(step==='create'?'DONE • final Create Issue stays manual':'PAUSED • review related tickets, then native Next');return;}if(lastSubmitted===step){status('UNKNOWN • Next already submitted; wait for native transition');return;}manual=false;
 if(['pandash','issue','sortability'].includes(step))choice(step==='pandash'?2:1,step,signal);
 else if(step==='asin'){if(payload.asin==='N/A')throw new Error('ASIN unavailable — manual step');await set(field(['type asin here','asin']),payload.asin,step,signal);}
 else if(step==='information'){const entries=[[['fnsku','x0 asin','x00 asin'],payload.fnsku],[['purchase order','po'],payload.purchaseOrder],[['vendor code','seller id'],payload.vendorCode],[['inventory cost','cost per unit'],payload.inventoryCost],[['physical location'],'TBD'],[['asin title','product title','title'],payload.title]];await wait(()=>entries.map(([aliases])=>field(aliases)).every(enabled),signal);check(step,signal);for(const[aliases,value]of entries){await set(field(aliases),value||'N/A',step,signal);if(aliases[0]==='asin title')await set(field(aliases),(value||'N/A')+' ',step,signal);}}
 else if(step==='severity'){await set(field(['shipments impacted']),0,step,signal);if(!Number.isFinite(payload.inventoryQuantity)||payload.inventoryQuantity<=0){manual=true;stopWatch();status('PAUSED • PO quantity unavailable/0; enter Units impacted, then native Next');return;}await set(field(['units impacted']),payload.inventoryQuantity,step,signal);}
 else if(step==='images'){const selects=[...d.querySelectorAll('select')].filter(enabled);if(selects.length!==1)throw new Error('Native image dropdown missing/ambiguous');const options=[...selects[0].options].filter(option=>!option.disabled&&!option.hidden);if(!options[1])throw new Error('Native image option 2 missing');await set(selects[0],options[1].value,step,signal);}
 else throw new Error('Native step unsupported');await advance(step,signal);watch();}catch(error){if(active&&!disposed&&!signal.aborted){status('WAITING • '+error.message);stopWatch();onEvidence({type:'river.error',intent:'workflow',data:{step,message:error.message}});}}finally{busy=false;controller=null;if(active&&lastSubmitted===step&&riverStep(window)!=='unknown'&&riverStep(window)!==lastSubmitted&&!manual)window.queueMicrotask(()=>void drive());}}
 function stop(clear=true){active=false;manual=false;controller?.abort();stopWatch();status('STOPPED / CLEARED');root.querySelector('[data-id]').textContent='';if(clear)clearPayload();}
 root.querySelector('[data-run]').onclick=()=>{active=true;watch();void drive();};root.querySelector('[data-clear]').onclick=stop;d.addEventListener('click',event=>{if(!active||!manual||event.target.closest('#tm-v4-river')||event.target.closest('button,a,[role=button]')!==nextButton())return;manual=false;lastSubmitted=riverStep(window);watch();},{capture:true,signal:events.signal});return{root,drive,stop,dispose(){if(disposed)return;stop(false);disposed=true;events.abort();root.remove();style.remove();}};
}
