import{clean,upper}from'./ui-tools.mjs';import{createOperationJournal,withOperationLock}from'./operation-journal.mjs';import{createNativeOperationTap}from'./native-operation-tap.mjs';import{classifySidelineMutation}from'./sideline-client.mjs';import{validSidelineContainer}from'./sideline-workflow.mjs';import{createDatePicker}from'./date-picker.mjs';
export function setNativeField(window,input,value){const old=input.value,proto=input.tagName==='TEXTAREA'?window.HTMLTextAreaElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(input,String(value));input._valueTracker?.setValue?.(old);input.dispatchEvent(new window.Event('input',{bubbles:true}));input.dispatchEvent(new window.Event('change',{bubbles:true}));}
export function createSidelineNative({window,page=window,client,identity,canAssist=()=>true,onEvidence=()=>{}}){
 const d=window.document,picker=createDatePicker(window),key='tm-v4.sideline.rows';const waits=new Set();const status=d.createElement('div');status.dataset.tmV4Script='SIDE';status.id='tm-v4-side-native-status';status.setAttribute('role','status');status.style.cssText='position:fixed;left:14px;bottom:14px;z-index:2147483645;max-width:450px;padding:7px;background:#eef8ff;color:#153d5f;border:1px solid #9eb8cd;font:12px Arial;white-space:pre-wrap';status.hidden=true;d.body.append(status);const say=message=>{if(!disposed){status.hidden=!message;status.textContent=message;}};let disposed=false,owner=null,expiryActive=false,expirySeen=null,expiryController=null;
 const native=node=>node&&!node.closest?.('[data-tm-v4-script]')&&!node.hidden&&!node.disabled&&window.getComputedStyle(node).display!=='none'&&window.getComputedStyle(node).visibility!=='hidden';
 const text=()=>[...d.body.children].filter(native).map(n=>n.textContent||'').join(' ').toLowerCase();
 const roots=()=>{const result=[d];for(let i=0;i<result.length&&i<200;i++)for(const node of result[i].querySelectorAll('*'))if(node.shadowRoot&&!node.closest('[data-tm-v4-script]'))result.push(node.shadowRoot);return result;};const all=selector=>roots().flatMap(root=>[...root.querySelectorAll(selector)]);const buttons=()=>all('button,[role=button],input[type=submit],alchemy-button,mdw-button').filter(native);
 const button=re=>buttons().find(b=>re.test(clean(b.textContent||b.value)));
 const click=node=>{const target=node?.shadowRoot?.querySelector('button,[role=button],input[type=submit]')||node;for(const type of ['mouseover','mousedown','mouseup'])target.dispatchEvent(new window.MouseEvent(type,{bubbles:true,composed:true}));target.click();};const confirm=()=>native(d.querySelector('#confirm-button'))?d.querySelector('#confirm-button'):button(/^(confirm|item match|continue|submit|enter)\b/i);
 function fields(){const inputs=all('input,textarea').filter(native);return inputs.filter(input=>/^(text|search|tel|number|)$/.test(input.type||''));}
 function dateFields(){const list=fields(),find=re=>{const found=list.filter(input=>re.test([input.id,input.name,input.placeholder,input.getAttribute('aria-label')].join(' ').toLowerCase()));return found.length===1?found[0]:null;};const month=find(/\b(mm|month)\b/),day=find(/\b(dd|day)\b/),year=find(/\b(yyyy|year)\b/);return month&&day&&year?{month,day,year}:null;}
 function journal(){return createOperationJournal({storage:window.localStorage,key,uuid:()=>window.crypto.randomUUID()});}
 function finish(result){if(!owner||owner.done)return;owner.done=true;if(owner.row){try{owner.journal.transition(owner.row,result.outcome,result.reason||'Typed native outcome');}catch{result={outcome:'UNKNOWN',reason:'Recovery result could not be saved'};}}say(result.outcome+' • '+(result.reason||'Typed native response'));owner.resolve(result);onEvidence(owner.submittedRequest?{type:'sideline.native-result',intent:'mutation',phase:result.outcome,operationId:owner.submittedRequest,data:{state:result.outcome}}:{type:'sideline.native-form',intent:'workflow',data:{kind:owner.kind,state:result.outcome}});}
 const tap=createNativeOperationTap({window,page,paths:['/api/move-items','/api/close-container'],onBefore:({path,payload})=>{
  if(!owner)return null;if(owner.done)throw new Error('Native helper operation already settled');identity();if(!payload||typeof payload.requestId!=='string')throw new Error('Native mutation request identity missing');
  const kind=path==='/api/move-items'?'move':'close';if(owner.kind!==kind&&owner.kind!=='date')throw new Error('Unexpected native mutation blocked');
  if(kind==='move'&&(!validSidelineContainer(payload.sourceContainerScannableId)||!validSidelineContainer(payload.destinationContainerScannableId)||upper(payload.sourceContainerScannableId)===upper(payload.destinationContainerScannableId)||!clean(payload.scannableId)||!Number.isInteger(Number(payload.quantity))||Number(payload.quantity)<1||owner.quantity&&Number(payload.quantity)!==owner.quantity))throw new Error('Native move container/quantity context invalid');
  if(kind==='close'&&!validSidelineContainer(payload.containerScannableId))throw new Error('Native close container missing');
  if(owner.submittedRequest)throw new Error('Duplicate native mutation blocked');if(owner.journal.rows.some(r=>r!==owner.row&&r.requestId===payload.requestId))throw new Error('Native request ID already used — replay blocked');owner.submittedRequest=payload.requestId;
  owner.journal.transition(owner.row,'SUBMITTED','Native request submitted',{container:clean(kind==='move'?payload.scannableId:payload.containerScannableId),kind:kind==='move'?'native-qty':'native-close',source:payload.sourceContainerScannableId||payload.containerScannableId,destination:payload.destinationContainerScannableId||'',quantity:Number(payload.quantity)||0,requestId:payload.requestId});onEvidence({type:'sideline.native-submit',intent:'mutation',phase:'SUBMITTED',operationId:payload.requestId,data:{kind}});return{owner,kind};
 },onResult:record=>{if(record.context.owner!==owner||disposed)return;let result={outcome:'UNKNOWN',reason:'Native response/session/timeout unknown'};if(record.exact&&record.data&&((record.status>=200&&record.status<300)||[400,409,422].includes(record.status)))result=classifySidelineMutation(record.data,record.context.kind);finish(result);}});
 async function perform(kind,quantity,action,{timeout=300000}={}){
  if(disposed||owner)throw new Error('Native helper busy');return withOperationLock(window,'tm-v4.sideline.owner',async()=>{
   const ledger=journal();if(ledger.rows.some(r=>['SUBMITTED','UNKNOWN','QUEUED','READING'].includes(r.state)))throw new Error('Recovery rows require native verification or explicit Reset of unsubmitted work');await client.bootstrap();if(disposed)throw new Error('Native helper disposed before action');identity();if(!tap.owns())throw new Error('Native request observation unavailable — action blocked');
   const row=ledger.add(['native-'+kind+'-'+window.crypto.randomUUID()],{mode:'native',kind:'native-'+kind,quantity:quantity||0})[0];ledger.transition(row,'READING','Awaiting native '+kind+' step');let timer;const response=new Promise(resolve=>owner={kind,quantity,journal:ledger,row,resolve,done:false,submittedRequest:null});
   const cancel=()=>{if(owner&&!owner.done)finish({outcome:owner.row.state==='SUBMITTED'?'UNKNOWN':'REJECTED',reason:'Native helper cancelled/timed out'});};timer=window.setTimeout(cancel,timeout);
   try{await action(owner);const result=await response;if(result.outcome!=='CONFIRMED')throw Object.assign(new Error(result.outcome+' — '+result.reason),{outcome:result.outcome});return result.reason||'CONFIRMED by typed native response';}
   catch(error){if(owner&&!owner.done)finish({outcome:owner.row.state==='SUBMITTED'?'UNKNOWN':'REJECTED',reason:error.message});throw error;}
   finally{window.clearTimeout(timer);owner=null;expiryController?.abort();}
  });
 }
 function tryQuantity(){if(!owner||owner.kind!=='move'||owner.done||owner.stopRequested)return;const t=text();if(t.includes('verify item')){const b=confirm();if(b&&owner.verifyButton!==b){owner.verifyButton=b;click(b);}return;}
  if(!t.includes('enter quantity')||owner.quantitySent)return;const direct=d.querySelector('#scan-text-input'),list=fields();const input=native(direct)?direct:list.length===1?list[0]:null,b=confirm();if(!input||!b)return;owner.quantitySent=true;setNativeField(window,input,owner.quantity);owner.journal.transition(owner.row,'SUBMITTED','Native quantity confirm intent — request pending');click(b);
 }
 async function nativeExpiry(){
  if(disposed||expiryActive||(!owner&&!canAssist())||!text().match(/(?:expiration|expiry|production) date/))return;const dates=dateFields();if(!dates||expirySeen===dates.year)return;expirySeen=dates.year;expiryActive=true;expiryController=new window.AbortController();
  const production=/production date/.test(text()),ctx={dateType:production?'PRODUCTION_DATE':'EXPIRATION_DATE',dateDetail:{},sku:{title:[...d.querySelectorAll('h1,h2,h3,strong')].filter(native).map(n=>clean(n.textContent)).find(s=>s.length>18)||''}};
  try{const entered=await picker.pick({code:'NATIVE DATE',ctx,native:true,signal:expiryController.signal});if(entered===null||disposed||!dates.year.isConnected)return;const apply=async()=>{if(owner?.stopRequested||!dateFields()||!dates.year.isConnected)throw new Error('Native date fields changed');const value=new Date(entered);for(const [input,part]of[[dates.month,String(value.getMonth()+1).padStart(2,'0')],[dates.day,String(value.getDate()).padStart(2,'0')],[dates.year,String(value.getFullYear())]]){setNativeField(window,input,part);input.dispatchEvent(new window.Event('blur',{bubbles:true}));}const b=confirm();if(!b)throw new Error('Native date confirm unavailable');owner.journal.transition(owner.row,'SUBMITTED','Native date confirm intent — result pending');owner.dateConfirm=true;click(b);};
   if(owner)await apply();else await perform('date',null,apply,{timeout:25000});
  }catch(error){say((error.outcome||'BLOCKED')+' • '+error.message);onEvidence({type:'sideline.native-date',intent:'mutation',data:{state:error.outcome||'blocked'}});}finally{expiryActive=false;}
 }
 function waitFor(test,timeout=5000){return new Promise((resolve,reject)=>{let timer;const obs=new window.MutationObserver(check),cancel=()=>done(new Error('Native action disposed'));function done(error,value){obs.disconnect();window.clearTimeout(timer);waits.delete(cancel);error?reject(error):resolve(value);}function check(){if(disposed||!owner||owner.done||owner.stopRequested){done(new Error('Native action cancelled'));return;}const value=test();if(value)done(null,value);}waits.add(cancel);obs.observe(d.body,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','disabled','aria-hidden']});timer=window.setTimeout(()=>done(new Error('Native confirmation unavailable')),timeout);check();});}
 function yesButton(){const dialogs=all('#modal-root,[role=dialog],dialog,.modal,.Dialog,.dialog,.ReactModal__Content,[aria-modal=true]').filter(native);return dialogs.flatMap(dialog=>[...dialog.querySelectorAll('button,[role=button],alchemy-button,mdw-button')]).find(b=>native(b)&&/^(yes|empty)\b/i.test(clean(b.textContent||b.getAttribute('aria-label'))));}
 function refresh(){if(disposed)return;if(!text().match(/(?:expiration|expiry|production) date/)){expirySeen=null;if(expiryActive)expiryController?.abort();}
  if(owner?.kind==='date'&&owner.dateConfirm&&!owner.submittedRequest&&/enter quantity|verify item/.test(text()))finish({outcome:'CONFIRMED',reason:'Native date accepted at quantity/verify step; inventory not submitted'});
  tryQuantity();void nativeExpiry();
 }
 const observer=new window.MutationObserver(records=>{if(records.some(r=>!((r.target.nodeType===1?r.target:r.target.parentElement)?.closest?.('[data-tm-v4-script]'))&&[...r.addedNodes,...r.removedNodes].some(n=>!(n.nodeType===1&&n.matches('[data-tm-v4-script]')))||records.some(r=>r.type!=='childList'&&!((r.target.nodeType===1?r.target:r.target.parentElement)?.closest?.('[data-tm-v4-script]')))))refresh();});observer.observe(d.querySelector('#root,#app')||d.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['disabled','hidden','aria-hidden']});
 function stop(){expiryController?.abort();picker.dispose();if(owner){owner.stopRequested=true;if(owner.row.state==='READING')finish({outcome:'REJECTED',reason:'Stopped before native submission'});else say('SUBMITTED — waiting for native result; no further form writes');}for(const cancel of [...waits])cancel();}
 return{stop,cancelExpiry:()=>{expiryController?.abort();picker.dispose();},quantity:number=>perform('move',number,async()=>refresh()),clear:()=>perform('close',null,async()=>{const change=d.querySelector('#change-container-button')||button(/change container/i);if(!native(change))throw new Error('No current native container');click(change);const yes=await waitFor(yesButton);owner.journal.transition(owner.row,'SUBMITTED','Native clear intent — request pending');click(yes);}),returnSource:async()=>{stop();await Promise.resolve();if(owner||journal().rows.some(r=>['SUBMITTED','UNKNOWN'].includes(r.state)))throw new Error('Native unresolved operation — verify before returning to source');const b=button(/^(back to source|return to source)/i);if(b)click(b);else throw new Error('Native return-to-source unavailable');},refresh,dispose(){if(disposed)return;disposed=true;if(owner&&!owner.done)finish({outcome:owner.row.state==='SUBMITTED'?'UNKNOWN':'REJECTED',reason:'Native helper disposed'});expiryController?.abort();picker.dispose();for(const cancel of [...waits])cancel();observer.disconnect();tap.dispose();status.remove();}};
}
