import{clean,upper,escapeHtml as esc,createReadPool,suspiciousDimensions}from'./ui-tools.mjs';
import{dropzone,DROPZONES}from'./move-container.mjs';
import{createOperationJournal,withOperationLock}from'./operation-journal.mjs';
export function fcskuConflicts(entries){const groups=new Map();for(const e of entries){if(!e.container||!e.fnsku||!e.fcsku)continue;const key=upper(e.container)+'\0'+upper(e.fnsku);if(!groups.has(key))groups.set(key,{fnsku:e.fnsku,fcskus:new Set(),entries:[]});const g=groups.get(key);g.fcskus.add(upper(e.fcsku));g.entries.push(e);}return[...groups.values()].filter(g=>g.fcskus.size>1);}
export function stowInventory(window){const table=window.document?.querySelector('#table-inventory');if(!table)return[];const cols={};for(const [i,th]of[...table.querySelectorAll('thead th')].entries()){const name=clean(th.textContent).replace(/\(.*?\)/g,'').toLowerCase();for(const field of['container','fnsku','fcsku','quantity'])if(name===field||field==='quantity'&&name.startsWith('quantity'))cols[field]=i;}
 if(cols.fnsku===undefined||cols.fcsku===undefined)return[];return[...table.querySelectorAll('tbody tr')].filter(row=>row.cells.length>=Math.max(...Object.values(cols))+1).map(row=>({row,container:clean(row.cells[cols.container]?.textContent)||new window.URL(window.location.href).searchParams.get('s')||'',fnsku:clean(row.cells[cols.fnsku]?.textContent),fcsku:clean(row.cells[cols.fcsku]?.textContent),units:Number(clean(row.cells[cols.quantity]?.textContent).replace(/,/g,''))||0,fnskuCell:row.cells[cols.fnsku],fcskuCell:row.cells[cols.fcsku]}));}
export function createStowHelper({window,reader,operate,print,version,onEvidence=()=>{}}){
 const d=window.document,controller=new window.AbortController(),pool=createReadPool(4);let dataController=new window.AbortController(),lastRows=[];let disposed=false,busy=false,operationController,journal,storageError='',container='',signature='',generation=0,cache=new Map(),hoverSerial=0;
 let prefs={floor:'P2',print:false,qty:2,img:true,imgw:150,title:true,dims:true,weight:true,sortable:true};try{prefs={...prefs,...JSON.parse(window.localStorage.getItem('tm-v4.stow.settings')||'{}')};journal=createOperationJournal({storage:window.localStorage,key:'tm-v4.stow.rows',uuid:()=>window.crypto.randomUUID()});}catch(error){storageError=error.message;}
 if(!['P1','P2','P3','P4'].includes(prefs.floor))prefs.floor='P2';
 const own=(tag,id)=>{const el=d.createElement(tag);el.id=id;el.dataset.tmV4Script='STOW';return el;};
 const style=own('style','tm-v4-stow-style');style.textContent=`#tm-v4-stow-controls{display:inline-flex;align-items:center;flex-wrap:wrap;gap:5px;margin-left:8px;color:#172033;font:12px Arial}#tm-v4-stow-controls button{min-height:24px;padding:4px 8px;border:1px solid #94a3b8;border-radius:7px;background:#fff;font-weight:700;cursor:pointer}#tm-v4-stow-controls button.active{background:#0b74d1;color:#fff}#tm-v4-stow-controls button:disabled{opacity:.55;cursor:wait}#tm-v4-stow-controls.tote{display:flex;margin:0;padding:6px 10px;background:#eef3f8;border-bottom:1px solid #cbd5e1}#tm-v4-stow-controls.tote button{min-height:32px;font-size:13px}#tm-v4-stow-gear{position:fixed;left:16px;bottom:16px;z-index:999998;width:34px;height:34px;border:1px solid #ccd2d8;border-radius:50%;background:white;cursor:pointer}#tm-v4-stow-settings{position:fixed;left:58px;bottom:56px;z-index:1000001;width:260px;padding:10px 14px;background:white;color:#172033;border:1px solid #d9dde1;border-radius:9px;box-shadow:0 8px 25px #0002;font:12px Arial}#tm-v4-stow-settings label{display:flex;align-items:center;gap:6px;margin:5px 0}#tm-v4-stow-settings input[type=number]{width:58px}#tm-v4-stow-status{position:fixed;bottom:55px;left:16px;z-index:1000002;max-width:500px;white-space:pre-wrap;padding:8px;background:#eef3f8;color:#172033;border:1px solid #ccd2d8;border-radius:6px;font:12px Arial}#tm-v4-stow-hover{position:absolute;z-index:999997;pointer-events:none;max-width:540px;padding:8px 10px;background:#161616f0;border-radius:6px;color:#f1f3f5;font:11px Arial}#tm-v4-stow-hover .content{display:flex;gap:10px}#tm-v4-stow-hover img{max-width:180px;max-height:220px;object-fit:contain}#tm-v4-stow-hover .title{max-width:340px;font-size:12px;margin-bottom:5px}#tm-v4-stow-controls .warning{border:2px solid #7f1d1d;border-radius:8px;padding:3px;background:#fff7ed;color:#7f1d1d}#table-inventory tr.tm-v4-stow-suspicious td{background-color:#fef9c3}#table-inventory tr.tm-v4-stow-conflict td{background-image:repeating-linear-gradient(135deg,#7f1d1d2d 0 8px,#f59e0b19 8px 16px);box-shadow:inset 0 2px #7f1d1d,inset 0 -2px #7f1d1d}#table-inventory .tm-v4-stow-conflict-cell{outline:3px solid #7f1d1d;outline-offset:-3px}#tm-v4-stow-hover .suspicious{padding:2px 5px;border:2px solid #f59e0b;background:#fff7ed;color:#111}#tm-v4-stow-hover .sort{padding:2px 6px;border-radius:20px;background:#fde047;color:#111}#tm-v4-stow-hover .sort.no{background:#dc2626;color:#fff}`;
 d.head.append(style);const controls=own('span','tm-v4-stow-controls'),gear=own('button','tm-v4-stow-gear'),settings=own('div','tm-v4-stow-settings'),status=own('div','tm-v4-stow-status'),hover=own('div','tm-v4-stow-hover');gear.type='button';gear.textContent='⚙';gear.title='Stow Andons settings';settings.hidden=true;hover.hidden=true;status.hidden=true;
 settings.innerHTML='<b>Print</b>'+[['print','Print Dropzone Label'],['qty','Quantity'],['img','Show Image'],['imgw','Image Width'],['title','Show Title'],['dims','Show Dimensions'],['weight','Show Weight'],['sortable','Show Sortable']].map(([key,label])=>`<label>${label}<input data-setting="${key}" type="${['qty','imgw'].includes(key)?'number':'checkbox'}" ${key==='qty'?'min="1" max="99"':key==='imgw'?'min="50" max="180"':''}></label>`).join('');
 for(const input of settings.querySelectorAll('input')){const key=input.dataset.setting;if(input.type==='checkbox')input.checked=!!prefs[key];else input.value=String(prefs[key]);}
 d.body.append(gear,settings,status,hover);
 function say(message){if(disposed)return;status.textContent=message;status.hidden=!message;}
 function savePrefs(){try{window.localStorage.setItem('tm-v4.stow.settings',JSON.stringify(prefs));}catch{say('Settings could not be saved');}}
 function currentContainer(){const tote=d.querySelector('#tm-v4-tote [data-container]');const raw=tote?clean(tote.textContent):new window.URL(window.location.href).searchParams.get('s');return/^(?:tsX|csX)[A-Z0-9_-]+$/i.test(raw||'')?raw:'';}
 function focus(){const input=d.querySelector('#tm-v4-tote input')||d.querySelector('#search-input,#searchInput,input[name=s]');if(input&&!input.disabled){input.focus({preventScroll:true});input.select?.();}}
 function renderControls(){const tote=!!d.querySelector('#tm-v4-tote');controls.classList.toggle('tote',tote);controls.innerHTML=`${tote?'<b>MOVE</b>':''}<b>Floor:</b>${['P1','P2','P3','P4'].map(f=>`<button data-floor="${f}" class="${prefs.floor===f?'active':''}">${f}</button>`).join('')} | <b>Drop:</b>${(prefs.floor==='P1'?DROPZONES.p1.filter(x=>x[0]!=='OB IOL'):DROPZONES.upper).map(([label])=>`<button data-drop="${esc(label)}" title="${esc(dropzone(prefs.floor,label))}">${esc(label)}</button>`).join('')}<button data-drop="PRIME">Prime</button> | <button data-unbind>Unbind</button><span data-warning></span>`;for(const b of controls.querySelectorAll('button'))b.disabled=busy||!!storageError;}
 function unresolved(){return journal?.rows.filter(r=>['SUBMITTED','UNKNOWN'].includes(r.state))||[];}
 async function act(mode,destination){if(busy||storageError||!container)return;say('');busy=true;renderControls();operationController=new window.AbortController();let row;
  try{await withOperationLock(window,'tm-v4.stow.owner',async()=>{
   journal=createOperationJournal({storage:window.localStorage,key:'tm-v4.stow.rows',uuid:()=>window.crypto.randomUUID()});if(journal.rows.some(r=>upper(r.container)===upper(container)&&['SUBMITTED','UNKNOWN','QUEUED','READING'].includes(r.state)))throw new Error('Unresolved operation exists for this container — verify native result');
   row=journal.add([container],{mode,destination})[0];journal.transition(row,'READING','Authenticating native worker');say('READING • '+row.container);
   const result=await operate(row,{mode,signal:operationController.signal,checkRunning:()=>{if(disposed)throw new Error('Disposed before submission');},beforeMutation:()=>{if(disposed)throw new Error('Disposed before submission');journal.transition(row,'SUBMITTED','Handed to native worker — verify result');say('SUBMITTED • '+row.container);},onPhase:phase=>say(row.state+' • '+phase)});
   journal.transition(row,'CONFIRMED','Confirmed by '+result.verifiedBy);say('CONFIRMED • '+(mode==='move'?destination:'Unbound')+' • '+row.container);
   if(mode==='move'&&prefs.print){try{await print(destination,prefs.qty);say('CONFIRMED move • Print SUBMITTED; physical output unverified');}catch(error){say('CONFIRMED move • Print UNKNOWN: '+error.message);}}
  });}catch(error){let outcome=row?.state==='SUBMITTED'?'UNKNOWN':'REJECTED';if(error.outcome==='REJECTED')outcome='REJECTED';try{if(row)journal.transition(row,outcome,error.message);}catch{}say(outcome+' • '+error.message);}finally{busy=false;renderControls();onEvidence({type:'stow.handoff',intent:'workflow',data:{mode,state:row?.state||'blocked'}});focus();}
 }
 function product(code){if(!cache.has(code)){const run=generation;const promise=pool(()=>reader.product(code,{signal:dataController.signal}),dataController.signal).then(r=>{if(run!==generation)throw new Error('Stale product result');return r.product;});promise.catch(()=>{});cache.set(code,promise);}return cache.get(code);}
 async function warnings(entries,run){const conflicts=fcskuConflicts(entries);for(const e of entries){e.row.classList.remove('tm-v4-stow-conflict','tm-v4-stow-suspicious');e.fnskuCell.classList.remove('tm-v4-stow-conflict-cell');e.fcskuCell.classList.remove('tm-v4-stow-conflict-cell');}for(const g of conflicts)for(const e of g.entries){e.row.classList.add('tm-v4-stow-conflict');e.fnskuCell.classList.add('tm-v4-stow-conflict-cell');e.fcskuCell.classList.add('tm-v4-stow-conflict-cell');}
  const badge=controls.querySelector('[data-warning]');if(badge){badge.textContent=(conflicts.length?'FCSKU CONFLICT: '+conflicts.length+' • ':'')+'Sussy: checking…';badge.classList.toggle('warning',!!conflicts.length);badge.title=conflicts.map(g=>g.fnsku+': '+[...g.fcskus].join(' + ')).join('\n');}
  let suspect=0,units=0,errors=0;await Promise.all([...new Set(entries.map(e=>e.fnsku))].map(async code=>{try{const p=await product(code);if(run!==generation||disposed)return;if(p&&suspiciousDimensions(p.dimensions))for(const e of entries.filter(e=>e.fnsku===code)){if(e.row.isConnected){e.row.classList.add('tm-v4-stow-suspicious');suspect++;units+=e.units;}}}catch{errors++;}}));
  if(run!==generation||disposed)return;const b=controls.querySelector('[data-warning]');if(b){b.textContent=(conflicts.length?'FCSKU CONFLICT: '+conflicts.length+' • ':'')+`Sussy: ${suspect}/${entries.length}${errors?' • '+errors+' UNKNOWN':''}`;b.title+=(b.title?'\n':'')+units+' suspicious units; '+errors+' unread products';}
 }
 function refresh(){if(disposed)return;const next=currentContainer();if(next!==container){container=next;generation++;cache=new Map();signature='';lastRows=[];dataController.abort();dataController=new window.AbortController();hoverSerial++;hover.hidden=true;}if(!container){controls.remove();return;}
  const tote=d.querySelector('#tm-v4-tote [data-system]');const section=d.querySelector('[data-section-type=inventory]');const heading=section?[...section.querySelectorAll('span,b,h2,h3')].find(el=>clean(el.textContent)==='Inventory'):null;
  if(!controls.isConnected){renderControls();if(tote)tote.prepend(controls);else if(heading)heading.after(controls);}
  if(tote)return;const entries=stowInventory(window),sig=container+'|'+entries.map(e=>e.fnsku+':'+e.fcsku+':'+e.units).join('|');if(sig===signature&&entries.length===lastRows.length&&entries.every((e,i)=>e.row===lastRows[i]))return;signature=sig;lastRows=entries.map(e=>e.row);dataController.abort();dataController=new window.AbortController();cache=new Map();warnings(entries,++generation); // coalesced per native inventory generation
 }
 controls.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;event.preventDefault();event.stopPropagation();if(b.dataset.floor){prefs.floor=b.dataset.floor;savePrefs();renderControls();signature='';refresh();focus();}else if(b.dataset.drop)act('move',dropzone(prefs.floor,b.dataset.drop));else if(b.hasAttribute('data-unbind'))act('unbind','');},{signal:controller.signal});
 gear.addEventListener('click',()=>settings.hidden=!settings.hidden,{signal:controller.signal});settings.addEventListener('change',event=>{const input=event.target,key=input.dataset.setting;if(!key)return;prefs[key]=input.type==='checkbox'?input.checked:Math.max(key==='qty'?1:50,Math.min(key==='qty'?99:180,Number(input.value)|| (key==='qty'?2:150)));input.value=String(prefs[key]);savePrefs();},{signal:controller.signal});
 d.addEventListener('mousedown',event=>{if(event.target!==gear&&!settings.contains(event.target))settings.hidden=true;},{signal:controller.signal});
 const hoverLink=target=>{const link=target.closest?.('#table-inventory a');const entry=stowInventory(window).find(e=>e.fnskuCell.contains(link));return entry&&link?{entry,link}:null;};
 d.addEventListener('mouseover',event=>{const hit=hoverLink(event.target);if(!hit||hit.link.contains(event.relatedTarget))return;const serial=++hoverSerial;hover.style.left=(event.pageX+18)+'px';hover.style.top=(event.pageY+18)+'px';product(hit.entry.fnsku).then(p=>{if(disposed||serial!==hoverSerial||!p)return;const img=/^https?:\/\//i.test(p.img)?p.img:'';hover.innerHTML=`<div class="content">${prefs.img&&img?`<img src="${esc(img)}" style="width:${Math.max(50,Math.min(180,prefs.imgw))}px">`:''}<section>${prefs.title?`<div class="title">${esc(p.title)}</div>`:''}${prefs.dims?`<div class="${suspiciousDimensions(p.dimensions)?'suspicious':''}">Dimensions: ${esc(p.dimensions)}</div>`:''}${prefs.weight?`<div>Weight: ${esc(p.weight)}</div>`:''}${prefs.sortable&&typeof p.sortable==='boolean'?`<div>Sortable: <b class="sort ${p.sortable?'':'no'}">${p.sortable?'TRUE':'FALSE'}</b></div>`:''}</section></div>`;hover.hidden=false;}).catch(error=>{if(serial===hoverSerial)say('Product UNKNOWN • '+error.message);});},{signal:controller.signal});
 d.addEventListener('mouseout',event=>{const hit=hoverLink(event.target);if(hit&&!hit.link.contains(event.relatedTarget)){hoverSerial++;hover.hidden=true;}},{signal:controller.signal});d.addEventListener('mousemove',event=>{if(!hover.hidden){hover.style.left=(event.pageX+18)+'px';hover.style.top=(event.pageY+18)+'px';}},{signal:controller.signal});
 const target=d.querySelector('#tm-v4-tote,#results-content')||d.querySelector('[data-section-type=inventory]')||d.body;const observer=new window.MutationObserver(records=>{if(records.some(r=>{const el=r.target.nodeType===1?r.target:r.target.parentElement;if(el?.closest?.('[data-tm-v4-script=STOW]'))return false;const nodes=[...r.addedNodes,...r.removedNodes];return !nodes.length||nodes.some(n=>!(n.nodeType===1&&n.matches('[data-tm-v4-script=STOW]')));}))refresh();});observer.observe(target,{childList:true,subtree:true,characterData:true});
 renderControls();refresh();if(storageError)say('Recovery blocked: '+storageError);else if(unresolved().length)say('UNKNOWN • '+unresolved().map(r=>r.container+' '+r.mode).join(', ')+' — verify native results before reuse');
 const dispose=()=>{if(disposed)return;disposed=true;try{const r=journal?.rows.find(r=>r.state==='SUBMITTED');if(r)journal.transition(r,'UNKNOWN','Stow disposed after native handoff');}catch{}operationController?.abort();dataController.abort();controller.abort();observer.disconnect();for(const e of[style,controls,gear,settings,status,hover])e.remove();for(const e of stowInventory(window)){e.row.classList.remove('tm-v4-stow-conflict','tm-v4-stow-suspicious');e.fnskuCell.classList.remove('tm-v4-stow-conflict-cell');e.fcskuCell.classList.remove('tm-v4-stow-conflict-cell');}};
 return{dispose,controls,refresh,getRows:()=>journal?.rows||[],act};
}
