import{registerWatermark}from'./watermark.mjs';import{createFcrReader}from'./fcr-read.mjs';import{createGmFetch}from'./gm-fetch.mjs';import{createMoveContainer}from'./move-container.mjs';import{createNativeJson}from'./native-json.mjs';import{createHierarchyDriver}from'./hierarchy-driver.mjs';import{resolveIdentity}from'./identity.mjs';import{createOperationBridge,serveOperationBridge,workerContext}from'./operation-bridge.mjs';import{createStowHelper}from'./stow-runtime.mjs';import{evidence,installRouteLifecycle}from'./ui-tools.mjs';
const VERSION = '0.1.0';
const page=typeof unsafeWindow==='object'?unsafeWindow:window,guard=Symbol.for('tampermonkey.v4.stow.installer');
if(!page[guard]){page[guard]={version:VERSION};const emit=data=>evidence(window,'STOW',VERSION,data);installRouteLifecycle(window,()=>{
 const context=workerContext(window);if(context){
  const mode=location.hostname==='tx-b-hierarchy-nrt.nrt.proxy.amazon.com'?'unbind':location.hostname==='aft-moveapp-nrt-nrt.nrt.proxy.amazon.com'?'move':null;if(!mode)return;
  const identity=()=>resolveIdentity(window,page);let driver;
  if(mode==='unbind')driver=createHierarchyDriver({request:createNativeJson({window,fetch:page.fetch.bind(page),onEvidence:emit}),identity});else{const fetch=createGmFetch(window,GM_xmlhttpRequest),reader=createFcrReader({origin:context.parentOrigin,warehouse:'BWU2',fetch,DOMParser:window.DOMParser,onEvidence:emit});driver=createMoveContainer({window,fetch,reader,identity,onEvidence:emit});}
  const release=registerWatermark(window,'STOW',VERSION),stop=serveOperationBridge({window,mode,driver,identity,onEvidence:emit});return()=>{stop?.();release();};
 }
 const warehouse=location.pathname.match(/^\/([A-Z0-9-]{2,12})\/results(?:\/|$)/)?.[1];if(!warehouse||location.hash.startsWith('#iss-console'))return;
 const reader=createFcrReader({origin:location.origin,warehouse,DOMParser:window.DOMParser,fetch:page.fetch.bind(page),onEvidence:emit});
 const print=(code,qty)=>new Promise((resolve,reject)=>{const hex=[...new TextEncoder().encode(code)].map(b=>b.toString(16).padStart(2,'0')).join('');const url=new URL('http://localhost:5965/printer');const count=Math.min(99,Math.max(1,Math.trunc(qty)||2));for(const [k,v]of Object.entries({action:'print',type:'barcode',data:hex,text:hex,quantity:String(count),desc:'',seq:window.crypto.randomUUID()}))url.searchParams.set(k,v);emit({type:'stow.print',intent:'print',data:{state:'SUBMITTED',quantity:count}});GM_xmlhttpRequest({method:'GET',url:url.href,timeout:15000,onload:r=>r.status>=200&&r.status<300?resolve({outcome:'UNKNOWN'}):reject(new Error('Printer HTTP '+r.status)),onerror:()=>reject(new Error('Printer network outcome unknown')),ontimeout:()=>reject(new Error('Printer timeout outcome unknown'))});});
 const release=registerWatermark(window,'STOW',VERSION),helper=createStowHelper({window,reader,operate:createOperationBridge({window}),print,version:VERSION,onEvidence:emit});return()=>{helper.dispose();release();};
},()=>location.pathname+'|'+(location.hash.startsWith('#iss-console')?'iss':location.hash.startsWith('#fcr-tote-checker')?'tote':location.hash.startsWith('#tm-v4-worker=')?'worker':'native'));}
