V3.boot=()=>{
  const C=V3.core,life=C.lifecycle('fcr'),telemetry=C.telemetry('fcr',V3.build.version),fcr=V3.fcr.create({life,telemetry});
  if(location.origin===V3.measurement.SITE){V3.measurement.native({life});return;}
  if(window.parent!==window)return;
  if(!document.body){life.on(document,'DOMContentLoaded',()=>{life.dispose();V3.boot();},{once:true});return;}
  const current=()=>C.clean(new URL(location.href).searchParams.get('s')||'');
  const print=async(code,title='')=>{
    const value=C.clean(code);if(!value)throw new Error('Barcode required');
    const hex=v=>Array.from(new TextEncoder().encode(String(v??''))).map(b=>b.toString(16).padStart(2,'0')).join('');
    return C.request('http://localhost:5965/printer?action=print&type=barcode&data='+hex(value)+'&text='+hex(value)+'&quantity=1&desc='+hex(C.clean(title))+'&seq='+Date.now(),{timeout:5000,allowHtml:true});
  };

  const currentContainer=()=>C.container(current())?current():'';

  function itemPanel(){
    const panel=C.panel({id:'fcr-item',title:'V3 · FCR Item',width:560,life});let mounted=false;
    return{open(){if(!mounted){mounted=true;const root=document.createElement('div');root.innerHTML='<section class="v3-section"><label class="v3-field">Search code<input data-code></label><div class="v3-row"><button class="v3-btn primary" data-run>LOOKUP</button><button class="v3-btn" data-print>PRINT CODE</button></div><div class="v3-note" data-msg style="margin-top:8px"></div></section><section class="v3-section"><div data-out></div></section>';panel.set(root);const input=root.querySelector('[data-code]'),msg=root.querySelector('[data-msg]'),out=root.querySelector('[data-out]');input.value=current();let last=null;root.querySelector('[data-run]').onclick=async()=>{const code=C.clean(input.value);if(!code)return;msg.textContent='Loading…';try{last=await fcr.product(code);if(!last)throw new Error('Product not found');out.innerHTML='<div class="v3-grid"><div><b>ASIN</b><br>'+C.esc(last.asin||'—')+'</div><div><b>FNSKU</b><br>'+C.esc(last.fnsku||'—')+'</div><div><b>FCSKU</b><br>'+C.esc(last.fcsku||'—')+'</div><div><b>Sortable</b><br>'+C.esc(last.sortableText||'—')+'</div><div><b>Dimensions</b><br>'+C.esc(last.dimensions||'—')+(last.suspicious?' <span class="v3-warn"><b>CHECK</b></span>':'')+'</div><div><b>Weight</b><br>'+C.esc(last.weight||'—')+'</div></div><div style="margin-top:9px"><b>'+C.esc(last.title||'')+'</b></div>';msg.className='v3-note v3-ok';msg.textContent='Ready';}catch(e){msg.className='v3-note v3-bad';msg.textContent=e.message;}};root.querySelector('[data-print]').onclick=async()=>{try{const code=C.clean(input.value),title=last&&[last.asin,last.fnsku,last.fcsku].some(x=>C.upper(x)===C.upper(code))?last.title:'';await print(code,title);msg.textContent='Printed '+code;}catch(e){msg.textContent=e.message;}};}panel.open();}};
  }

  function totePanel(){
    const panel=C.panel({id:'fcr-tote',title:'V3 · Tote Audit',width:760,life});let mounted=false;
    return{open(){if(!mounted){mounted=true;const state={container:'',loading:false,rows:[],lookup:new Map(),pending:[],scans:new Map(),seq:0,message:'Scan source container'};const root=document.createElement('div');root.innerHTML='<section class="v3-section"><div class="v3-note" data-summary>Scan tsX/csX to begin.</div><label class="v3-field">Scanner<input data-scan autocomplete="off"></label><div class="v3-row"><button class="v3-btn" data-reset>NEW TOTE</button></div><div class="v3-note" data-msg></div></section><section class="v3-section"><b>Physical scans</b><div data-scans></div></section><section class="v3-section"><b>System inventory</b><div data-system></div></section>';panel.set(root);const q=s=>root.querySelector(s),scan=q('[data-scan]');
      const lookup=rows=>{const map=new Map();for(const row of rows){row._scan=0;for(const v of [row.asin,row.fnsku,row.fcsku]){const k=C.upper(v);if(!k)continue;if(!map.has(k))map.set(k,[]);map.get(k).push(row);}}return map;};
      const allocate=(rows,n=1)=>{let left=n;for(const row of rows){if(left<=0)break;const room=Math.max(0,Number(row.qty||0)-Number(row._scan||0)),add=Math.min(room,left);row._scan+=add;left-=add;}return left;};
      const match=(product,raw)=>{const keys=[raw,product?.asin,product?.isbn,product?.fnsku,product?.fcsku].map(C.upper).filter(Boolean),seen=new Set(),out=[];for(const key of keys)for(const row of state.lookup.get(key)||[]){const id=[row.container,row.asin,row.fnsku,row.fcsku,row.disposition].join('|');if(!seen.has(id)){seen.add(id);out.push(row);}}return out;};
      const paint=()=>{const total=state.rows.reduce((s,r)=>s+Number(r.qty||0),0),scanned=state.rows.reduce((s,r)=>s+Number(r._scan||0),0);q('[data-summary]').textContent=(state.container||'NO CONTAINER')+' · '+scanned+'/'+total+' units';q('[data-msg]').textContent=state.message;q('[data-scans]').innerHTML=[...state.scans.values()].reverse().map(r=>'<div class="v3-list-row"><button class="v3-btn" data-print="'+C.esc(r.raw)+'">'+C.esc(r.raw)+(r.count>1?' ×'+r.count:'')+'</button> · <b class="'+(r.state==='found'?'v3-ok':r.state==='missing'?'v3-bad':'v3-warn')+'">'+r.state.toUpperCase()+'</b></div>').join('')||'<div class="v3-note">No scans.</div>';q('[data-system]').innerHTML=state.rows.map(r=>'<div class="v3-list-row"><b>'+C.esc(r.fnsku||r.fcsku||r.asin||'—')+'</b> · '+Number(r._scan||0)+'/'+Number(r.qty||0)+' · '+C.esc(r.title||r.asin||'')+'</div>').join('')||'<div class="v3-note">No inventory loaded.</div>';for(const b of q('[data-scans]').querySelectorAll('[data-print]'))b.onclick=async()=>{const rec=state.scans.get(C.upper(b.dataset.print));try{await print(rec.raw,rec.product?.title||'');state.message='Printed '+rec.raw;}catch(e){state.message='Print failed: '+e.message;}paint();};};
      const load=async code=>{const seq=++state.seq;state.container=code;state.loading=true;state.rows=[];state.lookup=new Map();state.pending=[];state.scans.clear();state.message='Loading full inventory…';paint();try{const result=await fcr.inventory(code,{onPreview:p=>{if(seq===state.seq){state.message='Loading inventory page '+p.pages+'…';paint();}}});if(seq!==state.seq)return;state.rows=result.rows;state.lookup=lookup(result.rows);state.loading=false;state.message='Ready';const queued=state.pending.splice(0);paint();for(const v of queued)await handle(v);}catch(e){if(seq===state.seq){state.loading=false;state.message='Inventory failed: '+e.message;paint();}}};
      const handle=async value=>{const raw=C.clean(value);if(!raw)return;if(!state.container){if(!C.container(raw)){state.message='SCAN SOURCE CONTAINER FIRST';paint();return;}return load(raw);}if(C.container(raw)&&C.upper(raw)!==C.upper(state.container))return load(raw);if(state.loading){state.pending.push(raw);state.message='Queued '+state.pending.length+' scan(s)';paint();return;}const key=C.upper(raw),old=state.scans.get(key);if(old){old.count++;allocate(old.matches);state.message=raw+' ×'+old.count;paint();return;}const seq=state.seq;const rec={raw,count:1,state:'checking',matches:[],product:null};state.scans.set(key,rec);paint();try{try{rec.product=await fcr.product(raw);}catch(error){if(!state.lookup.has(key))throw error;}if(seq!==state.seq)return;rec.matches=match(rec.product,raw);rec.state=rec.matches.length?'found':'missing';if(rec.matches.length)allocate(rec.matches);state.message=rec.matches.length?'IN '+state.container:'NOT IN '+state.container;telemetry.emit('tote.scan',{code:C.mask(raw),found:Boolean(rec.matches.length)});}catch(e){if(seq!==state.seq)return;rec.state='error';state.message=e.message;}paint();};
      scan.onkeydown=async e=>{if(e.key!=='Enter')return;e.preventDefault();const v=scan.value;scan.value='';await handle(v);scan.focus({preventScroll:true});};q('[data-reset]').onclick=()=>{state.seq++;Object.assign(state,{container:'',loading:false,rows:[],lookup:new Map(),pending:[],scans:new Map(),message:'Scan source container'});paint();scan.focus();};paint();}panel.open();}};
  }

  function binPanel(){
    const panel=C.panel({id:'fcr-bin',title:'V3 · Bin Check',width:800,life});let mounted=false;
    return{open(){if(!mounted){mounted=true;const state={rows:[],floors:new Map(),filter:new Set(['P2','P3','P4']),message:'Snapshot native inventory when ready.'};const root=document.createElement('div');root.innerHTML='<section class="v3-section"><div class="v3-row"><button class="v3-btn primary" data-load>SNAPSHOT VISIBLE/FILTERED</button><button class="v3-btn" data-copy>COPY VISIBLE TSV</button><button class="v3-btn primary" data-floor="P2">P2</button><button class="v3-btn primary" data-floor="P3">P3</button><button class="v3-btn primary" data-floor="P4">P4</button></div><div class="v3-note" data-msg style="margin-top:8px"></div></section><section class="v3-section"><div data-list></div></section>';panel.set(root);const q=s=>root.querySelector(s);
      const snapshot=()=>{const table=document.querySelector('#table-inventory');if(!table)throw new Error('Native inventory table not ready');const heads=[...table.querySelectorAll('thead th')].map(x=>C.lower(String(x.textContent||'').replace(/\(\d+\)/g,''))),find=(...n)=>heads.findIndex(h=>n.includes(h)),idx={container:find('container'),asin:find('asin'),fnsku:find('fnsku'),fcsku:find('fcsku'),qty:find('quantity','qty')};if(idx.container<0)throw new Error('Container column not found');let nodes=null;try{const jq=globalThis.jQuery||unsafeWindow?.jQuery,dt=jq&&jq.fn?.dataTable?.isDataTable?.(table)?jq(table).DataTable():null;if(dt)nodes=dt.rows({search:'applied'}).nodes().toArray();}catch{}if(!nodes)nodes=[...(table.tBodies?.[0]?.rows||[])].filter(row=>{const r=row.getBoundingClientRect(),s=getComputedStyle(row);return r.height>0&&s.display!=='none'&&s.visibility!=='hidden';});return nodes.map(row=>{const v=i=>i>=0?C.clean(row.cells[i]?.textContent):'';return{container:v(idx.container),asin:v(idx.asin),fnsku:v(idx.fnsku),fcsku:v(idx.fcsku),qty:Number(v(idx.qty).replace(/[^\d.-]/g,''))||0};}).filter(x=>x.container);};
      const visibleRows=()=>state.rows.filter(r=>{const pod=V3.fcr.podOf(r.container),floor=pod?state.floors.get(pod)||'PX':'PX';return !/^P[234]$/.test(floor)||state.filter.has(floor);});
      const paint=()=>{q('[data-msg]').textContent=state.message;for(const b of root.querySelectorAll('[data-floor]'))b.classList.toggle('primary',state.filter.has(b.dataset.floor));q('[data-list]').innerHTML=visibleRows().map((r,i)=>{const pod=V3.fcr.podOf(r.container),floor=pod?state.floors.get(pod)||'…':'—';return'<div class="v3-list-row">'+(i+1)+'. <b>'+C.esc(floor)+'</b> · <button class="v3-btn" data-print="'+C.esc(r.container)+'">'+C.esc(r.container)+'</button> · <button class="v3-btn" data-print="'+C.esc(r.fnsku)+'">'+C.esc(r.fnsku||'—')+'</button> · '+C.esc(r.fcsku||'—')+' · Q'+r.qty+'</div>';}).join('')||'<div class="v3-note">No rows.</div>';for(const b of q('[data-list]').querySelectorAll('[data-print]'))b.onclick=async e=>{if(!e.altKey)return;try{await print(b.dataset.print);state.message='Printed '+b.dataset.print;}catch(err){state.message=err.message;}paint();};};
      q('[data-load]').onclick=async()=>{try{state.rows=snapshot();state.floors.clear();state.message='Resolving '+state.rows.length+' filtered row(s)…';paint();const pods=[...new Set(state.rows.map(r=>V3.fcr.podOf(r.container)).filter(Boolean))];let cursor=0;const worker=async()=>{while(cursor<pods.length){const pod=pods[cursor++];state.floors.set(pod,await fcr.floor(pod));paint();}};await Promise.all(Array.from({length:Math.min(8,pods.length)},worker));state.message='Ready · Alt-click Container/FNSKU to print';paint();}catch(e){state.message=e.message;paint();}};
      for(const b of root.querySelectorAll('[data-floor]'))b.onclick=()=>{state.filter.has(b.dataset.floor)?state.filter.delete(b.dataset.floor):state.filter.add(b.dataset.floor);paint();};
      q('[data-copy]').onclick=()=>{const rows=visibleRows(),text=['Floor\tContainer\tASIN\tFNSKU\tFCSKU\tQty',...rows.map(r=>{const pod=V3.fcr.podOf(r.container),floor=pod?state.floors.get(pod)||'PX':'';return[floor,r.container,r.asin,r.fnsku,r.fcsku,r.qty].join('\t');})].join('\n');if(typeof GM_setClipboard==='function')GM_setClipboard(text,'text');else navigator.clipboard?.writeText(text);state.message='Copied '+rows.length+' visible row(s)';paint();};paint();}panel.open();}};
  }

  function pandashPanel(){
    const panel=C.panel({id:'fcr-pandash',title:'V3 · Pandash',width:480,life});let mounted=false;
    return{open(){if(!mounted){mounted=true;const root=document.createElement('div');root.innerHTML='<section class="v3-section"><label class="v3-field">ASIN<input data-asin></label><button class="v3-btn primary" data-run>CHECK</button><div class="v3-note" data-msg></div></section>';panel.set(root);const input=root.querySelector('[data-asin]'),msg=root.querySelector('[data-msg]');input.value=/^B[A-Z0-9]{9}$/i.test(current())?current():'';root.querySelector('[data-run]').onclick=async()=>{try{let asin=C.upper(input.value);if(!asin){const p=await fcr.product(current());asin=C.upper(p?.asin);input.value=asin;}const x=await fcr.pandash(asin);msg.className='v3-note '+(x.allowed?'v3-ok':'v3-bad');msg.textContent='L'+x.level+' · '+x.message;}catch(e){msg.className='v3-note v3-bad';msg.textContent=e.message;}};}panel.open();}};
  }

  function actionPanel({family,id,title,path,origin,button,fields,prepare}) {
    const panel=C.panel({id,title,width:560,life});let mounted=false,external=null,runContext=null;
    const worker=V3.bridge.client({origin,path,family,life,onEvent:detail=>window.dispatchEvent(new CustomEvent('bwu2-v3:event',{detail}))});
    return{open(){if(!mounted){mounted=true;const root=document.createElement('div');
      root.innerHTML='<section class="v3-section"><label class="v3-field">Container<input data-container></label>'+fields+'<div class="v3-row"><button class="v3-btn primary" data-run>'+button+'</button><button class="v3-btn danger" data-verify hidden>I VERIFIED IT · CLEAR ATTENTION</button></div><div class="v3-note" data-msg></div></section>';
      panel.set(root);const input=root.querySelector('[data-container]'),run=root.querySelector('[data-run]'),verify=root.querySelector('[data-verify]'),msg=root.querySelector('[data-msg]');input.value=currentContainer();
      const key='bwu2.v3.form.fcr.'+family;let busy=false,blocked=localStorage.getItem(key)||'';
      const paint=()=>{run.disabled=busy||Boolean(blocked);verify.hidden=!blocked;for(const field of root.querySelectorAll('input,select'))field.disabled=busy;};
      const payload=prepare?.(root)||(()=>({container:input.value}));
      run.onclick=async()=>{if(busy||blocked)return;let sent=false;busy=true;paint();try{const data=external||payload();external=null;if(!C.container(data.container))throw new Error('Valid container required');
        localStorage.setItem(key,'Unfinished '+button+' · verify '+data.container);sent=true;msg.textContent=button+'…';await worker.run('run',data);msg.textContent=button+' CONFIRMED';localStorage.removeItem(key);
      }catch(error){if(error.outcome==='unknown'){blocked=error.message;localStorage.setItem(key,blocked);}else if(sent)localStorage.removeItem(key);msg.textContent=error.message;}finally{busy=false;paint();}};
      verify.onclick=async()=>{if(busy)return;try{await worker.run('resolve');blocked='';localStorage.removeItem(key);msg.textContent='Attention cleared';paint();}catch(error){msg.textContent=error.message;}};
      runContext=async data=>{if(busy||blocked)return;external=data;await run.onclick();};msg.textContent=blocked?'VERIFY PREVIOUS ACTION · '+blocked:'Ready';paint();}panel.open();},async runContext(data){this.open();await runContext(data);}};
  }
  function movePanel(){return actionPanel({family:'movecontainer',id:'fcr-move',title:'V3 · MoveContainer',path:'/move-container',origin:V3.actions.MOVE_ORIGIN,button:'MOVE',
    fields:'<div class="v3-grid"><label class="v3-field">Floor<select data-floor>'+V3.actions.FLOORS.map(x=>'<option>'+x+'</option>').join('')+'</select></label><label class="v3-field">Destination<select data-drop></select></label></div>',
    prepare:root=>{const floor=root.querySelector('[data-floor]'),drop=root.querySelector('[data-drop]');floor.value='P2';const fill=()=>{drop.innerHTML='<option value="PRIME">PRIME</option>'+V3.actions.dropChoices(floor.value).map(x=>'<option value="'+C.esc(x.key)+'">'+C.esc(x.label)+'</option>').join('');};floor.onchange=fill;fill();return()=>({container:root.querySelector('[data-container]').value,destination:V3.actions.destination(floor.value,drop.value)});}});}
  function unbindPanel(){return actionPanel({family:'hierarchy',id:'fcr-unbind',title:'V3 · Unbind',path:'/unbindHierarchy',origin:V3.actions.HIERARCHY_ORIGIN,button:'UNBIND',fields:''});}

  const tools=[
    ['fcr-item','ITEM','Product / exact print',itemPanel()],
    ['fcr-tote','TOTE','Tote Audit',totePanel()],
    ['fcr-bin','BIN','Bin Check',binPanel()],
    ['fcr-pandash','PANDASH','Pandash',pandashPanel()],
    ['fcr-move','MOVE','MoveContainer',movePanel()],
    ['fcr-unbind','UNBIND','Unbind',unbindPanel()]
  ];
  V3.fcrNative.mount({life,telemetry,fcr,print,move:tools.find(row=>row[0]==='fcr-move')[3],unbind:tools.find(row=>row[0]==='fcr-unbind')[3]});
  for(const [id,label,title,tool] of tools)C.dockButton({id,label,title,onClick:tool.open});
  C.dockButton({id:'fcr-iss',label:'ISS',title:'Open standalone V3 ISS Console',onClick:()=>{const url='https://aft-poirot-website-nrt.nrt.proxy.amazon.com/#iss-console';if(typeof GM_openInTab==='function')GM_openInTab(url,{active:true,insert:true});else window.open(url,'_blank','noopener');}});
};
