V3.boot=()=>{
  const C=V3.core,life=C.lifecycle('river'),telemetry=C.telemetry('river',V3.build.version),store=C.store('river',1);
  const WORKFLOW_Q0='3654ec14-7232-4f65-84c3-87927cdb4d0c',WORKFLOW_ID='0dbb253e-c43a-4a8b-a316-e32b8ab9be21';
  const norm=v=>C.lower(v).replace(/[^a-z0-9]+/g,' ').trim(),code=v=>C.upper(v).replace(/[^A-Z0-9]/g,'');

  const tableHeaders=table=>{const wrapper=table?.closest('.dataTables_wrapper,.dataTables_scroll')||table?.parentElement,head=wrapper?.querySelector('.dataTables_scrollHead table')||table;return[...head?.querySelectorAll('thead th,thead td')||[]].map(x=>norm(x.textContent));};
  const column=(headers,...names)=>headers.findIndex(h=>names.some(n=>h===norm(n)||h.startsWith(norm(n)+' ')));
  const number=value=>{const text=C.clean(value).replace(/,/g,'');if(!/^-?\d+(?:\.\d+)?$/.test(text))return null;const n=Number(text);return Number.isFinite(n)&&n>=0?n:null;};
  const stamp=value=>{const n=Date.parse(C.clean(value));return Number.isFinite(n)?n:Number.NEGATIVE_INFINITY;};
  const vendor=value=>{const tokens=(C.clean(value).match(/[A-Z0-9]+/gi)||[]).map(x=>x.toUpperCase());return tokens.find(x=>x.length>=2&&x.length<=8&&x!=='FBA')||'';};
  const detailMap=doc=>{const table=doc.querySelector('#table-purchase-order'),map=new Map();if(!table)return map;const h=tableHeaders(table),pi=column(h,'purchase order','po'),di=column(h,'placed','confirmed','order date','date');if(pi<0)return map;[...table.querySelectorAll('tbody tr')].forEach((row,index)=>{const cells=[...row.children].filter(x=>x.matches?.('td,th')),po=C.clean(cells[pi]?.textContent);if(!po)return;const time=di>=0?stamp(cells[di]?.textContent):Number.NEGATIVE_INFINITY,old=map.get(code(po));if(!old||time>old.time)map.set(code(po),{po,time,index});});return map;};
  const itemRows=doc=>{const table=doc.querySelector('#table-purchase-order-item');if(!table)return[];const h=tableHeaders(table),i={po:column(h,'purchase order','po'),sku:column(h,'sku','fnsku','asin'),vendor:column(h,'vendor code','seller id'),unfilled:column(h,'unfilled'),cancelled:column(h,'canceled','cancelled'),received:column(h,'received'),title:column(h,'title'),date:column(h,'order date','placed','date')};if(i.po<0||i.sku<0)return[];return[...table.querySelectorAll('tbody tr')].map((row,index)=>{const cells=[...row.children].filter(x=>x.matches?.('td,th')),po=C.clean(cells[i.po]?.textContent);if(!po)return null;return{po,sku:C.clean(cells[i.sku]?.textContent),vendorRaw:i.vendor>=0?C.clean(cells[i.vendor]?.textContent):'',unfilled:i.unfilled>=0?number(cells[i.unfilled]?.textContent):null,cancelled:i.cancelled>=0?number(cells[i.cancelled]?.textContent):null,received:i.received>=0?number(cells[i.received]?.textContent):null,title:i.title>=0?C.clean(cells[i.title]?.textContent):'',time:i.date>=0?stamp(cells[i.date]?.textContent):Number.NEGATIVE_INFINITY,index,rowText:C.clean(row.textContent)};}).filter(Boolean);};
  const selectPo=(itemDoc,detailDoc,identity)=>{
    const rows=itemRows(itemDoc),details=detailMap(detailDoc),wanted=[identity.search,identity.asin,identity.fnsku].map(code).filter(Boolean),candidates=[];
    for(const row of rows){const sku=code(row.sku);let strength=0,matchBy='';if(sku&&wanted.includes(sku)){strength=3;matchBy=sku===code(identity.fnsku)?'fnsku':sku===code(identity.asin)?'asin':'search';}if(!strength)continue;const time=Math.max(row.time,details.get(code(row.po))?.time??Number.NEGATIVE_INFINITY);candidates.push({...row,strength,matchBy,time});}
    if(!candidates.length)return null;candidates.sort((a,b)=>b.time-a.time||b.strength-a.strength||a.index-b.index);const row=candidates[0],parts=[row.unfilled,row.cancelled,row.received],known=parts.every(value=>typeof value==='number'&&Number.isFinite(value)),quantity=known?parts.reduce((sum,v)=>sum+v,0):null;return{purchaseOrder:row.po,vendorCode:vendor(row.vendorRaw)||'N/A',quantity:Number.isFinite(quantity)&&quantity>0?quantity:null,matchBy:row.matchBy,candidateCount:candidates.length};
  };
  const riverUrl=warehouse=>{const u=new URL('https://river.amazon.com/'+encodeURIComponent(warehouse)+'/workflows');u.searchParams.set('buildingType','fc');u.searchParams.set('q0',WORKFLOW_Q0);u.searchParams.set('q1',WORKFLOW_ID);u.searchParams.set('id',WORKFLOW_ID);return u.href;};

  if(location.hostname!=='river.amazon.com'){
    const fcr=V3.fcr.create({life,telemetry}),panel=C.panel({id:'river-capture',title:'V3 · RIVER Capture',width:540,life});let mounted=false,payload=null;
    C.dockButton({id:'river-capture',label:'RIVER',title:'Capture item for RIVER',onClick:()=>{if(!mounted){mounted=true;const root=document.createElement('div');root.innerHTML='<section class="v3-section"><label class="v3-field">Current item<input data-code></label><div class="v3-row"><button class="v3-btn primary" data-cap>CAPTURE</button><button class="v3-btn" data-open>OPEN RIVER</button></div><div class="v3-note" data-msg></div><div data-out></div></section>';panel.set(root);const input=root.querySelector('[data-code]'),msg=root.querySelector('[data-msg]'),out=root.querySelector('[data-out]');input.value=C.clean(new URLSearchParams(location.search).get('s'));const paint=()=>{out.innerHTML=payload?'<div class="v3-grid" style="margin-top:10px"><div><b>FNSKU</b><br>'+C.esc(payload.fnsku)+'</div><div><b>PO</b><br>'+C.esc(payload.purchaseOrder)+'</div><div><b>PO qty</b><br>'+(payload.poLineQuantity??'N/A')+'</div><div><b>LIVE qty</b><br>'+(payload.liveInventoryQuantity??'N/A')+'</div></div>':'';};root.querySelector('[data-cap]').onclick=async()=>{try{const search=C.clean(input.value);if(!search)throw new Error('Search item required');msg.className='v3-note v3-warn';msg.textContent='CAPTURING…';const [product,inventory,itemHtml,poHtml]=await Promise.all([fcr.product(search),fcr.inventory(search),fcr.post('purchase-order-item',{s:search}),fcr.post('purchase-order',{s:search})]);if(!product)throw new Error('Product unavailable');const po=selectPo(C.html(itemHtml),C.html(poHtml),{search,asin:product.asin,fnsku:product.fnsku,title:product.title}),warehouse=V3.fcr.warehouse()||'BWU2';payload={asin:product.asin||'N/A',fnsku:product.fnsku||'N/A',title:product.title||'N/A',purchaseOrder:po?.purchaseOrder||'N/A',vendorCode:po?.vendorCode||'N/A',poLineQuantity:po?.quantity??null,liveInventoryQuantity:inventory.totalQuantity,inventoryCost:product.inventoryCost||'N/A',physicalLocation:'TBD',warehouseId:warehouse,riverUrl:riverUrl(warehouse),capturedAt:Date.now()};payload.quantityDisagreement=Number.isFinite(payload.poLineQuantity)&&Number.isFinite(payload.liveInventoryQuantity)&&payload.poLineQuantity!==payload.liveInventoryQuantity;await store.set('payload',payload);telemetry.emit('river.capture',{po:payload.poLineQuantity,live:payload.liveInventoryQuantity,disagreement:payload.quantityDisagreement,matchBy:po?.matchBy||''});msg.className='v3-note '+(payload.quantityDisagreement?'v3-warn':'v3-ok');msg.textContent=payload.quantityDisagreement?'QTY DISAGREEMENT':'READY';paint();}catch(error){msg.className='v3-note v3-bad';msg.textContent=C.clean(error.message||error);}};root.querySelector('[data-open]').onclick=async()=>{payload=payload||await store.get('payload',null);if(!payload?.riverUrl)return;if(typeof GM_openInTab==='function')GM_openInTab(payload.riverUrl,{active:true,insert:true});else window.open(payload.riverUrl,'_blank','noopener');};}panel.open();}});
    return;
  }

  const panel=C.panel({id:'river-assistant',title:'V3 · RIVER Assistant',width:620,life});let generation=0,watcher=null,severity=null;
  const visible=V3.native.visible;
  const field=aliases=>{const wanted=aliases.map(norm);for(const el of document.querySelectorAll('input,textarea,select')){if(!visible(el))continue;const label=C.clean(el.getAttribute('aria-label')||el.placeholder||el.name||el.id||el.closest('label')?.textContent||'');if(wanted.some(x=>norm(label)===x||norm(label).startsWith(x+' ')))return el;}return null;};
  const nextButton=()=>[...document.querySelectorAll('button,a,[role="button"],input[type="submit"],input[type="button"]')].filter(visible).find(el=>norm(el.innerText||el.textContent||el.value||'')==='next');
  const label=()=>C.clean(document.querySelector('page-info[label]')?.getAttribute('label')||[...document.querySelectorAll('h1,h2,h3,h4,[role="heading"],legend')].find(visible)?.textContent||'');
  const page=()=>{const text=norm(label()),route=(location.pathname+' '+location.search+' '+location.hash).toLowerCase();if(text.includes('information')||field(['physical location of the units','inventory cost per unit']))return'information';if(text.includes('severity')||field(['units impacted']))return'severity';if(text==='asin'||text.includes('enter asin')||field(['type asin here']))return'asin';if(text.includes('pandash')||/pandash|dangerous/.test(route))return'pandash';if(text.includes('sortab')||/sortab/.test(route))return'sortability';if(text.includes('related')||/related.?tt/.test(route))return'related';if(text.includes('image'))return'images';if(text.includes('create issue'))return'create';if(text.includes('issue')&&text.includes('fc'))return'issue';return'unknown';};
  const setValue=async(el,value,run)=>{if(run!==generation||!el||!visible(el)||el.disabled||el.readOnly)return false;let proto=el,setter=null;while((proto=Object.getPrototypeOf(proto))&&!setter)setter=Object.getOwnPropertyDescriptor(proto,'value')?.set||null;if(setter)setter.call(el,String(value??''));else el.value=String(value??'');el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(resolve=>requestAnimationFrame(resolve));return run===generation&&C.clean(el.value)===C.clean(value);};
  const choose=payload=>{const po=payload?.poLineQuantity,live=payload?.liveInventoryQuantity,poOk=Number.isFinite(po)&&po>0,liveOk=Number.isFinite(live)&&live>0;if(poOk&&liveOk&&po!==live)return{value:null,reason:'PO qty '+po+' ≠ live inventory '+live,po,live};if(poOk&&liveOk)return{value:po,reason:'PO/live agree'};if(liveOk)return{value:live,reason:'live inventory only'};if(poOk)return{value:po,reason:'PO only'};return{value:null,reason:'No positive quantity',po:poOk?po:null,live:liveOk?live:null};};
  const arm=previous=>{const runId=generation;watcher?.disconnect();let queued=false;watcher=life.observe(V3.native.root(),records=>{if(runId!==generation)return;if(records.every(record=>record.target.closest?.('[data-bwu2-ui]')))return;if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;if(runId!==generation)return;const current=page();if(current&&current!=='unknown'&&current!==previous){watcher?.disconnect();watcher=null;void run();}});},{childList:true,subtree:true,attributes:true,attributeFilter:['label','disabled','aria-label','data-step']});};

  const render=async(message='')=>{
    const renderId=generation,payload=await store.get('payload',null);if(renderId!==generation)return;const root=document.createElement('div');let chooser='';
    if(severity)chooser='<section class="v3-section"><b>⚠ QUANTITY DISAGREEMENT</b><div class="v3-note v3-warn">'+C.esc(severity.reason)+'</div><div class="v3-grid" style="margin-top:8px">'+(severity.po!=null?'<button class="v3-btn" data-po><b style="font-size:22px">'+severity.po+'</b><br>PO LINE</button>':'')+(severity.live!=null?'<button class="v3-btn" data-live><b style="font-size:22px">'+severity.live+'</b><br>LIVE INVENTORY</button>':'')+'</div><div class="v3-row" style="margin-top:8px"><input class="v3-input" type="number" min="0" data-manual placeholder="Manual qty"><button class="v3-btn" data-apply>APPLY MANUAL</button></div>'+(severity.selected!=null?'<div class="v3-note v3-ok" style="margin-top:8px"><b>FILLED: '+severity.selected+' · '+C.esc(severity.source)+'</b><br>Review RIVER, then click native Next.</div>':'')+'</section>';
    root.innerHTML='<section class="v3-section"><b>RIVER Assistant</b><div class="v3-note">Item: '+C.esc(payload?.fnsku||payload?.asin||'NO CAPTURE')+'</div><div class="v3-note">'+C.esc(message||('Current: '+(label()||page())))+'</div><div class="v3-row" style="margin-top:8px"><button class="v3-btn primary" data-run>RUN</button><button class="v3-btn danger" data-clear>CLEAR</button></div></section>'+chooser;panel.set(root);
    root.querySelector('[data-run]').onclick=run;root.querySelector('[data-clear]').onclick=async()=>{generation++;severity=null;watcher?.disconnect();watcher=null;await store.set('payload',null);render('CLEARED');};
    const apply=async(value,source)=>{const runId=generation,qty=Number(value),units=field(['units impacted','number of units impacted']),shipments=field(['shipments impacted','number of shipments impacted']);if(!Number.isInteger(qty)||qty<0)return render('Enter whole quantity 0+');if(!await setValue(units,qty,runId)||!await setValue(shipments,0,runId)){if(runId===generation)return render('RIVER did not retain quantity');return;}if(runId!==generation)return;severity={...severity,selected:qty,source};telemetry.emit('river.severity.choice',{value:qty,source});await render('Units impacted = '+qty+' ('+source+'). Review RIVER, then click Next.');arm('severity');};
    root.querySelector('[data-po]')?.addEventListener('click',()=>apply(severity.po,'PO'));root.querySelector('[data-live]')?.addEventListener('click',()=>apply(severity.live,'LIVE'));root.querySelector('[data-apply]')?.addEventListener('click',()=>apply(root.querySelector('[data-manual]').value,'MANUAL'));root.querySelector('[data-manual]')?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();void apply(event.currentTarget.value,'MANUAL');}});
  };

  async function run(){
    const runId=++generation;watcher?.disconnect();watcher=null;const payload=await store.get('payload',null);if(runId!==generation)return;if(!payload)return render('No FCR capture');const current=page();telemetry.emit('river.step',{page:current,label:label()});
    if(['pandash','sortability','related','images','issue','create','unknown'].includes(current))return render(current.toUpperCase()+' stays manual — complete/review it, then native Next or RUN');
    if(current==='asin'){if(!await setValue(field(['type asin here','asin']),payload.asin,runId))return render('ASIN field not ready');if(runId!==generation)return;nextButton()?.click();arm('asin');return;}
    if(current==='information'){
      const pairs=[[['x0 asin','fnsku','asin/fnsku'],payload.fnsku],[['purchase order','po'],payload.purchaseOrder],[['vendor code / seller id','vendor code','seller id'],payload.vendorCode],[['inventory cost per unit','inventory cost'],payload.inventoryCost],[['physical location of the units','physical location'],payload.physicalLocation],[['asin title','product title','title'],payload.title]];
      for(const [aliases,value] of pairs){if(runId!==generation)return;const input=field(aliases);if(!input||!await setValue(input,value||'N/A',runId))return render('Information field not ready: '+aliases[0]);}
      if(runId!==generation)return;const next=nextButton();if(!next)return render('Information filled — review and click Next');next.click();arm('information');return;
    }
    if(current==='severity'){
      const choice=choose(payload),shipments=field(['shipments impacted','number of shipments impacted']);
      if(!choice.value){if(shipments)await setValue(shipments,0,runId);if(runId!==generation)return;severity={...choice,selected:null,source:''};return render('Choose Units impacted');}
      severity=null;const units=field(['units impacted','number of units impacted']);if(!await setValue(units,choice.value,runId)||!await setValue(shipments,0,runId))return render('Severity fields not ready');if(runId!==generation)return;const next=nextButton();if(next){next.click();arm('severity');}else render('Severity filled — review and click Next');
    }
  }

  C.dockButton({id:'river',label:'RIVER',title:'V3 RIVER Assistant',onClick:()=>{void render().then(()=>panel.open());}});
};
