V3.boot=()=>{
  const life=V3.lifecycle.create('movecontainer'),telemetry=V3.telemetry.create('movecontainer',V3.build.version),queue=V3.queue.create({name:'movecontainer',life,telemetry});
  const panel=V3.ui.panel({id:'bwu2-v3-movecontainer-panel',title:'V3 · MoveContainer',width:560,life});let busy=false,floor='P2',type='PRIME';
  async function render(){await queue.load();const s=queue.state,root=document.createElement('div'),choices=V3.moveContainer.choices(floor);root.innerHTML='<section class="section"><div class="grid"><label class="field">Floor<select data-floor>'+V3.moveContainer.FLOORS.map(x=>'<option'+(x===floor?' selected':'')+'>'+x+'</option>').join('')+'</select></label><label class="field">Drop<select data-drop>'+choices.map(([n])=>'<option'+(n===type?' selected':'')+'>'+V3.base.esc(n)+'</option>').join('')+'</select></label></div><label class="field">Containers<textarea data-input></textarea></label><div class="row"><button class="btn" data-add>ADD</button><button class="btn primary" data-run>RUN</button><button class="btn" data-pause>PAUSE</button><button class="btn" data-done>CLEAR DONE</button></div><div class="note" style="margin-top:8px">'+V3.base.esc(s.message||'Ready')+'</div></section><section class="section"><div data-list></div></section>';panel.set(root);
    const list=root.querySelector('[data-list]');list.innerHTML=s.items.map(i=>'<div style="padding:6px;border-bottom:1px solid #39475b"><b>'+V3.base.esc(i.id)+'</b> · '+i.status.toUpperCase()+(i.error?' · '+V3.base.esc(i.error):'')+'</div>').join('')||'<div class="note">Queue empty.</div>';
    root.querySelector('[data-floor]').onchange=e=>{floor=e.target.value;type='PRIME';render();};root.querySelector('[data-drop]').onchange=e=>{type=e.target.value;};
    root.querySelector('[data-add]').onclick=async()=>{await queue.add(V3.base.lines(root.querySelector('[data-input]').value));render();};
    root.querySelector('[data-run]').onclick=async()=>{if(s.items.some(i=>i.status==='attention'))return queue.set({message:'Resolve ATTENTION before RUN'}).then(render);await queue.set({running:true,message:'Starting'});render();pump();};
    root.querySelector('[data-pause]').onclick=async()=>{await queue.set({running:false,message:'Pause requested'});render();};
    root.querySelector('[data-done]').onclick=async()=>{await queue.clearDone();render();};
  }
  async function pump(){if(busy||!queue.state.running)return;if(!queue.acquire()){await queue.set({running:false,message:'Queue active in another tab'});return render();}const item=queue.next();if(!item){await queue.set({running:false,current:'',message:'Queue complete'});queue.release();return render();}busy=true;await queue.item(item,{status:'active',error:''});await queue.set({current:item.id,message:'Moving '+item.id});render();try{await V3.moveContainer.move(item.id,V3.moveContainer.destination(floor,type),{telemetry});await queue.item(item,{status:'done'});await queue.set({current:'',message:'MOVED '+item.id});}catch(error){const unknown=error?.outcome==='unknown';await queue.item(item,{status:unknown?'attention':'rejected',error:unknown?'OUTCOME UNKNOWN — VERIFY BEFORE RETRY':String(error.message||error)});await queue.set({running:false,current:'',message:String(error.message||error)});}finally{busy=false;if(!queue.state.running)queue.release();render();}if(queue.state.running)life.timeout(pump,160);}
  V3.ui.dockButton({id:'movecontainer',label:'MOVE CONTAINER',title:'V3 MoveContainer Queue',onClick:()=>{render();panel.open();}});
};