V3.boot=()=>{
  const life=V3.lifecycle.create('fnsku'),telemetry=V3.telemetry.create('fnsku',V3.build.version),panel=V3.ui.panel({id:'bwu2-v3-fnsku',title:'V3 · FNSKU Mapping',width:760,life});
  const HOSTS={na:'fba-fnsku-commingling-console-na.aka.amazon.com',eu:'fba-fnsku-commingling-console-eu.aka.amazon.com',jp:'fba-fnsku-commingling-console-jp.aka.amazon.com'};
  const token=()=>new URL(location.href).searchParams.get('anti-csrftoken-a2z')||document.querySelector('input[name="anti-csrftoken-a2z"]')?.value||'';
  const url=(region,type,{fnsku='',asin=''}={})=>{const u=new URL('/tool/fnsku-mappings-tool/get','https://'+HOSTS[region]);for(const [k,v] of Object.entries({getMappingsType:type,FNSku:'',FNSkus:fnsku?fnsku+'\r\n':'',merchantId:'',MSkus:'',ASIN:asin,includeInactive:'true',includeInternalMerchants:'false',submit:'get',paginationToken:''}))u.searchParams.set(k,v);if(token())u.searchParams.set('anti-csrftoken-a2z',token());return u.toString();};
  const parse=raw=>{const doc=V3.base.html(raw),table=doc.querySelector('#fnsku-table')||doc.querySelector('table.table');if(!table)return[];const trs=[...table.querySelectorAll('tr')];if(trs.length<2)return[];const hs=[...trs[0].querySelectorAll('th,td')].map(x=>V3.base.lower(x.textContent)),idx={merchant:hs.findIndex(x=>/merchant\s*id/.test(x)),msku:hs.findIndex(x=>/msku/.test(x)),fnsku:hs.findIndex(x=>/fnsku/.test(x)),asin:hs.findIndex(x=>/^asin$/.test(x)),condition:hs.findIndex(x=>/condition/.test(x)),status:hs.findIndex(x=>/status/.test(x))};return trs.slice(1).map(tr=>{const c=[...tr.querySelectorAll('td')].map(x=>V3.base.clean(x.textContent)),get=i=>i>=0?c[i]||'':'';return{merchantId:get(idx.merchant),msku:get(idx.msku),fnsku:V3.base.upper(get(idx.fnsku)),asin:V3.base.upper(get(idx.asin)),condition:get(idx.condition),status:get(idx.status)};}).filter(x=>x.fnsku||x.asin);};
  const get=async u=>(await V3.transport.gm(u,{headers:{Accept:'text/html, */*; q=0.01','X-Requested-With':'XMLHttpRequest'},timeout:10000,allowHtml:true})).raw;
  const exactFnsku=async(region,code)=>parse(await get(url(region,'FNSKU_MAPPINGS',{fnsku:code}))).filter(r=>r.fnsku===code);
  const exactAsin=async asin=>parse(await get(url('jp','ASIN_MAPPINGS',{asin}))).filter(r=>r.asin===asin);
  let mounted=false;
  const mount=()=>{if(mounted)return;mounted=true;const root=document.createElement('div');root.innerHTML='<section class="section"><label class="field">FNSKU / ASIN<input data-code></label><button class="btn primary" data-run>LOOKUP</button><div class="note" data-msg style="margin-top:8px"></div></section><section class="section"><div data-result></div></section>';panel.set(root);const input=root.querySelector('[data-code]'),msg=root.querySelector('[data-msg]'),out=root.querySelector('[data-result]');root.querySelector('[data-run]').onclick=async()=>{const code=V3.base.upper(input.value);if(!code)return;msg.textContent='LOOKING…';out.innerHTML='';try{let rows=[],asin='';if(/^B0[A-Z0-9]{8}$/.test(code)){asin=code;rows=await exactAsin(asin);}else{const found=(await Promise.all([exactFnsku('na',code),exactFnsku('eu',code),exactFnsku('jp',code)])).flat();const asins=[...new Set(found.map(x=>x.asin).filter(x=>/^B0[A-Z0-9]{8}$/.test(x)))];if(asins.length!==1)throw new Error(asins.length?'Multiple exact ASINs: '+asins.join(', '):'No exact mapping');asin=asins[0];rows=await exactAsin(asin);}msg.className='note ok';msg.textContent='ASIN '+asin+' · '+rows.length+' JP/AU exact row(s)';out.innerHTML=rows.map(r=>'<div style="padding:6px;border-bottom:1px solid #39475b"><b>'+V3.base.esc(r.fnsku||'—')+'</b> · '+V3.base.esc(r.msku||'—')+' · '+V3.base.esc(r.merchantId||'—')+' · '+V3.base.esc(r.status||'')+'</div>').join('')||'<div class="note">No exact JP/AU rows.</div>';telemetry.emit('lookup',{input:V3.telemetry.mask(code),asin:V3.telemetry.mask(asin),rows:rows.length});}catch(e){msg.className='note bad';msg.textContent=e.message;}};};
  V3.ui.dockButton({id:'fnsku',label:'FNSKU',title:'V3 FNSKU Mapping',onClick:()=>{mount();panel.open();}});
};