import test from'node:test';import assert from'node:assert/strict';import{JSDOM}from'jsdom';import{AFT_MODES,parseAftPage,aftSourceChoices,aftQuantity,createAftClient}from'../aft-client.mjs';
const dom=()=>new JSDOM('<body>',{runScripts:'outside-only',url:'https://aft-qt-nrt.corp.amazon.com/app/edititems'});const html=(id,text)=>`<html><body><script type="a-state">{"instructionId":"EditItems","objectId":"${id}"}</script><h1>${text}</h1></body></html>`;
test('AFT exact native identity excludes hidden/stale step text and rejects wrong instructions',t=>{const d=dom();t.after(()=>d.window.close());const snap=parseAftPage(d.window,html('object-1','Select new inventory state')+'<div hidden>Scan location</div>',AFT_MODES.each);assert.equal(snap.state,'newState');assert.equal(snap.objectId,'object-1');assert.throws(()=>parseAftPage(d.window,html('x','Scan item').replace('EditItems','MoveItems'),AFT_MODES.each),/identity/);});
test('structured owner/state choices retain actual native radio values and distinguish ambiguity',t=>{const d=dom();t.after(()=>d.window.close());const snap=parseAftPage(d.window,html('x','Select source inventory state').replace('</body>','<label><input type="radio" value="opaque-1">Inventory (Quantity: 4) Owner: Retail</label><label><input type="radio" value="opaque-2">Pending Research (Quantity: 2) Owner: Retail</label></body>'),AFT_MODES.sku);assert.deepEqual(aftSourceChoices(snap).map(x=>[x.state,x.qty,x.value]),[['SELLABLE',4,'opaque-1'],['PENDING_RESEARCH',2,'opaque-2']]);});
test('Move quantity fails on Verify, missing/contradictory quantity rather than guessing',()=>{assert.equal(aftQuantity({state:'quantity',text:'Quantity: 12'}),12);assert.throws(()=>aftQuantity({state:'verify',text:'Quantity: 12'}),/Verify/);assert.throws(()=>aftQuantity({state:'quantity',text:'Quantity: 12 Quantity: 2'}),/ambiguous/);});
test('actual client preserves native action payload and requires status rather than an empty 200',async t=>{const d=dom();t.after(()=>d.window.close());const calls=[];const client=createAftClient({window:d.window,fetch:async(path,init)=>{calls.push([path,JSON.parse(init.body)]);return new Response(path==='/status'?' {"status":"READY"} ':'');}});await client.action(AFT_MODES.each,'exact','Input','tsXsource');assert.deepEqual(calls,[['/action',{id:{instructionId:'EditItems',objectId:'exact'},action:'Input',input:'tsXsource'}],['/status',{id:{instructionId:'EditItems',objectId:'exact'}}]]);});
test('AFT malformed/lost status is uncertain; backend ERRORED is a known rejection',async t=>{const d=dom();t.after(()=>d.window.close());for(const status of ['<html>login</html>','{"status":"ERRORED"}','{"status":"COMPLETE"}']){const client=createAftClient({window:d.window,fetch:async path=>new Response(path==='/status'?status:'')});await assert.rejects(client.action(AFT_MODES.each,'exact','Confirm','Confirm'),error=>status.includes('ERRORED')?error.outcome==='REJECTED':error.outcome!=='REJECTED');}});
import{parseAftRows,createAftRunner,AFT_KEY,exactInventoryQuantity}from'../aft-workflow.mjs';import{readFileSync}from'node:fs';
function owned(t){const d=dom();t.after(()=>d.window.close());let busy=false;d.window.navigator.locks={request:async(n,o,work)=>{if(busy)return work(null);busy=true;try{return await work({name:n});}finally{busy=false;}}};return d.window;}
test('EACH retains repeated physical rows; SKU and location queues deduplicate; date collisions fail before calls',()=>{assert.equal(parseAftRows('each','tsX1 B0001 X0001\ntsX1 B0001 X0001').length,2);assert.equal(parseAftRows('sku','X0001\nx0001').length,1);assert.equal(parseAftRows('flip','tsX1 TSX1',{old:'a',newCode:'b'}).length,1);assert.throws(()=>parseAftRows('date','a 2026-10-11\na 2026-10-12',{location:'tsX1'}),/different dates/);assert.throws(()=>parseAftRows('date','a 2026-02-30',{location:'tsX1'}),/calendar/);});
test('AFT lost accepted Confirm stays UNKNOWN across Clear, new Run and reload without a second Confirm',async t=>{const w=owned(t);let step='location',confirms=0;const client={fresh:async()=>({objectId:'o',state:'location'}),wait:async()=>{},page:async()=>({objectId:'o',state:step}),action:async(d,id,name,input)=>{if(name==='Confirm'){confirms++;assert.equal(JSON.parse(w.localStorage.getItem(AFT_KEY)).rows[0].state,'SUBMITTED');throw new Error('lost confirmation');}step=step==='location'?'item':step==='item'?'newState':'confirm';},end:async()=>{throw new Error('must not end unknown');}};const runner=createAftRunner({window:w,client,identity:()=>({})});t.after(runner.dispose);const items=parseAftRows('each','tsX1 B0001');await runner.run(items);assert.equal(runner.rows[0].state,'UNKNOWN');await runner.clear();assert.equal(runner.rows[0].state,'UNKNOWN');await runner.run(items);assert.equal(confirms,1);const restored=createAftRunner({window:w,client,identity:()=>({})});t.after(restored.dispose);assert.equal(restored.rows[0].state,'UNKNOWN');});
test('AFT explicit native success confirms an EACH row; Stop settles Confirm and leaves later rows queued',async t=>{const w=owned(t);let step='location',finish;const client={fresh:async()=>({objectId:'o',state:'location'}),wait:async()=>{},page:async()=>({objectId:'o',state:step}),action:async(d,id,name,input)=>{if(name==='Confirm'){await new Promise(resolve=>finish=resolve);step='success';}else if(name==='Done')step='success';else step=step==='location'?'item':step==='item'?'newState':'confirm';},end:async()=>{}};const runner=createAftRunner({window:w,client,identity:()=>({})});t.after(runner.dispose);const task=runner.run(parseAftRows('each','tsX1 B0001\ntsX2 B0002'));while(!finish)await new Promise(resolve=>setTimeout(resolve,0));runner.stop();assert.equal(runner.rows[0].state,'SUBMITTED');finish();await task;assert.deepEqual(runner.rows.map(row=>row.state),['CONFIRMED','QUEUED']);});
test('exact movement readback cannot accept incomplete or other-container inventory',()=>{assert.equal(exactInventoryQuantity({complete:true,rows:[{container:'tsX1',fnsku:'X1',qty:2}]},'tsX1',['X1']),2);assert.throws(()=>exactInventoryQuantity({complete:false,rows:[]},'tsX1',['X1']),/Complete/);assert.throws(()=>exactInventoryQuantity({complete:true,rows:[{container:'tsX2',qty:2}]},'tsX1',['X1']),/another/);});
test('generated AFT starts at DOM ready with familiar native hosts, scanner focus, one footer and no idle API',async t=>{const w=owned(t);w.document.body.innerHTML='<main>Mode: Each<h1>Scan location</h1></main>';w.unsafeWindow=w;w.fetch=()=>{throw new Error('idle API');};w.GM_xmlhttpRequest=()=>{throw new Error('idle GM');};const source=readFileSync(new URL('../AFT_Edit_SKU_Move.user.js',import.meta.url),'utf8');w.eval(source);w.eval(source);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await new Promise(resolve=>setTimeout(resolve,0));assert.equal(w.document.querySelectorAll('#tm-v4-aft').length,1);assert.match(w.document.querySelector('#tm-v4-runtime-watermark').textContent,/V4 AFT: 0.1.0/);const root=w.document.querySelector('#tm-v4-aft');root.querySelector('[data-min]').click();assert.equal(root.querySelector('.body').hidden,true);w.dispatchEvent(new w.Event('pagehide'));assert.equal(w.document.querySelector('#tm-v4-aft'),null);});
