import test from'node:test';import assert from'node:assert/strict';import{JSDOM}from'jsdom';import{readFileSync}from'node:fs';import{dropzone,createMoveContainer,validateLocation}from'../move-container.mjs';import{createDropzoneQueue}from'../drop-runtime.mjs';import{resolveIdentity}from'../identity.mjs';
const tick=async()=>{for(let i=0;i<8;i++)await new Promise(resolve=>setTimeout(resolve,0));};
const container='tsX111',destination='dz-P-PRIME',location=dest=>({complete:true,rows:[{container,outerLocation:dest}]});
function setup(t){const dom=new JSDOM('<body><main><p>Scan source container</p><input id="native"></main></body>',{url:'https://aft-moveapp-nrt-nrt.nrt.proxy.amazon.com/move-container',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window;w.employeeLogin='makkri';let owned=false;w.navigator.locks={request:async(name,options,work)=>{if(owned)return work(null);owned=true;try{return await work({name});}finally{owned=false;}}};return w;}
test('dropzone codes preserve PRIME, upper Cubiscan and every P1 dedicated choice',()=>{assert.equal(dropzone('','PRIME'),destination);assert.equal(dropzone('P3','Cubiscan'),'dz-Pcubiscan-P3');assert.equal(dropzone('P1','Nonsort'),'dz-P-IB-nonsort');assert.equal(dropzone('P1','Cubiscan'),'');assert.equal(dropzone('P2','Nonsort'),'dz-Pnonsort-P2');});
test('one native move plus exact complete FCR destination readback is required for confirmation',async t=>{const w=setup(t);let reads=0,moves=0,phase='READING';const move=createMoveContainer({window:w,identity:()=>resolveIdentity(w),reader:{inventory:async()=>location(++reads===1?'P-1-A000B000':destination)},fetch:async(url,init)=>{moves++;assert.equal(phase,'SUBMITTED');assert.deepEqual(JSON.parse(init.body),{sourceScannableId:null,destinationScannableId:destination,containerScannableId:container,confirmed:'true'});return new Response('');}});const result=await move({container,destination},{beforeMutation:()=>phase='SUBMITTED',checkRunning(){}});assert.equal(result.verifiedBy,'native-inventory-outerLocation');assert.equal(moves,1);assert.equal(reads,2);});
test('arbitrary 2xx, pending, login and unavailable readback remain UNKNOWN without a second mutation',async t=>{const w=setup(t);for(const response of [new Response('<html>login</html>'),new Response('{"status":"PENDING"}'),new Response('')]){let count=0,reads=0;const move=createMoveContainer({window:w,identity:()=>resolveIdentity(w),reader:{inventory:async()=>++reads===1?location('P-1-A000B000'):location('P-1-A999B000')},fetch:async()=>{count++;return response;}});await assert.rejects(move({container,destination},{beforeMutation(){},checkRunning(){}}),error=>error.outcome==='UNKNOWN');assert.equal(count,1);}});
test('incomplete, empty or wrong exact-container preflight prevents movement',async t=>{const w=setup(t);for(const result of [{complete:false,rows:[]},{complete:true,rows:[]},{complete:true,rows:[{container:'tsX999',outerLocation:'P-1-A000B000'}]}]){let count=0;const move=createMoveContainer({window:w,identity:()=>resolveIdentity(w),reader:{inventory:async()=>result},fetch:async()=>{count++;return new Response('');}});await assert.rejects(move({container,destination},{beforeMutation(){},checkRunning(){}}));assert.equal(count,0);}});
test('queue locks each row destination, quarantines loss through Pause/Clear/reload and never replays',async t=>{const w=setup(t);let count=0;const api=createDropzoneQueue({window:w,identity:()=>resolveIdentity(w),move:async(row,options)=>{options.beforeMutation();count++;throw new Error('lost response');},version:'0.1.0'});t.after(()=>api.dispose());api.root.querySelector('textarea').value=container;await api.run();assert.equal(api.getState()[0].destination,destination);assert.equal(api.getState()[0].state,'UNKNOWN');api.root.querySelector('textarea').value=container;await api.run();assert.equal(count,1);await api.clear();assert.equal(api.getState()[0].state,'UNKNOWN');});
test('CLEAR DONE removes confirmed only, retains rejected and unknown rows',async t=>{const w=setup(t);let count=0;const api=createDropzoneQueue({window:w,identity:()=>resolveIdentity(w),move:async(row,options)=>{options.beforeMutation();if(++count===2)throw new Error('lost');},version:'0.1.0'});t.after(()=>api.dispose());api.root.querySelector('textarea').value='tsX111\ntsX222';await api.run();await api.clear(true);assert.equal(api.getState().length,1);assert.equal(api.getState()[0].state,'UNKNOWN');});
test('native auto-destination emits Enter on one field only and never repeats on unrelated markup',async t=>{const w=setup(t);let enters=0,bodies=0;w.document.querySelector('#native').addEventListener('keydown',event=>{if(event.key==='Enter')enters++;});w.document.body.addEventListener('keydown',event=>{if(event.target===w.document.body)bodies++;});const api=createDropzoneQueue({window:w,identity:()=>resolveIdentity(w),move:async()=>{},version:'0.1.0'});t.after(()=>api.dispose());w.document.dispatchEvent(new w.Event('DOMContentLoaded'));w.document.querySelector('p').textContent='Scan destination container';await tick();assert.equal(enters,1);assert.equal(w.document.querySelector('#native').value,destination);w.document.querySelector('main').append(w.document.createElement('span'));await tick();assert.equal(enters,1);assert.equal(bodies,0);});
test('generated standalone Drop installer has real metadata/footer, consumes queue keys and disposes without traffic',async t=>{const w=setup(t);w.unsafeWindow=w;let calls=0;w.GM_xmlhttpRequest=()=>{calls++;throw new Error('unexpected');};const src=readFileSync(new URL('../Dropzone_Selector_Queue.user.js',import.meta.url),'utf8');w.eval(src);w.eval(src);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await tick();assert.equal(calls,0);assert.equal(w.document.querySelectorAll('#tm-v4-drop').length,1);assert.match(w.document.querySelector('#tm-v4-runtime-watermark').textContent,/V4 DROP: 0.1.0/);let seen=0;w.document.body.addEventListener('keydown',()=>seen++);const input=w.document.querySelector('#tm-v4-drop textarea');input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'a',bubbles:true}));assert.equal(seen,0);w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'=',altKey:true,bubbles:true}));assert.equal(w.document.querySelector('#tm-v4-drop').hidden,true);w.dispatchEvent(new w.Event('pagehide'));assert.equal(w.document.querySelector('#tm-v4-drop'),null);});
