import test from'node:test';import assert from'node:assert/strict';import{JSDOM}from'jsdom';import{readFileSync}from'node:fs';import{mappingUrl,parseMapping,lookupMapping,candidateRank,createMappingTransport,createMappingUI}from'../fnsku-runtime.mjs';
const tick=async()=>{for(let i=0;i<8;i++)await new Promise(resolve=>setTimeout(resolve,0));};
const source={merchantId:'123',msku:'SKU1',fnsku:'X012345678',asin:'B012345678',condition:'New',status:'Active'};
const html=(rows=[source],next=false)=>'<table id="fnsku-table"><tr>'+['Merchant ID','MSKU','FNSKU','ASIN','Condition','Status'].map(label=>'<th>'+label+'</th>').join('')+'</tr>'+rows.map(row=>'<tr>'+Object.values(row).map(value=>'<td>'+value+'</td>').join('')+'</tr>').join('')+'</table>'+(next?'<button>Next &gt;</button>':'');
function setup(t){const dom=new JSDOM('<body><input name="anti-csrftoken-a2z" value="secret-test-token"></body>',{url:'https://fba-fnsku-commingling-console-na.aka.amazon.com/tool/fnsku-mappings-tool',runScripts:'outside-only'});t.after(()=>dom.window.close());return dom.window;}
test('exact native request preserves region, form fields and CRLF scanner code',t=>{const url=new URL(mappingUrl('eu','FNSKU_MAPPINGS',source.fnsku,'secret'));assert.equal(url.hostname,'fba-fnsku-commingling-console-eu.aka.amazon.com');assert.equal(url.searchParams.get('FNSkus'),source.fnsku+'\r\n');assert.equal(url.searchParams.get('includeInactive'),'true');assert.throws(()=>mappingUrl('na','FNSKU_MAPPINGS','123START','secret'));});
test('exact mapping never accepts unrelated/substr FNSKU rows; first-page Next remains partial',t=>{const w=setup(t),result=parseMapping(w,html([source,{...source,fnsku:'X099999999'}],true),'na','FNSKU_MAPPINGS',source.fnsku);assert.equal(result.rows.length,1);assert.equal(result.complete,false);assert.equal(result.hasNext,true);assert.equal(parseMapping(w,html(),'na','FNSKU_MAPPINGS','X012345679').rows.length,0);});
test('login, malformed columns and empty arbitrary pages are errors, not no-mapping claims',t=>{const w=setup(t);for(const text of ['<form><input type=password></form>',html().replace('<th>ASIN</th>','<th>Wrong</th>'),'unexpected blank response'])assert.throws(()=>parseMapping(w,text,'na','FNSKU_MAPPINGS',source.fnsku));});
test('NA/EU exact source maps to JP candidates while failed region remains partial',async t=>{const w=setup(t);const result=await lookupMapping({window:w,code:source.fnsku,token:'secret',read:async url=>{const u=new URL(url);if(u.host.includes('-eu.'))throw new Error('HTTP 401');return html(u.searchParams.get('getMappingsType')==='ASIN_MAPPINGS'?[{...source,fnsku:'X088888888'}]:[source]);}});assert.equal(result.asin,source.asin);assert.equal(result.candidates[0].fnsku,'X088888888');assert.equal(result.partial,true);assert.equal(result.errors.length,1);});
test('multiple exact source ASINs remain ambiguous and do not query JP candidates',async t=>{const w=setup(t);let calls=0;const result=await lookupMapping({window:w,code:source.fnsku,token:'secret',read:async url=>{calls++;return html([{...source,asin:new URL(url).host.includes('-eu.')?'B099999999':source.asin}]);}});assert.equal(result.ambiguous,true);assert.equal(calls,2);assert.equal(result.candidates.length,0);});
test('JP source fallback and direct ASIN keep their proven separate flows',async t=>{const w=setup(t),calls=[];const read=async url=>{calls.push(new URL(url));return html(new URL(url).host.includes('-jp.')?[source]:[]);};const fallback=await lookupMapping({window:w,read,code:source.fnsku,token:'secret'});assert.equal(fallback.sources[0].region,'JP');assert.equal(calls.length,3);calls.length=0;const direct=await lookupMapping({window:w,read,code:source.asin,token:'secret'});assert.equal(calls.length,1);assert.equal(direct.candidates.length,1);});
test('BOTH ranking requires the same source pair; similarity never invents identity',()=>{assert.equal(candidateRank(source,[source]).label,'BOTH');assert.equal(candidateRank(source,[{...source,msku:'OTHER'},{...source,merchantId:'OTHER'}]).label,'MSKU');assert.equal(candidateRank({...source,merchantId:'OTHER',msku:'OTHER'},[source]).label,'—');});
test('GM cancellation aborts one request; redirect/malformed final URL cannot hang',async t=>{const w=setup(t);let options,aborts=0;const read=createMappingTransport(w,o=>{options=o;return{abort:()=>{aborts++;o.onabort();}}});const c=new w.AbortController(),job=read(mappingUrl('na','FNSKU_MAPPINGS',source.fnsku,'secret'),{signal:c.signal});c.abort();await assert.rejects(job,/cancelled/);assert.equal(aborts,1);const second=read(mappingUrl('na','FNSKU_MAPPINGS',source.fnsku,'secret'));options.onload({status:200,responseText:html(),finalUrl:'https://signin.amazon.com/'});await assert.rejects(second,/redirect/);const third=read(mappingUrl('na','FNSKU_MAPPINGS',source.fnsku,'secret'));options.onload({status:200,responseText:html(),finalUrl:'bad url'});await assert.rejects(third,/invalid/);});
test('Clear aborts pending reads; stale response cannot restore results and Debug excludes credentials',async t=>{const w=setup(t),releases=[];const ui=createMappingUI({window:w,read:()=>new Promise(resolve=>releases.push(resolve)),version:'0.1.0',getToken:()=> 'secret-test-token'});t.after(()=>ui.dispose());ui.root.querySelector('input').value=source.fnsku;void ui.lookup();ui.clear();releases.forEach(resolve=>resolve(html()));await tick();assert.equal(ui.getResult(),null);assert.match(ui.root.querySelector('[role=status]').textContent,/Ready/);let copied;w.navigator.clipboard={writeText:async text=>copied=text};ui.root.querySelector('[data-action=debug]').click();await tick();assert(!copied.includes('secret-test-token'));});
test('independent generated installer supports Enter, real footer, minimize, Clear and BFCache cleanup',async t=>{const w=setup(t);let calls=0;w.GM_xmlhttpRequest=options=>{calls++;queueMicrotask(()=>options.onload({status:200,responseText:html([source],true),finalUrl:options.url}));return{abort(){}};};const src=readFileSync(new URL('../FNSKU_Mapping_Lookup.user.js',import.meta.url),'utf8');w.eval(src);w.eval(src);assert.equal(w.document.querySelectorAll('#tm-v4-fnsku').length,1);assert.match(w.document.querySelector('#tm-v4-runtime-watermark').textContent,/V4 FNSKU: 0.1.0/);const input=w.document.querySelector('#tm-v4-fnsku input');input.value=source.asin;input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await tick();assert.equal(calls,1);assert.match(w.document.querySelector('[role=status]').textContent,/PARTIAL/);assert(w.document.querySelector('[data-more-region=jp]'));w.document.querySelector('[data-action=minimize]').click();assert.equal(w.document.querySelector('#tm-v4-fnsku').dataset.minimized,'true');w.dispatchEvent(new w.Event('pagehide'));assert.equal(w.document.querySelector('#tm-v4-fnsku'),null);w.dispatchEvent(new w.PageTransitionEvent('pageshow',{persisted:true}));assert(w.document.querySelector('#tm-v4-fnsku'));});
