import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import {createHierarchyNative} from '../hierarchy-native.mjs';
import {createOperationJournal} from '../operation-journal.mjs';
import {installHierarchy} from '../hierarchy-entry.mjs';

const tick=async()=>{for(let n=0;n<6;n++)await new Promise(resolve=>setTimeout(resolve,0));};
const endpoint=mode=>mode==='bind'?'/forceBind':'/unbindContainer';
const payload=(mode,container='tsXone')=>({sourceWarehouseId:'opaque-source',scannableId:container,employeeLogin:'fixture',...(mode==='bind'?{destinationWarehouseId:'opaque-destination'}:{})});
function setup(t,mode='bind'){
 const w=new JSDOM('<body><label>Destination<input id="destination"></label><label>Container<input id="container"></label>',{url:'https://tx-b-hierarchy-nrt.nrt.proxy.amazon.com/'+mode+'Hierarchy',runScripts:'outside-only'}).window;t.after(()=>w.close());w.employeeLogin='fixture';let owned=false;
 w.navigator.locks={request:async(name,options,work)=>{assert.equal(name,'tm-v4.hierarchy.owner');if(owned)return work(null);owned=true;try{return await work({name});}finally{owned=false;}}};
 return w;
}
function rows(w){return JSON.parse(w.localStorage.getItem('tm-v4.hierarchy.rows')||'{"rows":[]}').rows;}
function unresolved(w,container='tsXone',state='UNKNOWN'){
 const journal=createOperationJournal({storage:w.localStorage,key:'tm-v4.hierarchy.rows',uuid:()=>w.crypto.randomUUID()});const row=journal.add([container],{mode:'bind'})[0];journal.transition(row,'SUBMITTED','prior action');if(state==='UNKNOWN')journal.transition(row,'UNKNOWN','prior unclear action');return row;
}
function mockXhr(w,reply=()=>({status:200,body:{hostName:'native-host'}})){
 const sends=[];
 class Xhr extends w.EventTarget{
  constructor(){super();this.readyState=0;this.status=0;this.responseType='';this.responseText='';this.responseURL='';}
  open(method,url,async=true){this.method=method;this.url=url;this.async=async;this.readyState=1;}
  send(body){sends.push({xhr:this,body});this.readyState=2;queueMicrotask(()=>{if(this.readyState===0)return;const result=reply();if(!result)return;this.status=result.status;this.responseText=JSON.stringify(result.body);this.response=result.body;this.responseURL=new w.URL(this.url,w.location.href).href;this.readyState=4;this.dispatchEvent(new w.Event('load'));this.dispatchEvent(new w.Event('loadend'));});}
  abort(){this.readyState=0;this.status=0;this.dispatchEvent(new w.Event('abort'));this.dispatchEvent(new w.Event('loadend'));}
  getResponseHeader(){return 'application/json';}
 }
 w.XMLHttpRequest=Xhr;return sends;
}

for(const mode of ['bind','unbind'])test('native '+mode+' blocks same-container UNKNOWN and recovered SUBMITTED without a second request',async t=>{
 const w=setup(t,mode);let sends=0;w.fetch=async()=>{sends++;return new Response('{"hostName":"native-host"}');};unresolved(w,'tsXone','SUBMITTED');const native=createHierarchyNative({window:w});t.after(()=>native.dispose());
 await assert.rejects(w.fetch(endpoint(mode),{method:'POST',body:JSON.stringify(payload(mode))}),/unresolved/);assert.equal(sends,0);assert.equal(rows(w)[0].state,'SUBMITTED');assert.equal(rows(w).length,1);
});
for(const mode of ['bind','unbind'])test('manual '+mode+' keeps exact opaque payload and original response, with one durable outcome',async t=>{
 const w=setup(t,mode),body='  '+JSON.stringify(payload(mode))+'  ',events=[];let sends=0;const response=new Response('{"hostName":"native-host"}');w.fetch=async(url,options)=>{sends++;assert.equal(options.body,body);assert.equal(rows(w)[0].state,'SUBMITTED');return response;};const native=createHierarchyNative({window:w,onEvidence:event=>events.push(event)});t.after(()=>native.dispose());
 assert.equal(await w.fetch(endpoint(mode),{method:'POST',body}),response);assert.equal(await response.text(),'{"hostName":"native-host"}');assert.equal(sends,1);assert.equal(rows(w).length,1);assert.equal(rows(w)[0].state,'CONFIRMED');assert.deepEqual(events.map(event=>event.phase),['SUBMITTED','CONFIRMED']);
});
test('native HTTP200 pending response stays UNKNOWN, remains intact for native UI, and cannot repeat',async t=>{
 const w=setup(t);let sends=0;w.fetch=async()=>{sends++;return new Response('{"hostName":"native-host","status":"PENDING"}');};const native=createHierarchyNative({window:w});t.after(()=>native.dispose());const options={method:'POST',body:JSON.stringify(payload('bind'))};const response=await w.fetch('/forceBind',options);assert.equal((await response.json()).status,'PENDING');assert.equal(rows(w)[0].state,'UNKNOWN');await assert.rejects(w.fetch('/forceBind',options),/unresolved/);assert.equal(sends,1);
});
test('native explicit rejection permits later deliberate action; generic HTTP failure does not',async t=>{
 const w=setup(t);let body={success:false,errorMessage:'Rejected'},status=200,sends=0;w.fetch=async()=>{sends++;return new Response(JSON.stringify(body),{status});};const native=createHierarchyNative({window:w});t.after(()=>native.dispose());const options={method:'POST',body:JSON.stringify(payload('bind'))};assert.equal((await w.fetch('/forceBind',options)).status,200);assert.equal(rows(w)[0].state,'REJECTED');body={hostName:'native-host'};await w.fetch('/forceBind',options);assert.equal(rows(w)[1].state,'CONFIRMED');status=500;await w.fetch('/forceBind',options);assert.equal(rows(w)[2].state,'UNKNOWN');await assert.rejects(w.fetch('/forceBind',options),/unresolved/);assert.equal(sends,3);
});
test('unparsed mutation bodies and conflicting identities never pass through or create guessed records',async t=>{
 const w=setup(t);let sends=0;w.fetch=async()=>{sends++;return new Response('{}');};const native=createHierarchyNative({window:w});t.after(()=>native.dispose());for(const body of ['not json','{}',JSON.stringify({...payload('bind'),employeeLogin:'other'})])await assert.rejects(w.fetch('/forceBind',{method:'POST',body}),/unsupported|identity/);assert.equal(sends,0);assert.equal(rows(w).length,0);
});
for(const mode of ['bind','unbind'])test('async native '+mode+' XHR preserves body/events and blocks uncertain repeat',async t=>{
 const w=setup(t,mode),sends=mockXhr(w,()=>({status:200,body:{hostName:'native-host',status:'PENDING'}}));w.fetch=async()=>new Response('{}');const native=createHierarchyNative({window:w});t.after(()=>native.dispose());const body=JSON.stringify(payload(mode));let loads=0,errors=0,ends=0;const first=new w.XMLHttpRequest();first.open('POST',endpoint(mode));first.addEventListener('load',()=>loads++);first.send(body);await tick();assert.equal(sends.length,1);assert.equal(sends[0].body,body);assert.equal(loads,1);assert.equal(rows(w)[0].state,'UNKNOWN');const repeated=new w.XMLHttpRequest();repeated.open('POST',endpoint(mode));repeated.addEventListener('error',()=>errors++);repeated.addEventListener('loadend',()=>ends++);repeated.send(body);await tick();assert.equal(sends.length,1);assert.equal(errors,1);assert.equal(ends,1);
});
test('delayed owner followed by abort or disposal cannot start native hierarchy work',async t=>{
 for(const action of ['abort','dispose']){const w=setup(t);let grant,sends=0;w.navigator.locks.request=(name,options,work)=>new Promise(resolve=>grant=()=>resolve(work({name})));w.fetch=async()=>{sends++;return new Response('{"hostName":"native-host"}');};const native=createHierarchyNative({window:w});const controller=new w.AbortController(),work=w.fetch('/forceBind',{method:'POST',body:JSON.stringify(payload('bind')),signal:controller.signal});const rejected=assert.rejects(work,/cancelled/);if(action==='abort')controller.abort();else native.dispose();grant();await rejected;assert.equal(sends,0);assert.equal(rows(w).length,0);native.dispose();}
});
test('disposal after native submission retains UNKNOWN despite a late positive reply and blocks reload replay',async t=>{
 const w=setup(t);let finish,sends=0;const original=async()=>{sends++;return new Promise(resolve=>finish=resolve);};w.fetch=original;const native=createHierarchyNative({window:w}),options={method:'POST',body:JSON.stringify(payload('bind'))},work=w.fetch('/forceBind',options);const rejected=assert.rejects(work,/cancelled|disposed/);await tick();assert.equal(rows(w)[0].state,'SUBMITTED');native.dispose();await rejected;assert.equal(rows(w)[0].state,'UNKNOWN');finish(new Response('{"hostName":"native-host"}'));await tick();assert.equal(rows(w)[0].state,'UNKNOWN');const reloaded=createHierarchyNative({window:w});t.after(()=>reloaded.dispose());await assert.rejects(w.fetch('/forceBind',options),/unresolved/);assert.equal(sends,1);
});
for(const mode of ['bind','unbind'])test('actual '+mode+' entry shares visible manual records and queue does not double journal its authorised request',async t=>{
 const w=setup(t,mode),calls=[];w.sessionStorage.setItem('tm-v4.hierarchy.template',JSON.stringify({sourceWarehouseId:'opaque-source',destinationWarehouseId:'opaque-destination'}));w.fetch=async(url,options)=>{const path=new w.URL(url,w.location.href).pathname,body=JSON.parse(options.body);calls.push({path,body});return new Response(JSON.stringify(path==='/validateDestination'?'BWU1':path==='/validateContainer'?{warehouseId:'BWU2',scannableId:body.scannableId}:path==='/getTransshipmentBindingSummary'?{transferBindingSummaryList:[]}:{hostName:'native-host'}));};installHierarchy(w,w,mode,'0.1.4');const root=w.document.querySelector('#tm-v4-hierarchy');root.querySelector('textarea').value='tsXqueued';root.querySelector('[data-action=start]').click();await tick();assert.equal(rows(w).length,1);assert.equal(rows(w)[0].state,'CONFIRMED');assert.equal(calls.filter(call=>call.path===endpoint(mode)).length,1);
 await w.fetch(endpoint(mode),{method:'POST',body:JSON.stringify(payload(mode,'tsXmanual'))});assert.equal(rows(w).length,2);assert.equal(rows(w)[1].state,'CONFIRMED');assert.match(root.textContent,/tsXmanual/);assert.match(root.textContent,/2 done/);w.dispatchEvent(new w.Event('pagehide'));
});
test('first Bind native scanner seed keeps its queue owner and one row/operation without manual guard deadlock',async t=>{
 const w=setup(t),calls=[];w.fetch=async(url,options)=>{const path=new w.URL(url,w.location.href).pathname,body=JSON.parse(options.body);calls.push({path,body});return new Response(JSON.stringify(path==='/validateDestination'?'BWU1':path==='/validateContainer'?{warehouseId:'BWU2',scannableId:body.scannableId}:path==='/getTransshipmentBindingSummary'?{transferBindingSummaryList:[]}:{hostName:'native-host'}));};let scans=0;w.document.querySelector('#destination').addEventListener('keydown',event=>{if(event.key==='Enter')void w.fetch('/validateDestination',{method:'POST',body:JSON.stringify({destinationWarehouseId:'opaque-destination'})});});w.document.querySelector('#container').addEventListener('keydown',event=>{if(event.key!=='Enter')return;const container=event.target.value;if(++scans===1){void w.fetch('/validateContainer',{method:'POST',body:JSON.stringify({warehouseId:'BWU2',scannableId:container})});void w.fetch('/getTransshipmentBindingSummary',{method:'POST',body:JSON.stringify({warehouseId:'BWU2',scannableId:container})});}else void w.fetch('/forceBind',{method:'POST',body:JSON.stringify(payload('bind',container))});});installHierarchy(w,w,'bind','0.1.4');const root=w.document.querySelector('#tm-v4-hierarchy');root.querySelector('textarea').value='tsXseed';root.querySelector('[data-action=start]').click();await tick();assert.equal(rows(w).length,1);assert.equal(rows(w)[0].state,'CONFIRMED');assert.equal(calls.filter(call=>call.path==='/forceBind').length,1);assert.equal(calls.length,4);assert.equal(JSON.parse(w.sessionStorage.getItem('tm-v4.hierarchy.template')).destinationWarehouseId,'opaque-destination');w.dispatchEvent(new w.Event('pagehide'));
});
test('native asynchronous XHR success and abort preserve the normal event lifecycle, synchronous mutations are blocked',async t=>{
 const w=setup(t),sends=mockXhr(w);w.fetch=async()=>new Response('{}');const native=createHierarchyNative({window:w});t.after(()=>native.dispose());const first=new w.XMLHttpRequest();first.open('POST','/unbindContainer');let loads=0,ends=0;first.addEventListener('load',()=>loads++);first.addEventListener('loadend',()=>ends++);first.send(JSON.stringify(payload('unbind')));await tick();assert.equal(loads,1);assert.equal(ends,1);assert.equal(rows(w)[0].state,'CONFIRMED');
 const sync=new w.XMLHttpRequest();sync.open('POST','/unbindContainer',false);assert.throws(()=>sync.send(JSON.stringify(payload('unbind','tsXsync'))),/Synchronous/);assert.equal(sends.length,1);
 let grant;w.navigator.locks.request=(name,options,work)=>new Promise(resolve=>grant=()=>resolve(work({name})));const aborted=new w.XMLHttpRequest();aborted.open('POST','/unbindContainer');let abortedEnds=0;aborted.addEventListener('loadend',()=>abortedEnds++);aborted.send(JSON.stringify(payload('unbind','tsXabort')));aborted.abort();grant();await tick();assert.equal(sends.length,1);assert.equal(abortedEnds,1);assert.equal(rows(w).length,1);
});
test('a native call cannot enter an active queue owner or replace its canonical journal during preflight',async t=>{
 const w=setup(t,'unbind');let resolveRead,sends=0;w.fetch=async(url,options)=>{const path=new w.URL(url,w.location.href).pathname,body=JSON.parse(options.body);if(path==='/validateContainer')return new Promise(resolve=>resolveRead=()=>resolve(new Response(JSON.stringify({warehouseId:'BWU2',scannableId:body.scannableId}))));if(path==='/getTransshipmentBindingSummary')return new Response('{"transferBindingSummaryList":[]}');sends++;return new Response('{"hostName":"native-host"}');};installHierarchy(w,w,'unbind','0.1.4');const root=w.document.querySelector('#tm-v4-hierarchy');root.querySelector('textarea').value='tsXqueue';root.querySelector('[data-action=start]').click();await tick();assert.equal(rows(w)[0].state,'READING');await assert.rejects(w.fetch('/unbindContainer',{method:'POST',body:JSON.stringify(payload('unbind','tsXmanual'))}),/owns/);assert.equal(rows(w).length,1);assert.equal(rows(w)[0].state,'READING');resolveRead();await tick();assert.equal(rows(w)[0].state,'CONFIRMED');assert.equal(sends,1);w.dispatchEvent(new w.Event('pagehide'));
});
test('native SUBMITTED stays visible; Clear and Pause retain its final UNKNOWN record for reload',async t=>{
 const w=setup(t,'unbind');let rejectRequest,sends=0;w.fetch=async()=>{sends++;return new Promise((resolve,reject)=>rejectRequest=reject);};installHierarchy(w,w,'unbind','0.1.4');const root=w.document.querySelector('#tm-v4-hierarchy'),work=w.fetch('/unbindContainer',{method:'POST',body:JSON.stringify(payload('unbind'))});const rejected=assert.rejects(work,/failed/);await tick();assert.equal(rows(w)[0].state,'SUBMITTED');assert.match(root.textContent,/SUBMITTED/);root.querySelector('[data-action=pause]').click();root.querySelector('[data-action=clear]').click();await tick();assert.equal(rows(w)[0].state,'SUBMITTED');rejectRequest(new Error('lost response'));await rejected;await tick();assert.equal(rows(w)[0].state,'UNKNOWN');assert.match(root.textContent,/UNKNOWN/);root.querySelector('[data-action=clear]').click();await tick();assert.equal(rows(w)[0].state,'UNKNOWN');assert.equal(rows(w).length,1);await assert.rejects(w.fetch('/unbindContainer',{method:'POST',body:JSON.stringify(payload('unbind'))}),/unresolved/);assert.equal(sends,1);w.dispatchEvent(new w.Event('pagehide'));
});
test('native failure writes its terminal journal while the canonical owner is still held',async t=>{
 const w=setup(t);let owned=false,sends=0;w.navigator.locks.request=async(name,options,work)=>{if(owned)return work(null);owned=true;try{return await work({name});}finally{owned=false;}};w.fetch=async()=>{sends++;throw new Error('lost response');};const events=[];const native=createHierarchyNative({window:w,onEvidence:event=>{events.push(event);if(event.phase==='UNKNOWN')assert.equal(owned,true,'UNKNOWN persisted/evidenced before releasing owner');}});t.after(()=>native.dispose());await assert.rejects(w.fetch('/forceBind',{method:'POST',body:JSON.stringify(payload('bind'))}),/failed/);assert.equal(sends,1);assert.equal(rows(w)[0].state,'UNKNOWN');assert.deepEqual(events.map(event=>event.phase),['SUBMITTED','UNKNOWN']);assert.equal(owned,false);
});
test('reopening an XHR cancels its old waiting send, preserves new request events and sends only the new body',async t=>{
 const w=setup(t),sends=mockXhr(w),grants=[];w.fetch=async()=>new Response('{}');w.navigator.locks.request=(name,options,work)=>new Promise(resolve=>grants.push(()=>resolve(work({name}))));const native=createHierarchyNative({window:w});t.after(()=>native.dispose());const xhr=new w.XMLHttpRequest(),oldBody=JSON.stringify(payload('bind','tsXold')),newBody=JSON.stringify(payload('unbind','tsXnew'));let loads=0,errors=0,ends=0;xhr.addEventListener('load',()=>loads++);xhr.addEventListener('error',()=>errors++);xhr.addEventListener('loadend',()=>ends++);
 xhr.open('POST','/forceBind');xhr.send(oldBody);xhr.open('POST','/unbindContainer');xhr.send(newBody);grants[0]();await tick();assert.equal(sends.length,0,'old lifetime cannot submit through the replacement URL');assert.equal(errors,0,'old lifetime must not dispatch error into the new request');assert.equal(ends,0,'old lifetime must not close the new request');grants[1]();await tick();assert.equal(sends.length,1);assert.equal(sends[0].xhr.url,'/unbindContainer');assert.equal(sends[0].body,newBody);assert.equal(loads,1);assert.equal(ends,1);assert.equal(errors,0);assert.equal(rows(w).length,1);assert.equal(rows(w)[0].container,'tsXnew');assert.equal(rows(w)[0].state,'CONFIRMED');
});
test('a blocked second native click does not turn the live owned SUBMITTED row into UNKNOWN in the queue view',async t=>{
 const w=setup(t,'unbind');let rejectRequest,sends=0;w.fetch=async()=>{sends++;return new Promise((resolve,reject)=>rejectRequest=reject);};installHierarchy(w,w,'unbind','0.1.4');const root=w.document.querySelector('#tm-v4-hierarchy'),work=w.fetch('/unbindContainer',{method:'POST',body:JSON.stringify(payload('unbind','tsXpending'))});const rejected=assert.rejects(work,/failed/);await tick();assert.equal(rows(w)[0].state,'SUBMITTED');assert.equal(root.querySelector('tbody tr').dataset.state,'SUBMITTED');await assert.rejects(w.fetch('/unbindContainer',{method:'POST',body:JSON.stringify(payload('unbind','tsXsecond'))}),/owns/);assert.equal(rows(w)[0].state,'SUBMITTED');assert.equal(root.querySelector('tbody tr').dataset.state,'SUBMITTED','blocked click must preserve the canonical active view');root.querySelector('[data-action=pause]').click();root.querySelector('[data-action=clear]').click();await tick();assert.equal(rows(w)[0].state,'SUBMITTED');assert.equal(root.querySelector('tbody tr').dataset.state,'SUBMITTED');rejectRequest(new Error('lost response'));await rejected;await tick();assert.equal(rows(w)[0].state,'UNKNOWN');assert.equal(root.querySelector('tbody tr').dataset.state,'UNKNOWN');assert.equal(sends,1);w.dispatchEvent(new w.Event('pagehide'));
});
test('XHR reopen after actual submission leaves the old operation UNKNOWN and permits a different new request',async t=>{
 const w=setup(t);let pending=true;const sends=mockXhr(w,()=>pending?null:{status:200,body:{hostName:'native-host'}});w.fetch=async()=>new Response('{}');const native=createHierarchyNative({window:w});t.after(()=>native.dispose());const xhr=new w.XMLHttpRequest();let loads=0,ends=0,errors=0;xhr.addEventListener('load',()=>loads++);xhr.addEventListener('loadend',()=>ends++);xhr.addEventListener('error',()=>errors++);xhr.open('POST','/forceBind');xhr.send(JSON.stringify(payload('bind','tsXsubmitted')));await tick();assert.equal(sends.length,1);assert.equal(rows(w)[0].state,'SUBMITTED');xhr.open('POST','/unbindContainer');await tick();assert.equal(rows(w)[0].state,'UNKNOWN');assert.equal(ends,1);assert.equal(errors,0);pending=false;const newBody=JSON.stringify(payload('unbind','tsXnewafter'));xhr.send(newBody);await tick();assert.equal(sends.length,2);assert.equal(sends[1].body,newBody);assert.deepEqual(rows(w).map(row=>row.state),['UNKNOWN','CONFIRMED']);assert.equal(loads,1);assert.equal(ends,2);assert.equal(errors,0);
});
const workerNonce='12345678-1234-1234-1234-123456789abc',workerParentOrigin='https://fcresearch-fe.aka.amazon.com';
function stowWorkerSetup(t){
 const w=setup(t,'unbind'),messages=[],parent={postMessage:data=>messages.push(data)};Object.defineProperty(w,'parent',{value:parent});w.history.replaceState({},'','/unbindHierarchy?tmV4ParentOrigin='+encodeURIComponent(workerParentOrigin)+'#tm-v4-worker='+workerNonce);w.unsafeWindow=w;w.GM_xmlhttpRequest=()=>{throw new Error('unbind worker must not require GM transport');};
 const run=container=>w.dispatchEvent(new w.MessageEvent('message',{origin:workerParentOrigin,source:parent,data:{protocol:'tm-v4.operation',nonce:workerNonce,type:'run',row:{id:'stow-request',container}}}));
 const loadStow=()=>{w.eval(readFileSync(new URL('../Stow_Andons_Helper.user.js',import.meta.url),'utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));};return{w,messages,run,loadStow};
}
for(const hierarchyFirst of [true,false])test('actual Stow unbind worker and hierarchy entry share one authoritative owner in '+(hierarchyFirst?'hierarchy-first':'Stow-first')+' load order',async t=>{
 const {w,messages,run,loadStow}=stowWorkerSetup(t);let sends=0;w.fetch=async(url,options)=>{const path=new w.URL(url,w.location.href).pathname,body=JSON.parse(options.body);if(path==='/validateContainer')return new Response(JSON.stringify({warehouseId:'BWU2',scannableId:body.scannableId}));if(path==='/getTransshipmentBindingSummary')return new Response('{"transferBindingSummaryList":[]}');sends++;return new Response('{"hostName":"native-host"}');};
 const loadHierarchy=()=>installHierarchy(w,w,'unbind','0.1.4');if(hierarchyFirst){loadHierarchy();loadStow();}else{loadStow();loadHierarchy();}await tick();run('tsXworker');await tick();assert.equal(sends,1,'authorised worker must not be rejected by its own native guard');assert.equal(rows(w).length,1);assert.equal(rows(w)[0].state,'CONFIRMED');assert.equal(messages.find(message=>message.type==='result')?.outcome,'CONFIRMED');assert.equal(w.document.querySelector('#tm-v4-hierarchy'),null,'an explicit owned worker has no standalone queue');assert.doesNotMatch(w.document.querySelector('#tm-v4-runtime-watermark').textContent,/UNBD/);w.dispatchEvent(new w.Event('pagehide'));
});
test('owned Stow unbind worker retains its existing UNKNOWN and cancellation barriers alongside Unbind installer',async t=>{
 const {w,messages,run,loadStow}=stowWorkerSetup(t);let sends=0;w.fetch=async()=>{sends++;return new Response('{}');};unresolved(w,'tsXunknown');installHierarchy(w,w,'unbind','0.1.4');loadStow();await tick();run('tsXunknown');await tick();assert.equal(sends,0);assert.equal(rows(w)[0].state,'UNKNOWN');assert.equal(messages.find(message=>message.type==='result')?.outcome,'REJECTED');w.dispatchEvent(new w.Event('pagehide'));
 const next=stowWorkerSetup(t);let grant,cancelledCalls=0;next.w.navigator.locks.request=(name,options,work)=>new Promise(resolve=>grant=()=>resolve(work({name})));next.w.fetch=async()=>{cancelledCalls++;return new Response('{}');};installHierarchy(next.w,next.w,'unbind','0.1.4');next.loadStow();await tick();next.run('tsXcancelled');next.w.dispatchEvent(new next.w.Event('pagehide'));grant();await tick();assert.equal(cancelledCalls,0);assert.equal(rows(next.w).length,0);
});
test('ordinary native child frames and invalid worker contexts retain the manual UNKNOWN guard',async t=>{
 for(const context of ['ordinary-frame','untrusted-parent','top-tab-worker-looking-url']){
  const w=setup(t,'unbind');if(context!=='top-tab-worker-looking-url')Object.defineProperty(w,'parent',{value:{}});if(context!=='ordinary-frame')w.history.replaceState({},'','/unbindHierarchy?tmV4ParentOrigin='+encodeURIComponent(context==='untrusted-parent'?'https://example.com':workerParentOrigin)+'#tm-v4-worker='+workerNonce);let sends=0;w.fetch=async()=>{sends++;return new Response('{"hostName":"native-host"}');};unresolved(w);installHierarchy(w,w,'unbind','0.1.4');assert(w.document.querySelector('#tm-v4-hierarchy'));await assert.rejects(w.fetch('/unbindContainer',{method:'POST',body:JSON.stringify(payload('unbind'))}),/unresolved/);assert.equal(sends,0);w.dispatchEvent(new w.Event('pagehide'));
 }
});
