import test from'node:test';import assert from'node:assert/strict';import{JSDOM}from'jsdom';import{readFileSync}from'node:fs';import{createScreenshotMode}from'../screenshot-runtime.mjs';
function setup(t){const d=new JSDOM('<html><head><style id="native">input{color:red}</style><style data-tm-v4-style="POP" media="screen">.x{color:blue}</style></head><body><input value="native"><div data-tm-v4-script="POP">PO</div></body></html>',{url:'https://console.harmony.a2z.com/poportal/fe',runScripts:'outside-only'});t.after(()=>d.window.close());return d.window;}
test('Ctrl+Q restores exact style media/native state/focus and handles newly mounted owned styles',async t=>{const w=setup(t),helper=createScreenshotMode(w);t.after(helper.dispose);const native=w.document.querySelector('input');native.focus();w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'q',ctrlKey:true,bubbles:true}));assert.equal(helper.enabled,true);assert.equal(native.value,'native');assert.equal(w.document.activeElement,native);assert.equal(w.document.querySelector('[data-tm-v4-style=POP]').media,'not all');assert.equal(w.document.querySelector('#native').hasAttribute('media'),false);const newStyle=w.document.createElement('style');newStyle.dataset.tmV4Master='';w.document.head.append(newStyle);await new Promise(resolve=>setTimeout(resolve,0));assert.equal(newStyle.media,'not all');w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'q',ctrlKey:true,repeat:true}));assert.equal(helper.enabled,true);helper.dispose();assert.equal(w.document.querySelector('[data-tm-v4-style=POP]').media,'screen');assert.equal(newStyle.hasAttribute('media'),false);assert.equal(w.document.documentElement.hasAttribute('data-tm-v4-screenshot'),false);});
test('generated Screenshot includes PO host, one footer, repeated startup, key toggle and disposal',t=>{const w=setup(t),source=readFileSync(new URL('../Screenshot_Mode.user.js',import.meta.url),'utf8');assert.match(source,/console\\\.harmony\\\.a2z/);w.eval(source);w.eval(source);assert.match(w.document.querySelector('#tm-v4-runtime-watermark').textContent,/V4 SRCS: 0.1.1/);w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Q',ctrlKey:true}));assert.equal(w.document.documentElement.hasAttribute('data-tm-v4-screenshot'),true);w.dispatchEvent(new w.Event('pagehide'));assert.equal(w.document.querySelector('#tm-v4-screenshot-style'),null);});

for(const installer of [false,true])for(const dispose of [false,true])test('Screenshot '+(installer?'installer':'source')+' restores detached style media at '+(dispose?'disposal':'exit'),t=>{
 const w=setup(t);let helper;if(installer)w.eval(readFileSync(new URL('../Screenshot_Mode.user.js',import.meta.url),'utf8'));else helper=createScreenshotMode(w);
 const retained=w.document.querySelector('[data-tm-v4-style=POP]');w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'q',ctrlKey:true}));retained.remove();
 if(dispose){helper?.dispose();w.dispatchEvent(new w.Event('pagehide'));}else w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'q',ctrlKey:true}));
 w.document.head.append(retained);assert.equal(retained.media,'screen');helper?.dispose();w.dispatchEvent(new w.Event('pagehide'));
});
