import test from'node:test';import assert from'node:assert/strict';import{JSDOM}from'jsdom';import{readFileSync}from'node:fs';import{createSidelineNative}from'../sideline-native.mjs';
const tick=async()=>{for(let i=0;i<4;i++)await new Promise(r=>setTimeout(r,0));};
function setup(t,kind){const html=kind==='move'?'<h2>Enter quantity</h2><input id="scan-text-input"><button id="confirm-button">Confirm</button>':'<button id="change-container-button">Change container</button>';const w=new JSDOM('<head></head><body><main>'+html+'</main></body>',{url:'https://aft-poirot-website-nrt.nrt.proxy.amazon.com/',runScripts:'outside-only'}).window;t.after(()=>w.close());w.navigator.locks={request:async(n,o,work)=>work({name:n})};let mutations=0;w.fetch=url=>{mutations++;return Promise.resolve({status:200,url:new w.URL(url,w.location.origin).href,clone:()=>({text:async()=>JSON.stringify({'@type':kind==='move'?'MoveItemsResponse':'CloseContainerResponse',success:true})})});};const submit=()=>w.fetch(kind==='move'?'/api/move-items':'/api/close-container',{method:'POST',body:JSON.stringify({sourceContainerScannableId:'tsXsource',destinationContainerScannableId:'tsXdest',scannableId:'X000000001',quantity:3,containerScannableId:'tsXsource',requestId:'native-one'})});if(kind==='move')w.document.querySelector('button').onclick=submit;else w.document.querySelector('button').onclick=()=>{const dialog=w.document.createElement('div');dialog.setAttribute('role','dialog');dialog.innerHTML='<button>Yes, close</button>';dialog.querySelector('button').onclick=submit;w.document.body.append(dialog);};return{w,mutations:()=>mutations};}
for(const kind of ['move','close'])for(const stage of ['bootstrap','owner'])test('native '+kind+' Stop during '+stage+' submits nothing; late startup cannot revive',async t=>{
 const {w,mutations}=setup(t,kind);let grant,release,bootstrap=0,signal;
 if(stage==='owner')w.navigator.locks.request=(n,o,work)=>new Promise((resolve,reject)=>grant=()=>Promise.resolve(work({name:n})).then(resolve,reject));
 const api=createSidelineNative({window:w,identity:()=>({login:'fixture'}),canAssist:()=>false,client:{bootstrap:options=>{bootstrap++;signal=options?.signal;return stage==='bootstrap'?new Promise(resolve=>release=resolve):Promise.resolve({});}}});t.after(api.dispose);
 const pending=(kind==='move'?api.quantity(3):api.clear()).then(()=>null,error=>error);await tick();api.stop();if(grant)grant();if(release)release({});const error=await pending;assert(error);assert.equal(mutations(),0);assert.equal(w.localStorage.getItem('tm-v4.sideline.rows'),null);if(stage==='owner')assert.equal(bootstrap,0);else assert.equal(signal?.aborted,true);
});
test('native accepted startup rejects a second QTY instead of scheduling a later operation',async t=>{
 const {w,mutations}=setup(t,'move');const releases=[];const api=createSidelineNative({window:w,identity:()=>({}),canAssist:()=>false,client:{bootstrap:()=>new Promise(resolve=>releases.push(resolve))}});t.after(api.dispose);const pending=api.quantity(3).catch(error=>error);await tick();const second=api.quantity(3).catch(error=>error);api.stop();for(const release of releases)release({});const errors=await Promise.all([pending,second]);assert(errors.every(error=>error instanceof Error));assert.match(errors[1].message,/busy/);assert.equal(mutations(),0);
});
for(const close of [false,true])test('generated native QTY delayed bootstrap '+(close?'closure':'Stop')+' does not submit',async t=>{
 const {w}=setup(t,'move');w.unsafeWindow=w;w.employeeLogin='fixture';w.GM_xmlhttpRequest=()=>{throw new Error('No external request');};let release,requests=0;
 w.fetch=(url,options)=>{const path=new w.URL(url).pathname;if(path==='/api/get-bootstrap-data')return new Promise(resolve=>release=()=>resolve({ok:true,status:200,url,headers:{get:()=> 'application/json'},text:async()=>JSON.stringify({warehouseInfo:'BWU2'})}));requests++;throw new Error('Cancelled action');};
 w.eval(readFileSync(new URL('../Sideline_Queue_Lazy.user.js',import.meta.url),'utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await tick();w.document.querySelector('[data-qty="3"]').click();await tick();if(close)w.dispatchEvent(new w.Event('pagehide'));else w.document.querySelector('#tm-v4-side-lazy [data-action=stop]').click();await tick();release();await tick();assert.equal(requests,0);assert.equal(w.localStorage.getItem('tm-v4.sideline.rows'),null);w.dispatchEvent(new w.Event('pagehide'));
});
