import test from'node:test';import assert from'node:assert/strict';import{JSDOM}from'jsdom';import{readFileSync}from'node:fs';import{createSimToolbar}from'../sim-runtime.mjs';
const tick=async()=>{for(let i=0;i<6;i++)await new Promise(r=>setTimeout(r,0));};
async function setup(t,installer,url='https://t.corp.amazon.com/image.png'){const w=new JSDOM('<head></head><body><div><textarea data-testid="sim-markdownEditor--textArea"></textarea></div><ul role="tablist"><li><button role="tab">Audit Trail</button></li></ul><section><h3>Attachments</h3><a href="'+url+'">image.png</a></section></body>',{url:'https://t.corp.amazon.com/test',runScripts:'outside-only'}).window;const handoffs=[];w.URL.createObjectURL=()=> 'blob:valid';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){handoffs.push(this.href);};let helper;if(installer){w.eval(readFileSync(new URL('../SIM_Markdown_Toolbar.user.js',import.meta.url),'utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));await tick();}else helper=createSimToolbar({window:w});const dispose=()=>{helper?.dispose();w.dispatchEvent(new w.Event('pagehide'));};t.after(()=>{dispose();w.close();});return{w,handoffs,dispose,start:()=>w.document.querySelector('.tm-v4-sim-images button:last-child').click()};}
for(const installer of [false,true]){
 const label=installer?'installer':'source';
 test('SIM '+label+' known HTTP/MIME/empty/auth image failures have no raw-link fallback',async t=>{for(const response of [new Response('login',{headers:{'content-type':'text/html'}}),new Response('no',{status:401}),new Response('no',{status:404}),new Response('',{headers:{'content-type':'image/png'}}),new Response('binary',{headers:{'content-type':'application/octet-stream'}})]){const {w,start,handoffs}=await setup(t,installer);w.fetch=async()=>response;start();await tick();assert.deepEqual(handoffs,[]);assert.match(w.document.querySelector('.tm-v4-sim-status').textContent,/0 blob.*0 direct.*1 fetch failure/);}});
 test('SIM '+label+' valid images and transport-only same-origin fallback remain usable',async t=>{const {w,start,handoffs}=await setup(t,installer);w.fetch=async()=>new Response('image',{headers:{'content-type':'image/png'}});start();await tick();assert.deepEqual(handoffs,['blob:valid']);w.fetch=async()=>{throw new TypeError('Network unavailable');};start();await tick();assert.deepEqual(handoffs,['blob:valid','https://t.corp.amazon.com/image.png']);assert.match(w.document.querySelector('.tm-v4-sim-status').textContent,/0 blob.*1 direct.*1 fetch failure/);});
 test('SIM '+label+' cross-origin transport failure or cancelled download produces no direct handoff',async t=>{let app=await setup(t,installer,'https://images.example/image.png');app.w.fetch=async()=>{throw new TypeError('Network unavailable');};app.start();await tick();assert.deepEqual(app.handoffs,[]);app=await setup(t,installer);let reject;app.w.fetch=(_url,{signal})=>new Promise((_resolve,fail)=>{reject=fail;signal.addEventListener('abort',()=>fail(new app.w.DOMException('Cancelled','AbortError')),{once:true});});app.start();await tick();app.dispose();reject(new Error('late'));await tick();assert.deepEqual(app.handoffs,[]);});
}
