import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
const source=file=>readFileSync(new URL('../'+file,import.meta.url),'utf8');
const tick=async()=>{for(let i=0;i<5;i++)await new Promise(resolve=>setTimeout(resolve,0));};
function suite(t){const dom=new JSDOM('<html><head><style id="native-style">input{color:red}</style></head><body><main id="native-fcr"><input value="native"></main></body></html>',{url:'https://fcresearch-fe.aka.amazon.com/BWU2/results?s=B000000001',runScripts:'outside-only'}),w=dom.window;const values=new Map();let requests=0;w.unsafeWindow=w;w.fetch=()=>{requests++;throw new Error('Unexpected idle fetch');};w.GM_xmlhttpRequest=()=>{requests++;throw new Error('Unexpected idle GM');};w.GM_getValue=(key,fallback)=>values.get(key)??fallback;w.GM_setValue=(key,value)=>values.set(key,value);w.GM_addValueChangeListener=()=>1;w.GM_removeValueChangeListener=()=>{};w.GM_registerMenuCommand=()=>1;for(const file of ['FC_Lite.user.js','ISS_Console.user.js','Screenshot_Mode.user.js','diagnostics/FCR_Native_Capture.user.js']){const text=source(file);w.eval(text);w.eval(text);}w.document.dispatchEvent(new w.Event('DOMContentLoaded'));t.after(()=>{w.dispatchEvent(new w.Event('pagehide'));w.close();});return{w,requests:()=>requests};}
const entries=w=>[...w.document.querySelectorAll('[data-tm-v4-runtime]')].map(node=>[node.dataset.tmV4Runtime,node.dataset.tmV4Version]);
test('independent generated installers share one truthful footer across FCR/ISS routes, exclude inactive Tote and make zero idle requests',async t=>{const {w,requests}=suite(t);await tick();assert.equal(w.document.querySelectorAll('#tm-v4-runtime-watermark').length,1);assert.deepEqual(entries(w),[['FCAP','0.1.1'],['SRCS','0.1.0'],['TOTE','0.1.1']]);w.location.hash='#iss-console';w.dispatchEvent(new w.Event('hashchange'));await tick();assert.deepEqual(entries(w),[['FCAP','0.1.1'],['ISSC','0.1.1'],['SRCS','0.1.0']]);assert.equal(w.document.querySelectorAll('#tm-v4-iss').length,1);assert.equal(w.document.querySelector('iframe'),null);w.location.hash='';w.dispatchEvent(new w.Event('hashchange'));await tick();assert.equal(w.document.querySelector('#tm-v4-iss'),null);assert.deepEqual(entries(w),[['FCAP','0.1.1'],['SRCS','0.1.0'],['TOTE','0.1.1']]);assert.equal(requests(),0);assert.equal(w.document.querySelector('#native-fcr input').value,'native');});
test('real Screenshot Ctrl+Q hides shared runtime/UI and restores native focus/styles; BFCache restores exactly one active entry per installer',async t=>{const {w,requests}=suite(t);await tick();const native=w.document.querySelector('#native-fcr input');native.focus();native.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Q',ctrlKey:true,bubbles:true,cancelable:true}));assert.equal(w.getComputedStyle(w.document.querySelector('#tm-v4-runtime-watermark')).display,'none');assert.equal(w.document.querySelector('#native-style').hasAttribute('media'),false);assert.equal(w.document.activeElement,native);assert.equal(native.value,'native');native.dispatchEvent(new w.KeyboardEvent('keydown',{key:'q',ctrlKey:true,bubbles:true,cancelable:true}));assert.notEqual(w.getComputedStyle(w.document.querySelector('#tm-v4-runtime-watermark')).display,'none');w.dispatchEvent(new w.Event('pagehide'));assert.equal(w.document.querySelector('#tm-v4-runtime-watermark'),null);w.dispatchEvent(new w.PageTransitionEvent('pageshow',{persisted:true}));await tick();assert.deepEqual(entries(w),[['FCAP','0.1.1'],['SRCS','0.1.0'],['TOTE','0.1.1']]);assert.equal(w.document.querySelectorAll('#tm-v4-screenshot-style').length,1);assert.equal(requests(),0);});
