import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM}from'jsdom';import{readFileSync}from'node:fs';import{createToteAudit}from'../tote-runtime.mjs';
const tick=async()=>{for(let i=0;i<12;i++)await new Promise(resolve=>setTimeout(resolve,0));};
const row={container:'tsX111',asin:'B012345678',fnsku:'X012345678',fcsku:'ZZ12345678',lpn:'LPN123',qty:2,disposition:'SELLABLE',consumer:'STOW',consumerId:'operator',outerLocation:'P-1-A001',outerLocationType:'BIN',title:'Test'};
const product={...row,primary:row.asin,aliases:[row.asin,row.fnsku,row.fcsku],dimensions:'1 x 2 x 3',weight:'1 kg',sortable:true};
function setup(t,{inventory=async()=>({complete:true,rows:[{...row}]}),lookup=async()=>({product}),enrichment}={}){
 const dom=new JSDOM('<head></head><body><div id="native"></div></body>',{url:'https://fcresearch-fe.aka.amazon.com/BWU2/results#fcr-tote-checker'}),w=dom.window;
 const calls=[];const reader={inventory:async(...args)=>{calls.push(args[0]);return inventory(...args);},product:lookup,barcodeProduct:lookup};
 const api=createToteAudit({window:w,reader,enrichment:enrichment||{hazmat:async()=>({hazmat:{level:0}}),binDescription:async()=>({size:'SMALL'}),recentMadcat:async()=>({madcat:false,madcatSource:'raw'})},warehouse:'BWU2',version:'0.1.0',fetch:async()=>new Response('')});
 t.after(()=>{api.dispose();dom.window.close();});return{api,w,calls};
}
test('scanner loads a tote; all twelve native columns and physical counts are retained',async t=>{const{api}=setup(t);api.scan('tsX111');await tick();api.scan(row.fnsku);api.scan(row.fnsku);await tick();assert.equal(api.getState().entries.length,1);assert.equal(api.getState().entries[0].count,2);assert.equal(api.getState().inventory[0].physical,2);assert.equal(api.root.querySelectorAll('[data-system] th').length,12);assert.match(api.root.querySelector('[data-summary]').textContent,/COMPLETE/);});
test('queued fast scans survive inventory failure and deliberate retry',async t=>{let release,failed=true;const{api,w}=setup(t,{inventory:()=>new Promise((resolve,reject)=>{release=()=>failed?reject(new Error('timeout')):resolve({complete:true,rows:[row]});})});api.scan('tsX111');api.scan(row.fnsku);api.scan(row.fnsku);release();await tick();assert.equal(api.getState().pending.length,2);assert.equal(api.getState().entries.length,0);failed=false;api.root.querySelector('[data-action=retry]').click();release();await tick();assert.equal(api.getState().pending.length,0);assert.equal(api.getState().entries[0].count,2);assert.equal(w.document.activeElement,api.root.querySelector('input'));});
test('strict internal codes never broaden through a shared ASIN',async t=>{const{api}=setup(t,{lookup:async()=>({product:{...product,fnsku:'X099999999',aliases:[row.asin,'X099999999']}})});api.scan('tsX111');await tick();api.scan('X099999999');await tick();assert.equal(api.getState().entries[0].state,'OUT');assert.equal(api.getState().inventory[0].physical,0);});
test('same tote finishes; next tote resets; reset stops stale inventory from reviving',async t=>{let release;const{api}=setup(t,{inventory:()=>new Promise(resolve=>release=resolve)});api.scan('tsX111');api.scan(row.fnsku);api.scan('tsX111');release({complete:true,rows:[row]});await tick();assert.equal(api.getState().done,true);assert.equal(api.getState().entries.length,1);api.scan(row.fnsku);assert.equal(api.getState().entries[0].count,1);api.scan('csX222');api.reset();release({complete:true,rows:[row]});await tick();assert.equal(api.getState(),null);assert.match(api.root.textContent,/No container loaded/);});
test('partial and foreign-container inventories block IN/OUT claims and retain queued scans',async t=>{for(const result of [{complete:false,rows:[row]},{complete:true,rows:[{...row,container:'tsX999'}]}]){const{api}=setup(t,{inventory:async()=>result});api.scan('tsX111');api.scan(row.fnsku);await tick();assert.equal(api.getState().inventoryState,'ERROR');assert.equal(api.getState().entries.length,0);assert.equal(api.getState().pending.length,1);}});
test('duplicate units allocate across all records without exceeding native counts; excess stays visible',async t=>{const{api}=setup(t,{inventory:async()=>({complete:true,rows:[{...row,qty:1},{...row,qty:2,disposition:'DEFECTIVE'}]})});api.scan('tsX111');await tick();for(let i=0;i<4;i++)api.scan(row.fnsku);await tick();assert.deepEqual(api.getState().inventory.map(row=>row.physical),[1,2]);assert.match(api.root.querySelector('[data-physical]').textContent,/EXTRA 1/);});
test('native Enter scanning does not require mouse run; DOM injection is escaped',async t=>{const{api,w}=setup(t,{lookup:async()=>({product:{...product,dimensions:'<img src=x onerror=evil()>'}})});const input=api.root.querySelector('input');input.value='tsX111';input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await tick();input.value=row.fnsku;input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await tick();assert.equal(api.getState().entries.length,1);assert.equal(api.root.querySelector('[onerror]'),null);});
test('MADCAT failure remains visibly retryable, never becomes NO',async t=>{const{api}=setup(t,{enrichment:{hazmat:async()=>({hazmat:null}),binDescription:async()=>({size:''}),recentMadcat:async()=>{throw new Error('auth failed');}}});api.scan('tsX111');await tick();api.scan(row.fnsku);await tick();assert.equal(api.getState().entries[0].madcat,'ERROR ↻');});
test('generated installer runs independently, registers only its active route and cleans up',async t=>{const dom=new JSDOM('<body><div data-section-type="product"><table><tr><th>Dimensions</th><td>1x2x3</td></tr></table></div></body>',{url:'https://fcresearch-fe.aka.amazon.com/BWU2/results?s=B012345678',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window;w.unsafeWindow=w;let requests=0;w.fetch=async()=>{requests++;throw new Error('unexpected');};const store=new Map();w.GM_getValue=(key,fallback)=>store.get(key)??fallback;w.GM_setValue=(key,value)=>store.set(key,value);w.GM_addValueChangeListener=()=>1;w.GM_removeValueChangeListener=()=>{};w.GM_xmlhttpRequest=()=>{throw new Error('unexpected');};w.eval(readFileSync(new URL('../FC_Lite.user.js',import.meta.url),'utf8'));assert.match(w.document.querySelector('#tm-v4-runtime-watermark').textContent,/V4 TOTE: 0.1.4/);assert.equal(requests,0);w.location.hash='#iss-console';w.dispatchEvent(new w.Event('hashchange'));assert.equal(w.document.querySelector('#tm-v4-runtime-watermark'),null);});

test('exact FNSKU/ASIN physical entries share complete bin and Measurement reads; manual refresh bypasses',async t=>{
 let bins=0,measurements=0,products=0;const{api}=setup(t,{lookup:async()=>{products++;return{product};},enrichment:{hazmat:async()=>({hazmat:{level:0}}),binDescription:async()=>{bins++;return{size:'SMALL',matched:row.fnsku,complete:true};},recentMadcat:async()=>{measurements++;return{madcat:false,madcatSource:'raw',complete:true};}}});api.scan('tsX111');await tick();api.scan(row.fnsku);api.scan(row.asin);await tick();assert.equal(bins,1);assert.equal(measurements,1);assert.equal(products,2);assert.equal(api.getState().entries.length,2);assert.equal(api.getState().inventory[0].physical,2);api.root.querySelector('[data-madcat]').click();await tick();assert.equal(measurements,2);
});
test('distinct FNSKUs with a shared ASIN never share exact-item enrichment',async t=>{
 let bins=0,measurements=0;const other={...row,fnsku:'X099999999',fcsku:'ZZ99999999'};const{api}=setup(t,{inventory:async()=>({complete:true,rows:[row,other]}),lookup:async code=>{const chosen=code===other.fnsku?other:row;return{product:{...product,...chosen,aliases:[chosen.asin,chosen.fnsku,chosen.fcsku]}};},enrichment:{hazmat:async()=>({hazmat:null}),binDescription:async()=>{bins++;return{size:'SMALL',complete:true};},recentMadcat:async()=>{measurements++;return{madcat:true,madcatSource:'raw',complete:true};}}});api.scan('tsX111');await tick();api.scan(row.fnsku);api.scan(other.fnsku);await tick();assert.equal(bins,2);assert.equal(measurements,2);assert.equal(api.getState().entries.length,2);
});
test('incomplete/negative bin and unverified Measurement results are not retained for later compatible scans',async t=>{
 let bins=0,measurements=0;const{api}=setup(t,{enrichment:{hazmat:async()=>({hazmat:null}),binDescription:async()=>++bins===1?{size:'',complete:false}:{size:'SMALL',complete:true},recentMadcat:async()=>++measurements===1?{madcat:null,madcatSource:'history',complete:false}:{madcat:true,madcatSource:'raw',complete:true}}});api.scan('tsX111');await tick();api.scan(row.fnsku);await tick();api.scan(row.asin);await tick();assert.equal(bins,2);assert.equal(measurements,2);assert.equal(api.getState().entries[0].madcat,'UNKNOWN');assert.equal(api.getState().entries[1].madcat,'YES');
});
test('manual Measurement refresh supersedes a pending shared read and later scans join the new result',async t=>{
 const releases=[];let bins=0;const{api}=setup(t,{enrichment:{hazmat:async()=>({hazmat:null}),binDescription:async()=>{bins++;return{size:'SMALL',complete:true};},recentMadcat:()=>new Promise(resolve=>releases.push(resolve))}});api.scan('tsX111');await tick();api.scan(row.fnsku);await tick();api.root.querySelector('[data-madcat]').click();await tick();api.scan(row.asin);await tick();const reads=releases.length;for(const release of releases)release({madcat:false,madcatSource:'raw',complete:true});await tick();assert.equal(reads,2);assert.equal(bins,1);assert(api.getState().entries.every(entry=>entry.madcat==='NO'));
});
test('Tote reset/new container never reuses old enrichment and late results cannot revive old entries',async t=>{
 let binReads=0,measureReads=0;const releases=[];const{api}=setup(t,{inventory:async code=>({complete:true,rows:[{...row,container:code}]}),enrichment:{hazmat:async()=>({hazmat:null}),binDescription:async()=>({size:'BIN'+(++binReads),complete:true}),recentMadcat:()=>{measureReads++;return new Promise(resolve=>releases.push(resolve));}}});api.scan('tsX111');await tick();api.scan(row.fnsku);await tick();api.reset();api.scan('csX222');await tick();api.scan(row.fnsku);await tick();releases[1]({madcat:false,madcatSource:'raw',complete:true});releases[0]({madcat:true,madcatSource:'raw',complete:true});await tick();assert.equal(binReads,2);assert.equal(measureReads,2);assert.equal(api.getState().entries[0].bin,'BIN2');assert.equal(api.getState().entries[0].madcat,'NO');assert.equal(api.getState().container,'csX222');
});
