import test from'node:test';import assert from'node:assert/strict';import{JSDOM}from'jsdom';import{readFileSync}from'node:fs';
const tick=async()=>{for(let i=0;i<12;i++)await new Promise(r=>setTimeout(r,0));};
test('generated Tote real readers coalesce exact enrichment while preserving product reads, barcode verification and physical scans',async t=>{
 const w=new JSDOM('<head></head><body>',{url:'https://fcresearch-fe.aka.amazon.com/BWU2/results#fcr-tote-checker',runScripts:'outside-only'}).window;t.after(()=>{w.dispatchEvent(new w.Event('pagehide'));w.close();});w.unsafeWindow=w;w.stop=()=>{};w.TextDecoder=TextDecoder;const counts={product:0,inventory:0,bin:0,measurement:0};
 const product='<div data-section-type="product"><table>'+Object.entries({ASIN:'B012345678',FNSKU:'X012345678',FCSKU:'ZZ12345678',Title:'Synthetic test product',Dimensions:'1 x 2 x 3',Sortable:'Yes'}).map(([k,v])=>'<tr><th>'+k+'</th><td>'+v+'</td></tr>').join('')+'</table></div>';
 const labels=['Container','ASIN','FNSKU','FCSKU','LPN','Quantity','Disposition','Consumer','Consumer ID','Outer Location','Outer Location Type','Title'],values=['tsX111','B012345678','X012345678','ZZ12345678','','3','SELLABLE','STOW','','P-1-A001','BIN','Synthetic test product'];
 const inventory='<table id="table-inventory"><thead><tr>'+labels.map((label,i)=>'<th>'+label+(i===5?' (3)':'')+'</th>').join('')+'</tr></thead><tbody><tr>'+values.map(v=>'<td>'+v+'</td>').join('')+'</tr></tbody></table>';
 w.fetch=async(url,options)=>{const section=new w.URL(url).pathname.split('/').at(-1);assert(['product','inventory'].includes(section));counts[section]++;return new Response(section==='product'?product:inventory);};
 const token='header.'+Buffer.from(JSON.stringify({token_use:'id',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.signature';w.GM_getValue=(key,fallback)=>key==='tm-v4.measurement.auth'?JSON.stringify({token}):fallback;w.GM_setValue=()=>{};w.GM_addValueChangeListener=()=>{throw new Error('Cached synthetic token requires no frame');};w.GM_removeValueChangeListener=()=>{};
 w.GM_xmlhttpRequest=options=>{const url=new w.URL(options.url);let data;if(url.hostname==='pandash.amazon.com')data=options.method==='GET'?{restriction:'AU'}:{rows:[{asin:'B012345678',level:0,message:'can be processed'}]};else if(url.hostname==='aft-poirot-website-nrt.nrt.proxy.amazon.com'){counts.bin++;data={items:[{scannableId:'X012345678',skuDetail:{fnSku:'X012345678',asin:'B012345678',fcSku:'ZZ12345678'},binDescription:'SMALL'}]};}else{assert.match(url.pathname,/\/measurementEvents\/X012345678\/FNSKU/);counts.measurement++;data={measurementEvents:[]};}options.onload({status:200,finalUrl:options.url,responseText:JSON.stringify(data)});return{abort(){}};};
 w.eval(readFileSync(new URL('../FC_Lite.user.js',import.meta.url),'utf8'));const input=w.document.querySelector('#tm-v4-tote input'),scan=async code=>{input.value=code;input.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await tick();};await scan('tsX111');await scan('X012345678');await scan('B012345678');assert.equal(counts.bin,1,JSON.stringify(counts)+' '+w.document.querySelector('[data-status]').textContent+' '+w.document.querySelector('[data-physical]').textContent);assert.equal(counts.measurement,1);assert.equal(counts.product,2);assert.equal(w.document.querySelectorAll('[data-physical] tbody tr').length,2);await scan('012345678905');assert.equal(counts.product,4,'numeric barcode still resolves then verifies its exact native product');assert.equal(counts.bin,1);assert.equal(counts.measurement,1);assert.equal(w.document.querySelectorAll('[data-physical] tbody tr').length,2);assert.match(w.document.querySelector('[data-summary]').textContent,/3\/3u/);w.document.querySelector('[data-madcat]').click();await tick();assert.equal(counts.measurement,2);
});
